### ISSUE TITLE
Opening splits opens to the left of nerdtree

### ISSUE THREAD

**Issue by sinks** [scrooloose/nerdtree#1003]
### Environment
* Operating System: Linux
* Vim version `NVIM v0.3.7`: 
* NERDTree version `28eb47e`: 
* NERDTree settings applied in your vimrc, if any:
    
```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'scrooloose/nerdtree'

call plug#end()

let mapleader = "\<Space>"
map <leader>n :NERDTreeFind<CR>
 ```

### Process

1. nvim .
2. select file
3. `space+n`
4. nerd tree is opened expanded
5. open file with `s`
6. new buffer opens to the left of nerd tree

### Current Result
4. nerd tree is opened expanded
6. new buffer open to the left

### Expected Result
4. nerd tree is opened not expanded
6. new buffer is open to right of nerd tree pane

### Possible Fix
revert to previous commit (67fa9b3) does not have this issue

**Comment by Kejie-Wang** [comment]
same issue.

**Comment by PhilRunninger** [comment]
#1001 is the fix for this. I'll merge it now.
