### ISSUE TITLE
e management

### ISSUE THREAD

**Issue by alanjohnson** [scrooloose/nerdtree#1004]
### Environment

* Operating System: 
* Vim version `:version`: 
* NERDTree version `git rev-parse --short HEAD`: 
* NERDTree settings applied in your vimrc, if any:
    ```vim
    ```

### Process

1.

**Comment by PhilRunninger** [comment]
No info. Closing.

**Comment by alanjohnson** [comment]
Errrrmmm.  I have NO idea how this ticket got created.  I’m hoping my kid mashed some keys when I was away, and that this isn’t the first sign of a split personality disorder.  :/
