### ISSUE TITLE
NERDTree show large error message and becomes unusable

### ISSUE THREAD

**Issue by arlopurcell** [scrooloose/nerdtree#1006]
### Environment

* Operating System: Ubuntu 18.04
* Vim version: NVIM v0.2.2 (also happens on vim 8.0)
* NERDTree version `git rev-parse --short HEAD`: 9bedadd
* NERDTree settings applied in your vimrc, if any: none

### Process

1. just run `:NERDTree` anywhere

### Current Result
Shows this error message 
```
Error detected while processing function 188[2]..189[21]..234[1]..255[36]..131[1]..132[18]..1
51[3]..27[4]..28:
line   14:
E874: (NFA) Could not pop the stack !
E874: (NFA) Could not pop the stack !
... (many more lines of this)
```
Then, when I hit `q` to dismiss the message, NERDTree has opened and shows the current directory and its contents. When I try to open a subdirectory with <ENTER>, I get this error message:
```
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..78[26]..77[3]..<SN
R>29_activateDirNode[7]..134[3]..168[8]..157[8]..150[1]..151[3]..27[4]..28:        
line   14:
E874: (NFA) Could not pop the stack !
E874: (NFA) Could not pop the stack !
```
repeated 6 times with various numbers of "pop the stack" lines in between. When I dismiss this message. all the subdirectories have disappeared in the sidebar. Pushing `?` also shows the same error.

### Expected Result
NERDTree is usable

I'm sure this is some issue with my personal setup, but I can't think of what it could be and I don't know how to debug further. Please help

**Comment by PhilRunninger** [comment]
`~` is a special character in regular expressions, and it needs to be escaped. Line https://github.com/arlopurcell/dotfiles/blob/master/.vimrc#L196 needs to be:
```
let NERDTreeIgnore=['\.pyc$', '/\~$', '.egg-info[[dir]]']
```
Notice the backslash before the tilde.

**Comment by arlopurcell** [comment]
Thank you, I knew it would be something stupid on my part
