### ISSUE TITLE
New file template support

### ISSUE THREAD

**Issue by g4s8** [scrooloose/nerdtree#1010]
#### Self-Diagnosis
- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question
I'm using `augroup` with `BufNewFile` auto command to set up templates for some file types, e.g. for Java files I have a template which automatically create new class, changes the name of class to file name, etc:
```vim
augroup templates
  autocmd!
  autocmd BufNewFile *.java $r ~/.vim/templates/skeleton.java|call s:SetupJavaClass()

  fun! s:SetupJavaClass()
    exe "%s/__CLASS_NAME__/" . expand('%:t:r')
  endfun
augroup END
```
it's working fine when I create files using vim, e.g. `vim src/main/some/package/MyClass.java`, but it's not working in NERDTree, since it doesn't call `BufNewFile` when new file created.
Is it possible to handle some hooks from NERDTree and process new file creation in my `.vimrc` and apply custom templates and call vimscript functions?

Asked here aslo: https://vi.stackexchange.com/q/20429/9140

**Comment by PhilRunninger** [comment]
Since NERDTree creates a new file in the OS instead of the editor, the `BufNewFile` autocommand won't fire. The first thing I'd suggest is the `BufRead` autocommand. The file will have been created with zero length, so you could do something like this:
```vim
autocmd BufRead *.java if getfsize(expand('%'))==0|$r ~/.vim/templates/skeleton.java|call s:SetupJavaClass()|endif
```

**Comment by g4s8** [comment]
@PhilRunninger thanks, it's working
