### ISSUE TITLE
Display Error: when open a node, background color of empty lines change

### ISSUE THREAD

**Issue by Appalled** [scrooloose/nerdtree#1020]
#### Self-Diagnosis
- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [ ] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [ ] Operating System:  windows10
- [ ] Vim/Neovim version `:echo v:version`: NVIM V0.3.8
- [ ] NERDTree version, found on 1st line in NERDTree quickhelp `?`:  5.2.7
- [x] vimrc settings

    ```vim
    cd c:/other_file/gomo/
    "keyremap:
    :imap jk <Esc>

    "leader
    let mapleader=";"

    set encoding=utf-8

    call plug#begin('~/.vim/plugged')
    Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
    call plug#end()


    filetype plugin on
    " NERDTree config
    map <F2> :NERDTreeToggle<CR>
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") &&b:NERDTreeType == "primary") | q | endif
    let NERDTreeWinSize=31

    "NerdTree
    let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree
    let NERDTreeShowBookmarks=1


    au BufNewFile,BufRead *.py
                \ set tabstop=4 |
                \ set softtabstop=4 |
                \ set shiftwidth=4 |
                \ set textwidth=79 |
                \ set expandtab |
                \ set autoindent |
                \ set fileformat=unix |

    au BufNewFile,BufRead *.js,*.html,*.css
                \ set tabstop=2 |
                \ set softtabstop=2 |
                \ set shiftwidth=2 |
    ```
    - [ ] NERDTree variables

    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. open nerdtree
2. open a node

The problem occurs after i updated nerdtree through vim-plug on 2019-07-11,
and command ':mode‘  will remove these dark lines.

#### Current Result (Include screenshots where appropriate.)
![image](https://user-images.githubusercontent.com/22954918/61018628-08ed4700-a3ca-11e9-8262-e41285bf29f6.png)

#### Expected Result
![image](https://user-images.githubusercontent.com/22954918/61018662-30dcaa80-a3ca-11e9-9e09-ddc132e17c98.png)

**Comment by PhilRunninger** [comment]
What does the command `:echo has('nvim')` print out?

**Comment by Appalled** [comment]
> What does the command `:echo has('nvim')` print out?

:echo has('nvim') returns 1
python3 and node.js provider work normally.

**Comment by RobertAudi** [comment]
@PhilRunninger I'm not sure this is related, but I noticed that since #1019 was merged, when using NeoVim, everytime I open a node in NERDTree the screen flickers. I believe that is because the whole screen is redrawn (as explained in the PR). If this is a different "bug" then I can create another issue.

**Comment by mihaelartz** [comment]
I have same issue
