### ISSUE TITLE
Ability to have multiple file trees in a single tab.

### ISSUE THREAD

**Issue by Qualphey** [scrooloose/nerdtree#1022]
I want to use multiple file tree windows on a single tab so I wrote a little function that splits the tree window and opens up a window level tree below the main one.

Example:
```
|``````````````|````````````````|
|  Main tree   |                |
|______________|                |
|              |  some.script   |
| Window level |                |
|     tree     |                |
|______________|________________|
```

The problem is that the window level tree always replaces itself with the selected file instead of opening it somewhere else. I was looking for a way to configure that secondary kind of tree, but had no luck (I've read the whole documentation).

So I'm asking you to implement one of these features:
- Ability to configure window level trees to open files outside of it's window
**_or_**
- Ability to have multiple "main" trees in a tab

I hope I'm not asking too much. Please let me know if I can help you in any way! :)

**Comment by PhilRunninger** [comment]
This is a very unusual use case for NERDTree. While you can create two NERDTree windows, the code isn't designed to handle that situation, and will only recognize the first NERDTree window it finds on a tab. To make NERDTree work as you requested, will require a LOT a lot changes that likely would introduce a lot of regression errors.

See the discussion in #811 for a way to specify the window in which a file will be opened. This is a PR meant to integrate NERDTree with another plugin - [ChooseWin](https://github.com/t9md/vim-choosewin) - for that purpose.
