### ISSUE TITLE
May be NERDTree need natural sort for files, or sub-folders

### ISSUE THREAD

**Issue by kyoz** [scrooloose/nerdtree#1023]
#### Description

Seem like NERDTree doesn't support natural sort for files in a folder, or sub folders...

Is there a way i can change it. Or can we make it a feature for NERDTree ?

<img width="292" alt="Screen Shot 2019-07-22 at 21 43 55" src="https://user-images.githubusercontent.com/29815830/61641796-f9bfa080-acc9-11e9-9add-25e8e4986acf.png">

Thank you you all for such a great plugin :heart:

**Comment by PhilRunninger** [comment]
I'm going to call this one a bug, and I'll look into it soon.

**Comment by PhilRunninger** [comment]
I may have been premature in labeling this a bug. I tried confirming it as such this morning, and all seems to be working well. I was prepared to make changes, thinking perhaps the period was causing issues, but that doesn't appear to be the case either. The only thing I can think of is your settings. Do you have 
```
let NERDTreeNaturalSort = 1
```
in your `vimrc`? That will turn on natural sorting, and it works with both files and folders.

**Comment by kyoz** [comment]
Yep, thanks @PhilRunninger. It work perfectly. Btw i think it should be in the doc too.

**Comment by PhilRunninger** [comment]
See `:h NERDTreeNaturalSort`. It's already there.
