### ISSUE TITLE
How to copy the content of file to the pasteboard?

### ISSUE THREAD

**Issue by yiran7324** [scrooloose/nerdtree#1024]
## Self-Diagnosis
- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [ ] I have reviewed the NERDTree documentation. `:h NERDTree`
- [ ] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question

Is it possible to copy the content of a file in nerdtree? Till now what I've tried is using `!cat FILE`, but using command mode of vim seems inconvenient.

**Comment by PhilRunninger** [comment]
No, NERDTree doesn't have that capability. Could you describe your situation a little better? There could be many different ways to do what you're attempting, depending on what you do with the text after copying it.

* To do only what you're asking to do in vim, open the file, and then use these normal mode keystrokes: `gg"*yG`. See `:h clipboard`
* If you want to insert a file into another, use the `:r FILE` command instead.
* Outside of vim, you have the Unix pipeline and redirection at your disposal, which may even negate the need to use the clipboard.

**Comment by yiran7324** [comment]
Thanks a lot.
