### ISSUE TITLE
Is there any way to open nerdtree in current window?

### ISSUE THREAD

**Issue by mkwork** [scrooloose/nerdtree#1025]
It seems to be usable at least on session load. I want to tile nerdtree in given position. When I open nerdtree window in other ways - it breaks already saved layout.

**Comment by PhilRunninger** [comment]
If you don't have `:let NERDTreeHijackNetrw = 0` (The default is 1.) in your .vimrc, then you can use `:edit <path>` or `:e <path>` for short. That will open a NERDTree in the current Vim window instead of splitting the window first.

**Comment by mkwork** [comment]
It doesn't work as expected. When I use `NERDTreeFind` - other NERDTree window opening and breaking layout, instead of using already opened instance.

**Comment by PhilRunninger** [comment]
That is correct. You need to use the native vim command `:edit <path>`, which NERDTree will intercept. It then shows the NERDTree buffer in the current window. All other NERDTree commands - `:NERDTree <path>`, `:NERDTreeFind <path>`, `:NERDTreeFocus` - will split the current window, and display the tree there.
