### ISSUE TITLE
Github sorting?

### ISSUE THREAD

**Issue by 9mm** [scrooloose/nerdtree#1027]
#### Description

I'm wondering how hard it would be to sort things alphabetically but by file type, similar to how GitHub does it (notice all the *.go source files are next to each other, and all the misc crap files like README and such are elsewhere in the same list)

https://github.com/uber-go/zap

**Comment by PhilRunninger** [comment]
You can use `g:NERDTreeSortOrder` to group specific filetypes together in the listing, but currently there is nothing to sort by filename as you request. Looking at the source just now gave me an idea for implementing your request. Stay tuned.

**Comment by 9mm** [comment]
Dude you are the man... staying 📺tuned

**Comment by PhilRunninger** [comment]
@9mm , check out the documentation `:h NERDTreeSortOrder` to learn how to use the new sorting capabilities.

**Comment by 9mm** [comment]
dude you are awesome! Thank you :D
