### ISSUE TITLE
Make buffer name the directory name

### ISSUE THREAD

**Issue by wincent** [scrooloose/nerdtree#1028]
#### Description

Got this idea from [vim-dirvish](https://github.com/justinmk/vim-dirvish), from the README:

> ### Buffer name is the directory name
>
> So commands and plugins that work with `@%` and `@#` do the Right Thing.
>
> - Create directories:
>   ```
>   :!mkdir %foo
>   ```
> - Create files:
>   ```
>   :e %foo.txt
>   ```

Basically, if you explore a directory in vim-dirvish, `:echo expand('%')` will print the directory name. As the README suggests, you can do something like `:e %<tab>` and you'll see the path of the directory expand and you can easily create a new file inside the directory.

In NERDTree, if you do `:echo expand('%')` you'll get a name like "NERD_tree_1", and `:e %<tab>` won't do anything. I tend to use `:e %` quite a bit, so muscle memory kicks in and I'm always disappointed when I see it doesn't work in NERDTree.

**Comment by PhilRunninger** [comment]
Interesting idea. I'll look into it. I think the buffer name is rather inflexible currently.

**Comment by PhilRunninger** [comment]
@wincent After further consideration, I'm going to say "No" to this request. There are just too many places that require the buffer name to follow its current pattern. I could maybe get it working in NERDTree alone, but I'd run the risk of breaking a bunch of other plugins that work with NERDTree.

I did come up with something you can put into your `vimrc` that's a step in your request's direction.

```vim
augroup NERDTreeStuff
    autocmd!
    autocmd FileType nerdtree nnoremap <buffer> % :vsp <C-R>=b:NERDTreeRoot.path.str()<CR>/
augroup END
```

It's not `:e %<Tab>`, but it's close.
