### ISSUE TITLE
feature request:  expand gvim window when opening NERDTree

### ISSUE THREAD

**Issue by benjifisher** [scrooloose/nerdtree#103]
When I open a NERDTree in a gvim window, I would like it to make the window wider instead of stealing columns from the file I am editing.  The Tagbar plugin has such an option.

I will write this myself, but not if someone already has ... or if it is already possible and I did not RTFM carefully enough.

**Comment by PhilRunninger** [comment]
This is a good candidate to be written as a NERDTree plugin, rather than being placed in the NERDTree core code.
