### ISSUE TITLE
create a file with template

### ISSUE THREAD

**Issue by YvesZHI** [scrooloose/nerdtree#1030]
#### Description

Create a file with Nerdtree is to type `m` then `a`.

But this always makes an empty file.

I think creating a new file with a template would be a useful function. For example, if we create a file with the extension `.py` or `.h` and Nerdtree can put some content by default in it, it should be great.

**Comment by PhilRunninger** [comment]
I'm not going to build this into the base NERDTree. This is a perfect example of something that would be written as a NERDTree plugin. I could see it perhaps integrating NERDTree with one of the snippets Vim plugins that are out there: https://github.com/sirver/ultisnips, https://github.com/garbas/vim-snipmate, or https://github.com/shougo/neosnippet.vim, to name a few.

**Comment by PhilRunninger** [comment]
See also https://github.com/scrooloose/nerdtree/issues/1010 for another way to implement this functionality.
