### ISSUE TITLE
Refocusing issues with vim-airline when NERDTree window closes

### ISSUE THREAD

**Issue by jinscoe123** [scrooloose/nerdtree#1036]
#### Self-Diagnosis
- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: Manjaro
- [x] Vim/Neovim version `:echo v:version`: Nvim v0.3.8, Vim 8.1
- [x] NERDTree version, found on Operating1st line in NERDTree quickhelp `?`: 5.3.1
- [x] vimrc settings
    - [x] NERDTree variables
    ```vim
    call plug#begin( '~/.vim/plugged' )
    Plug 'vim-airline/vim-airline'
    Plug 'scrooloose/nerdtree'
    call plug#end()

    let mapleader=','
    nnoremap <Leader>n :NERDTreeFocus<CR>
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [ ] I've verified the issue occurs with only NERDTree installed.
        - **I don't know how else to observe the issue, without vim-airline being installed.**

#### Steps to Reproduce the Issue

With the above configuration, type the following within Neovim/Vim:

,n
q

^Vim-airline status line does NOT refocus.

,n
:q 

^Vim-airline status line refocuses.

#### Current Result (Include screenshots where appropriate.)

![image](https://user-images.githubusercontent.com/3609458/64831514-0c58a680-d5a4-11e9-86c3-047b334ea1ef.png)

#### Expected Result

![image](https://user-images.githubusercontent.com/3609458/64831524-18446880-d5a4-11e9-801d-c3a74d8d4dc6.png)

#### Extra

The bug seems to be in the `s:NERDTree.Close()` function in [lib/nerdtree/nerdtree.vim](https://github.com/scrooloose/nerdtree/blob/master/lib/nerdtree/nerdtree.vim). I've tried executing some of the code from that function manually at the vim command line with the NERDTree window in focus, and I get the same issue.

```vim
:call nerdtree#exec("close", 1) | call nerdtree#exec("call win_gotoid(" . win_getid() . ")", 0)
```

<br/>
<br/>
Related: vim-airline/vim-airline#1968, #801

**Comment by jinscoe123** [comment]
Changing the `1` to a `0` fixes that refocus issue, but if you have multiple windows open, then it will always focus on the first one, rather than the previous one.

For example, if you open Neovim/Vim and type the following:

```vim
:vsp
:NERDTreeFocus
:call nerdtree#exec("close", 0) | call nerdtree#exec("call win_gotoid(" . win_getid() . ")", 0)
```

Rather than refocusing on the second virtual split, it refocuses on the original one.

**Comment by PhilRunninger** [comment]
Try checking out branch 1036, and see if that fixes your issue. 

The second issue you reported is caused by your omitting some important statements. The following statements more closely match what `s:NERDTree.Close()` is doing.
```vim
:vsp
:NERDTreeFocus
wincmd p
let w = win_getid()
wincmd p
:call nerdtree#exec("close", 0) | call nerdtree#exec("call win_gotoid(" . w . ")", 0)
```

**Comment by jinscoe123** [comment]
Yes, that fixes the issue! Thanks so much! :smiley:
