### ISSUE TITLE
Undefined variable: splitMode

### ISSUE THREAD

**Issue by dambrisco** [scrooloose/nerdtree#1039]
Introduced by #1035, the `let` is removed at https://github.com/scrooloose/nerdtree/pull/1035/files#diff-aacb944c971018c39683b783f57a1d4eL189 and the variable is subsequently referenced at https://github.com/scrooloose/nerdtree/pull/1035/files#diff-aacb944c971018c39683b783f57a1d4eR178.

I'm unsure if simply reintroducing the removed `let` would fit the goals of the PR, although it does resolve the error.

**Comment by sethen** [comment]
Having the same error.
