### ISSUE TITLE
A note about auto-openning NERDTree

### ISSUE THREAD

**Issue by determin1st** [scrooloose/nerdtree#1050]
In the readme FAQ, you have the following Q:

> How can I open a NERDTree automatically when vim starts up if no files were specified?

and the answer:

```vim
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
```

Which interfere with session. If there is a session, opened with `gvim -S x.vim`, for example, the NERDTree will automaticly openup, which is not needed 99% my bet. So, this:

```vim
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") && v:this_session == "" | NERDTree | endif
```

..may suit better. Or, maybe, wrap it into function and use setting, like:

```vim
let g:NERDTreeOpenWhenNoFile=1
```

**Comment by PhilRunninger** [comment]
This is in the realm of user customization, to be done only in the .vimrc. No new function or setting. I will update the readme.

**Comment by determin1st** [comment]
Roger that :+1:
