### ISSUE TITLE
Undo move/delete of file or folder

### ISSUE THREAD

**Issue by geoyws** [scrooloose/nerdtree#1054]
#### Description

Sometimes we may make a mistake and want to quickly return to previous state.

**Comment by PhilRunninger** [comment]
NERDTree uses `rm` for *nix and Mac, and `del` and `rmdir` for Windows. These provide no mechanism for undoing a deletion. If there is a 3rd party application that provides undo capabilities, you can specify it in the `NERDTreeRemoveFileCmd` and `NERDTreeRemoveDirCmd` options. See the help file for more details: `:help NERDTree`
