### ISSUE TITLE
Opening a tree always opens a second tree of parent directory

### ISSUE THREAD

**Issue by BRS7** [scrooloose/nerdtree#1057]
When using :NERDTree or :NERDTreeToggle the commands will always open a second tree of the parent directory. Adding a directory argument doesn't seem to change this (ex: :NERDTree $PWD).
Is there a way to only open the current directory tree and not the second parent tree? Im not sure if this is a bug or a feature

**Comment by lucianoratamero** [comment]
+1

**Comment by PhilRunninger** [comment]
This should be opened as a bug. Please create a bug issue for this and provide all the required information.
