### ISSUE TITLE
let g:NERDTreeMapOpenInTab = <ENTER>

### ISSUE THREAD

**Issue by misakisuna705** [scrooloose/nerdtree#1058]
[x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
[x] I have reviewed the NERDTree documentation. `:h NERDTree`
[x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
[x] I have searched the web for an answer to my question.

Operating System: macOS 10.15.1 Catalina
Vim/Neovim version `:echo v:version`: vim 8.1.2250 
NERDTree version, found on 1st line in NERDTree quickhelp `?`: newest

vimrc settings (NERDTree variables)
```vim
let g:NERDTreeMapOpenInTab = '<ENTER>'
```

When I press ENTER on a file,
it can be open on a new tab normally.

However, when I press ENTER on a directory,
I think nerdtree should expend the content in that directory,
but nerdtree directly switch to that directory and open a new tab for itself.

**Comment by willfindlay** [comment]
Try <CR> instead of <ENTER>

**Comment by PhilRunninger** [comment]
Leave `g:NERDTreeMapOpenInTab` unchanged, that is, remove it from your `vimrc`. There is a setting for the Enter key that allows you to customize its behavior. See `:h NERDTree-<CR>` and `:h NERDTreeCustomOpenArgs`. The value you want, to open files in a new tab, and directories in the current tree, is:
```vim
let g:NERDTreeCustomOpenArgs = {'file':{'where':'t'}}
```

**Comment by misakisuna705** [comment]
@willfindlay Thank you ! It`s exactly what I want.
