### ISSUE TITLE
Undefined variable: v:t_func

### ISSUE THREAD

**Issue by pohaosu** [scrooloose/nerdtree#1068]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: Linux
- [x] Vim/Neovim version `:echo v:version`: 704
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.4.0
- [x] vimrc settings
    - [ ] NERDTree variables
    ```vim
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. Trigger any key in NerdTree

#### Expected Result
map key should work

#### Possible solution
Change key_map.vim: 69 to the following for backward compatibility
```vim
let Callback = type (self.callback) == type (function ("tr"))? self.callback: function (self.callback)
```

**Comment by PhilRunninger** [comment]
Fixed in c962796b030f39db596fde5048464e57c2c6ca8d. Thanks for catching that.
