### ISSUE TITLE
Syntax highlight loss in nerdtree when opening fortran files

### ISSUE THREAD

**Issue by danfisica** [scrooloose/nerdtree#11]
Hi! 
I've stumbled upon this weird problem: NerdTree losses all coloring when opening any fortran file (be it F77, F90, F95, fixed form, free form). Syntax highlighting is ok in the buffer of the file proper, though. It does not happen with c, c++, python, perl, shell, tex or any other type of file that I have tested.

**Comment by PhilRunninger** [comment]
@scrooloose , your instructions on Feb 7, 2011 don't show any change in the syntax. Has vim behavior changed, or is there something now in NERDTree to reestablish its syntax highlighting? I think we can close this one.

**Comment by scrooloose** [comment]
Yes good point. We can reopen this if it is reported again.

**Comment by mishaszu** [comment]
I have the same issue with JavaScript files on MacOS (10.12.6), vim version 8.0.666, no problem on Ubuntu. Syntax coloring works just fine when I open files via vim, but files are completely white if I open them with NERDTree
