### ISSUE TITLE
Issues between NERD Tree and MiniBufExpl

### ISSUE THREAD

**Issue by nrclark** [scrooloose/nerdtree#117]
I've noticed that NERD Tree and MiniBufExpl (as well as other tab-esque buffer managers) don't seem to play very well together. Specifically, when a buffer is closed in the buffer explorer, NERD Tree's file explorer moves to a different buffer split containing the buffer manager. I tried a few other buffer managers and NERD Tree does the same thing on all of them.

What causes this? Am I "doing it wrong" in a way I'm missing? Is there something similar to MiniBuf that I should use instead? Should I be using tabs for multiple documents instead of buffers?

**Comment by PhilRunninger** [comment]
This issue has been idle for 5 years, so I'm closing it. Feel free to reopen if necessary.
