### ISSUE TITLE
Use trailing root path component (or bookmark name) as tablabel.

### ISSUE THREAD

**Issue by guivho** [scrooloose/nerdtree#123]
Is it possible to use the last path component of the root path rather
than the non-informative NERD_tree_nn label name?

Such an informative label name may well be adorned to standout as
NERD_tree tab. e.g' like the [No Name] tab label provided by vim.

So a tab where the NERD_tree window is the active window and where  e.g.
my ~/.vim directory is the root, would have label [.vim] and for my home
directory it would be [guivho]

A similar feature request has been asked earlier, where the OP wanted
the bookmark name to be used as tablabel.
(https://github.com/scrooloose/nerdtree/issues/14)

I would like that the bookmark name (if it is the root of the current
tree) would be used; if it is not a bookmark tree, I would like the last
path component of the root, as explained above.

**Comment by PhilRunninger** [comment]
See #774.
