### ISSUE TITLE
:NERDTreeMirror on the wrong side

### ISSUE THREAD

**Issue by djmccormick** [scrooloose/nerdtree#13]
I'm using the following in my .vimrc file:

    autocmd VimEnter * NERDTree ~/Projects/
    autocmd TabEnter * NERDTreeMirror

Unfortunately when a tab is created the NERDTree split is on the right side and large and the file is on the left side and is very slim, presumably their positions have been reversed. Is there any solution for this?

**Comment by PhilRunninger** [comment]
Use the `TabNewEntered` event instead.

```
autocmd VimEnter * NERDTree ~/Projects/
autocmd TabNewEntered * NERDTreeMirror
```
