### ISSUE TITLE
arrow chars do not work on Windows 7 and Vim 7.3

### ISSUE THREAD

**Issue by mario-grgic** [scrooloose/nerdtree#135]
I have the latest NERDTree on both Mac OS X 10.6.8 and Windows 7 64 bit enterprise. On Mac OS X arrow chars are used to render the filesystem tree out of the box (MacVim, Terminal Vim and both Terminal app or iTerm2). On Windows |+ etc are used. If I force arrow keys with NERDTreeDirArrows=1 in _vimrc I still don't get arrow chars (I tried all kinds of modern fonts like Consolas and DejaVu Sans Mono etc), but instead get "â–¸" in both gvim and command prompt.

**Comment by chidea** [comment]
I opened `~/vimfiles/nerdtree/plugin/NERD_tree.vim` or `~/.vim/nerdtree/plugin/NERD_tree.vim`
and changed line 71 like below and it fixed the issue.
```
call s:initVariable("g:NERDTreeDirArrowExpandable", "▶")
call s:initVariable("g:NERDTreeDirArrowCollapsible", "▼")
```
Pretty sure Windows code page cp949 doesn't have slick arrow characters of NERDTree.

**Comment by PhilRunninger** [comment]
NERDTree has been rewritten since this issue was created, and there are options that can be set in your `vimrc` to specify the arrows:

```
let NERDTreeDirArrowExpandable = "▶"
let NERDTreeDirArrowCollapsible = "▼"
```
