### ISSUE TITLE
Bookmarks do not remain toggled off when opening a directory

### ISSUE THREAD

**Issue by andymcintosh** [scrooloose/nerdtree#138]
**Expected behavior**

  After pressing "B" to hide bookmarks, they should remain toggled off until "B" is pressed again to display them.

**Actual behavior**

  Bookmarks are displayed when opening a directory after using NERDTreeToggle to hide/show NERDTree.

**Steps to reproduce**
1. Issue NERDTreeToggle command to open NERDTree.
2. Press "B" to toggle off bookmarks.
3. Close NERDTree with "q".
4. Issue NERDTreeToggle again to reopen NERDTree. Notice that the bookmarks remain toggled off.
5. Press "o" to open a directory. Notice that the bookmarks are toggled on.

**Comment by PhilRunninger** [comment]
Fixed some time ago. Not sure when.
