### ISSUE TITLE
Open in new tab silently (‘T’) is ignored in new window

### ISSUE THREAD

**Issue by Debilski** [scrooloose/nerdtree#146]
*This may be by design (at least the code looks a bit like it) but since the behaviour has been changed I’ll mention it.*

After opening vim on a new directory

    vim .

nerdtree has populated the complete window. In this situation both `t` and `T` produce the same result. Both open the file in a new tab and switch to it. Previous behaviour was that `T` would open the tab in the background (which still happens when nerdtree is opened in a split window). Is this new behaviour by design?

**Comment by melhakim** [comment]
I know this might be two years old, but any updates on this one?

**Comment by ben-albrecht** [comment]
I know this might be three years old, but any updates on this one?

**Comment by scrooloose** [comment]
Finally, after five long years this is fixed. Let me know if there are any further issues with this. Thanks for the patience :)

**Comment by ben-albrecht** [comment]
Hey @scrooloose , thanks for setting aside some time for this issue. The fix works well for me.
