### ISSUE TITLE
Allow bookmarks to use environment variables

### ISSUE THREAD

**Issue by gburca** [scrooloose/nerdtree#147]
I often work on 2 or more different versions of a project in parallel. Each terminal has an environment variable that defines the root of the project. It would be nice if I could define bookmarks like:

base $PROJ/frameworks/base

That bookmark would then point to a different location, depending on the terminal in which vim is running. Currently I have to maintain a separate bookmark for each project.

**Comment by hiberabyss** [comment]
I run into the same problem when I switch from Ubuntu to Mac, please consider adding this useful feature. Thanks :)

**Comment by PhilRunninger** [comment]
Closing this issue for the reasons mentioned in #792.
