### ISSUE TITLE
Improve handling when using NERDtree with a mouse

### ISSUE THREAD

**Issue by fpauser** [scrooloose/nerdtree#148]
To correct the very annoying "jumping-cursor-behavior" when switching between windows/buffers via mouse NERDtree should include the following snippet:

```
augroup NO_CURSOR_MOVE_ON_FOCUS
  au!
  au FocusLost * let g:oldmouse=&mouse | set mouse=
  au FocusGained * if exists('g:oldmouse') | let &mouse=g:oldmouse | unlet g:oldmouse | endif
augroup END
```

Taken from http://vim.wikia.com/wiki/How_to_not_move_cursor_when_selecting_window_with_mouse

**Comment by PhilRunninger** [comment]
This behavior seems to have been implemented sometime in the last 5.5 years. Closing.
