### ISSUE TITLE
Feature Request: Auto minimize NERDTree window

### ISSUE THREAD

**Issue by rrrrutdk** [scrooloose/nerdtree#15]
Can NERDTree window be minimized automatically when opening a file node (o, go, i, gi, s, gs)?

**Comment by jiminoc** [comment]
+1

**Comment by PhilRunninger** [comment]
@lifecrisis I propose this way of implementing the request: If zoomed (using key `A`) and a file is chosen to be opened, and `NERDTreeQuitOnOpen == 0`, then set NERDTree's width back to the `NERDTreeWinSize` value.

**Comment by PhilRunninger** [comment]
Implemented by #870.
