### ISSUE TITLE
Add little git support in NerdTree

### ISSUE THREAD

**Issue by gnujeremie** [scrooloose/nerdtree#153]
It would be great to see new/modified/deleted files in Nerdtree, with git :

<pre>> dir/
    + a.txt    (a new/modified file, not yet commited)
      b.txt
    - c.txt    (a deleted file, not yet commited)
</pre>
Something like this.

**Comment by digitalronin** [comment]
This is fantastic! Exactly what I was looking for. Thank you.

**Comment by scrooloose** [comment]
I have added an FAQ to the readme that points to the excellent https://github.com/Xuyuanp/nerdtree-git-plugin.
