### ISSUE TITLE
Sexplore opens both Netrw and NERDTree

### ISSUE THREAD

**Issue by lunchboxer** [scrooloose/nerdtree#155]
With NERDTreeHijackNetrw set to 1 NERDTree replaces the default file explorer except when using Explore and its variants. I have sometimes had the experience of NERDTree then opening once the Netrw window invoked by Explore is done. This happens whenever the selected file is opened in an window other than the current Netrw, such as happens when hitting t,s, or v. The ideal behavior would be for NERDTree to also replace Netrw when using Explore and all of its variants whenever NERDTreeHijackNetrw=1. Alternatively it would be almost just as useful to have NERDTree emulate Explore by opening NERDTree with the directory of the current file. I could do this with a line in .vimrc but I can't sort out how to pass anything but a literal string as an argument to NERDTree.

I'd like to use :NERDTREE =expand('%:p:h') but it doesn't like it. There may be a much better way of doing this but my knowledge of Vimscript is very limited.

**Comment by PhilRunninger** [comment]
You should be using `:NERDTree [<start-directory> | <bookmark>]`, `:NERDTreeToggle [<start-directory> | <bookmark>]`, or `:NERDTreeFind` commands to open a NERDTree window. `let NERDTreeHijackNetrw = 1` is used to intercept the `:e <directory>` command, and show a NERDTree instead of the netrw directory listing.

**Comment by techfishio** [comment]
@PhilRunninger is it possible to make `NERDTree` / `NERDTreeToggle` open in the current window (same behavior as `:e .`)?

**Comment by PhilRunninger** [comment]
No. NERDTree always opens in a separate window.
