### ISSUE TITLE
NERDTree - no bookmarks on startup

### ISSUE THREAD

**Issue by edanm** [scrooloose/nerdtree#160]
Hi,

I wanted to open NERDTree automatically on vim startup. Problem is, if I set it using autocmd VimEnter, it appears as though the Bookmarks file isn't properly loaded.

Specifcally, I get the NERDTree window all right, but instead of bookmarks I have an empty space. If I hit "b" twice to toggle the bookmarks on, then off, my bookmarks correcttly appear.

I'm pretty sure it's not a problem with my config, since each part works individually (without the startup autocmd, just opening NERDTree manually DOES show the bookmarks properly).

My code for adding NERDTree on startup:

function! StartUp()
    if 0 == argc()
        NERDTree vim
    end
endfunction
autocmd VimEnter \* call StartUp()

Thanks!

**Comment by PhilRunninger** [comment]
See the three FAQs starting with https://github.com/scrooloose/nerdtree/wiki/F.A.Q.#how-can-i-open-a-nerdtree-automatically-when-vim-starts-up for better ways of opening NERDTree when vim startup. The Bookmarks are correctly being displayed now.
