### ISSUE TITLE
Disable NERDTreeInvalidBookmarks Error?

### ISSUE THREAD

**Issue by jhogendorn** [scrooloose/nerdtree#168]
Hey, sometimes my bookmarks are invalid due to having stuff unmounted.

Can I disable the startup error here, or alternatively store bookmarks per project?

**Comment by foges** [comment]
+1 I'm using sshfs and don't always have drives mounted.

**Comment by harobed** [comment]
+1

**Comment by harobed** [comment]
To disable this message, replace 0 by 1 in this line https://github.com/scrooloose/nerdtree/blob/master/autoload/nerdtree.vim#L97

**Comment by jm3** [comment]
since hand-hacking the plugin source would break installing via plugin managed e.g. Vundle or Vim-Plug, could this be a configuration option instead? if someone can point me in the right direction, i'd be happy to submit a PR for this.

**Comment by scrooloose** [comment]
Sorry for the 2 year delay :)

I have just disabled this warning for now. I dont want to add any more options etc as I'll be overhauling/replacing bookmarks with projects shortly (https://github.com/scrooloose/nerdtree-project-plugin).
