### ISSUE TITLE
Error E95: buffer with this name already exists when restoring PHP debug session

### ISSUE THREAD

**Issue by donnut** [scrooloose/nerdtree#169]
Issue is raised after stopping debugging PHP classes using BDGp or BDGPavim. When closing the debug session, the previous edit session is restored (I assume) and this error is raised. The exact message is:

```
Error detected while processing /home/...../dbgpavim_saved_session.1340:
line 205:
E95: Buffer with this name already exists
```

**Comment by PhilRunninger** [comment]
I don't see how this is a NERDTree issue. Closing.
