### ISSUE TITLE
Improve path copy/move/delete support for multi nodes

### ISSUE THREAD

**Issue by domenkozar** [scrooloose/nerdtree#17]
Currenty one can not do something like:
- select a tree node (eg. /home/user/)
- press m
- choose copy or move
- add two levels or more deep nodes (eg /home/user/folder/file.py)

**Comment by PhilRunninger** [comment]
NERDTree will copy, move, or delete folders just fine. At least it does now in 2016. The problem may have been in your example. It looks like you're trying to move or copy a folder to a location within itself. This is impossible in any environment without runaway recursion. I'm closing this issue, but it can be reopened with additional description if necessary.
