### ISSUE TITLE
Error Clicking on NERDTree Empty Space > Easy Fix

### ISSUE THREAD

**Issue by edwardbeckett** [scrooloose/nerdtree#176]
This isn't too terribly important ... But it does become a nuisance ... 
When the root directory is closed, leaving only one directory, clicking on the empty space below the link will result in an error ... 

E684: List Index Out of Range: 0
E15: Invalid Expression line[i] 

The solution is simple .... Just wrap the startToCur loop in try catch blocks ...

<pre>

"FUNCTION: s:handleLeftClick() {{{2
"Checks if the click should open the current node
function! s:handleLeftClick()
    let currentNode = s:TreeFileNode.GetSelected()
    if currentNode != {}

"the dir arrows are multibyte chars, and vim's string functions only
"deal with single bytes - so split the line up with the hack below and
"take the line substring manually

        let line = split(getline(line(".")), '\zs')
        let startToCur = ""
        for i in range(0,virtcol(".")-1)
           try
             let startToCur .= line[i]
                catch
                 call s:echoWarning("You Must Click a Link")                
           endtry       
        endfor

</pre>

**Comment by PhilRunninger** [comment]
No longer an issue. The root node cannot be collapsed any more, and clicking an empty line does not cause an error.
