### ISSUE TITLE
Problem with capital Q and capital W in nerdtree menu

### ISSUE THREAD

**Issue by yoopea** [scrooloose/nerdtree#185]
In the nerdtree menu, I want to add a new node having capital Q in its name. Typing 'shift-q' (azerty keyboard), I always get a lower-case q instead of capital Q.

Same behaviour with move/copy actions and with capital W (azerty keyboard).

Thank you for solving this issue,

**Comment by PhilRunninger** [comment]
This issue has been idle for a while, so I'm closing it. Feel free to reopen if necessary.
