### ISSUE TITLE
Buffer issues

### ISSUE THREAD

**Issue by Zielun** [scrooloose/nerdtree#187]
NERDTree is not on a buffer list (:ls) so if you switch between opened buffers being in NERDTree split (by accident) you overwrites it and can't switch back to the NERDTree. Is it the intended behaviour? Can I disable it from within .vimrc? (being in NERDTree switching buffers doesn`t work).

I also noticed strange behaviour in this case:
- open a file
- open NERDTree (NERDTree is on the left side of the file buffer)
- type :help bn (to have anothe split above)
- go to file buffer (CTRL+W+j)
- close it (:q)
- next file you open via NERDTree appears below (horizontal split). Not as it should on the right side
- Additionally when you close and reopen NERDTree it has the width of your screen and all splits (help split the was opened horizontally) is moved beyond the screen (to the right side). 

Maybe it`s just a matter of lack of configuration but it looks bad and buggy as a default behaviour.

**Comment by PhilRunninger** [comment]
Confirmed bug.

**Comment by PhilRunninger** [comment]
Here is a workaround that will prevent the NERDTree window from being replaced by another buffer. Just place this in your vimrc. **Be warned: this is not fully tested.**
```vim
autocmd BufEnter * if bufname('#') =~# "^NERD_tree_" | b# | endif
```

**Comment by PhilRunninger** [comment]
As I look at this more, I believe there is no bug in NERDTree. It's just the way buffers and windows work in Vim.

Concerning the width of NERDTree, it remembers the width of its last window, and when it's reopened, it will reappear at that width. If NERDTree was in a full width window previously, you can do this to restore it to a normal size when you reopen it. Press `A` to maximize the window (It will appear to do nothing), and then again to restore it back to its normal size.
