### ISSUE TITLE
NERDTreeFind does not mark hidden file

### ISSUE THREAD

**Issue by stabilobox** [scrooloose/nerdtree#189]
For a hidden file the `:NERDTreeFind` will find the CWD but doesn't place the cursor on the file. Rather it marks the first directory entry.

E.g. open `~/.vimrc` and do `:NERDTreeFind`

A `:NERDTreeFind I` also does not do the trick.

**Comment by mboughaba** [comment]
I get this issue too on GViM (Windows). It works fine on Linux.

**Comment by lifecrisis** [comment]
Thanks for the report, guys. Just confirmed this bug. It will take some investigation to fix this properly.

**Comment by lifecrisis** [comment]
@mboughaba and @stabilobox, you should both be able to update the NERDTree and have your problem fixed. Let me know if the issue is not corrected...
