### ISSUE TITLE
Hijack Netrw Explore command?

### ISSUE THREAD

**Issue by cvincent** [scrooloose/nerdtree#192]
I have NERDTree setup to hijack Netrw, but it doesn't work when I do the Explore command. I tried finding an autocmd which would fire when Netrw loads in via the Explore command, but I couldn't get anything to work. Does anyone have a workaround?

**Comment by Rulqu** [comment]
You can insert `command E e .` or `command Explore e .` to .vimrc so it edits the current folder instead.
