### ISSUE TITLE
NERDTree opening with cursor

### ISSUE THREAD

**Issue by benmezger** [scrooloose/nerdtree#193]
More a question than an issue. 
I added NERDTree to the autoload, when doing vim file the file opens and NERDTree opens with it. 
The problem is when opening vim file it opens with the cursor on the NERDTree and not in the opened file. Is there anyway I can open the file with the cursor directly opened in the file and not in NERDTree?

Cheers.

**Comment by PhilRunninger** [comment]
The [FAQ](https://github.com/scrooloose/nerdtree/wiki/F.A.Q.) contains some suggestions for opening NERDTree on startup.
