### ISSUE TITLE
Can I make NerdTree available always at left?

### ISSUE THREAD

**Issue by santosh** [scrooloose/nerdtree#195]
I want to see NERDTree window at the left of the editor window right from the time I start VIM. Is it currently possible? How can I do so?

**Comment by avesus** [comment]
NERDTree has defaults not meeting expectations of those from Visual Studio world. Nothing works as expected. DIY product, as most of OSS.
Here’s my $500 spent .vimrc for NERDTree: https://gist.github.com/avesus/1954d9384d86cc1e39cb2b2eff7017b7

**Comment by lifecrisis** [comment]
There's not really an issue here. No real problems with the NERDTree are reported that we can fix. Everything here can be addressed with proper configuration on the user's end.

For this reason, this issue is closed.

**Comment by TwelveNights** [comment]
In case somebody is looking for an answer now: you can set `let g:NERDTreeWinPos = "left"` in `.vimrc`

**Comment by lifecrisis** [comment]
@TwelveNights, that doesn't answer the original question. The setting you mention only controls *where* the NERDTree window opens, not *when* it opens.

**Comment by TwelveNights** [comment]
@lifecrisis 

Ahhh, I see. I'm surprised they asked about that then, since the README contains those instructions already lol

**Comment by Statham-stone** [comment]
> In case somebody is looking for an answer now: you can set `let g:NERDTreeWinPos = "left"` in `.vimrc`

And you better add that line at the **end** of your .vimrc file.
