### ISSUE TITLE
Cannot edit a file in another directory that contains spaces

### ISSUE THREAD

**Issue by radostyle** [scrooloose/nerdtree#20]
if you are in directory /home/me   and use NERDTree on a directory with spaces "/tmp/a directory with spaces/" then when pressing enter on a file in that directory, you cannot edit the file.  If you are already in the directory with spaces then it works fine.

**Comment by PhilRunninger** [comment]
I tested this on all "vim" executables I have access to:

* Mac OSX, Neovim 0.1.1
* Mac OSX, Vim 7.3
* Windows, gVim 7.4
* Windows console, Vim 7.4
* Windows (Git bash console), Vim 7.4

None of them could reproduce this error. If this is still happening, please let us know, but it looks like it's been fixed sometime in the last 6 years.
