### ISSUE TITLE
File coloring based on type.

### ISSUE THREAD

**Issue by ghost** [scrooloose/nerdtree#201]
Is it possible to change the color of files based on their extension?

**Comment by atoder** [comment]
I am using Iterm2 + Solarized Dark theme. Can't get highlighting based on file type to work. I tried all variations including 
`autocmd VimEnter * call NERDTreeHighlightFile('jade', 'green', 'none', 'green', '#151515')`



Tried the one in vim-devicons FAQ as well
```

" NERDTress File highlighting
function! NERDTreeHighlightFile(extension, fg, bg, guifg, guibg)
exec 'autocmd FileType nerdtree highlight ' . a:extension .' ctermbg='. a:bg .' ctermfg='. a:fg .' guibg='. a:guibg .' guifg='. a:guifg
exec 'autocmd FileType nerdtree syn match ' . a:extension .' #^\s\+.*'. a:extension .'$#'
endfunction

call NERDTreeHighlightFile('jade', 'green', 'none', 'green', '#151515')
call NERDTreeHighlightFile('ini', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('md', 'blue', 'none', '#3366FF', '#151515')
call NERDTreeHighlightFile('yml', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('config', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('conf', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('json', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('html', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('styl', 'cyan', 'none', 'cyan', '#151515')
call NERDTreeHighlightFile('css', 'cyan', 'none', 'cyan', '#151515')
call NERDTreeHighlightFile('coffee', 'Red', 'none', 'red', '#151515')
call NERDTreeHighlightFile('js', 'Red', 'none', '#ffa500', '#151515')
call NERDTreeHighlightFile('php', 'Magenta', 'none', '#ff00ff', '#151515')
call NERDTreeHighlightFile('ds_store', 'Gray', 'none', '#686868', '#151515')
call NERDTreeHighlightFile('gitconfig', 'Gray', 'none', '#686868', '#151515')
call NERDTreeHighlightFile('gitignore', 'Gray', 'none', '#686868', '#151515')
call NERDTreeHighlightFile('bashrc', 'Gray', 'none', '#686868', '#151515')
call NERDTreeHighlightFile('bashprofile', 'Gray', 'none', '#686868', '#151515')
```

**Comment by Leandros** [comment]
@atoder Look at [`solarized.vim`](https://github.com/altercation/vim-colors-solarized/blob/master/colors/solarized.vim), and figure out what colour in what mode you want.

If you want a funny potpourri of colors, this somewhat resembles the colors github uses for it's languages.

```
" source files
call NERDTreeHighlightFile('.c', '11', 'NONE', 'NONE', 'NONE')
call NERDTreeHighlightFile('h', '3', 'NONE', 'NONE', 'NONE')
call NERDTreeHighlightFile('cc', '5', 'NONE', 'NONE', 'NONE')
call NERDTreeHighlightFile('mm', '4', 'NONE', 'NONE', 'NONE')
" shell scripts
call NERDTreeHighlightFile('sh', '2', 'NONE', 'NONE', 'NONE')
call NERDTreeHighlightFile('bash', '2', 'NONE', 'NONE', 'NONE')
call NERDTreeHighlightFile('zsh', '2', 'NONE', 'NONE', 'NONE')
" makefiles
call NERDTreeHighlightFile('mk', '13', 'NONE', 'NONE', 'NONE')
call NERDTreeHighlightFile('makefile', '13', 'NONE', 'NONE', 'NONE')
call NERDTreeHighlightFile('Makefile', '13', 'NONE', 'NONE', 'NONE')
```

Obviously only has support for languages / files I regularly use, extend as you wish.

**Comment by tiagofumo** [comment]
For anyone looking for this, I created this: https://github.com/tiagofumo/vim-nerdtree-syntax-highlight

Take a look at the screenshots and see if you like it. You can use it with [vim-devicons](https://github.com/ryanoasis/vim-devicons) or not. If you don't want to use it with [vim-devicons](https://github.com/ryanoasis/vim-devicons), add the following line to your .vimrc:

`let g:NERDTreeFileExtensionHighlightFullName = 1`

**Comment by EdvinOlofsson** [comment]
@tiagofumo wow, that looks amazing! Thanks for sharing :)

**Comment by PhilRunninger** [comment]
What does everyone here think? With @tiagofumo's NERDTree [plugin](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight), can we consider this issue closed?

**Comment by cmcginty** [comment]
I just tested it out and it makes the cursor navigation really slow when you have a medium amount of dirs! 🤕

**Comment by atoder** [comment]
Yes I just tested it and I agree with @cmcginty it makes my cursor navigation slower. I am testing it using a production project that has quite a few directories.

**Comment by ryanoasis** [comment]
FYI, related solutions: https://github.com/ryanoasis/vim-devicons/issues/158

**Comment by cmcginty** [comment]
Here a basic syntax file I got working for nerdtree colors. Make sure you put in `after/syntax/` dir. https://github.com/cmcginty/dotfiles/blob/master/vim/vim/after/syntax/nerdtree.vim

**Comment by atoder** [comment]
"Plugin 'tiagofumo/vim-nerdtree-syntax-highlight' SUPER SLOWS down NERD tree. Do not use!

**Comment by tiagofumo** [comment]
@atoder,
you can configure to use the plugin only for the extensions/rules that you need, and that can make scrolling a little bit faster. In the [README](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight) file, it is stated:

> **Warning:** This is sort of a hack and has some limitations.

I would love to merge a pull request with a fix for this performance issue. Feel free to contribute.

**Comment by PhilRunninger** [comment]
I am going to close this issue. @tiagofumo's plugin is a good start. Good luck to those who choose to tackle improving its performance.

**Comment by hozza** [comment]
> It would be rather easy to strip the color from the `dircolors` file since relevant lines would like like `.mp3 00;36`. The problem then becomes finding a good translation between ANSI and vim color. I do know that some scripts for this have already been made.

Any update on this part? I'd love to integrate `LS_COLORS` or `~/.dircolors` seamlessly into NERDTree.

**Comment by PhilRunninger** [comment]
I've not heard of anyone tackling the `.dircolors` integration. As NERDTree is already quite bloated, this would be a perfect candidate to be written as a separate plugin, like @tiagofumo has done.
