### ISSUE TITLE
No way to move "up" from starting directory

### ISSUE THREAD

**Issue by fncll** [scrooloose/nerdtree#205]
I don't have the `..` in the NERDTree listing. At one time I'm pretty sure I did! So I don't have any way to move up from the directory that NERDTree starts in.

I thought `p` would move "up" to the parent directory if the top node was selected, but that doesn't seem to be the case.

I am running:

```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Sep  1 2012 18:08:47)
MacOS X (unix) version
Included patches: 1-646
```

I'm running NERDTree pulled from this repo a few days ago...

**Comment by gaodacheng** [comment]
@fncll thank you.

found this helpful.

u did the trick when I want to go back to parent directory of the current file/directory, because `..` has been hidden.

**Comment by lifecrisis** [comment]
@fncll and @gaodacheng,

Looks like you guys might have the `g:NERDTreeMinimalUI` setting flipped on.

Try running `:let g:NERDTreeMinimalUI = 0` and refreshing the NERDTree to see if the desired line comes back.  See the documentation for more information.

**Comment by gaodacheng** [comment]
@lifecrisis 

> Looks like you guys might have the g:NERDTreeMinimalUI setting flipped on.

yes, you are right. I have set that option on not a long time ago.

I love the `NERDTreeMinimalUI` .

Now `u` works for me.

Thank you a lot for your time and point out my problem here.

Have a nice day, man.
