### ISSUE TITLE
execute shell command on file

### ISSUE THREAD

**Issue by piotryordanov** [scrooloose/nerdtree#206]
Is it possible to call an external shell command (like say touch) on a file from NERDTree?

I want to invoke `stylus` on a css file directly from the Tree.

If not, can i open the file's working directly in a shell (maybe in tmux?)

Cheers!

**Comment by devth** [comment]
:+1: great idea!

**Comment by aemonge** [comment]
+1

**Comment by kontact-chan** [comment]
+1

**Comment by ChappIO** [comment]
+1 is this possible yet?

**Comment by PhilRunninger** [comment]
This is the sort of thing the NERDTree API was written to handle. Take a look at the documentation (especially `:h NERDTreeAPI`) and the way the commands have been used in `nerdtree/nerdtree_plugin/fs_menu.vim`. That will get you started. Here is something I quickly put together which you can put in your vimrc file. It asks for the OS command (and leading arguments) to execute. Then it asks for any trailing arguments before running the command and echoing the output.
```
call NERDTreeAddMenuItem({'text': '(e)xecute OS command on a childnode', 'shortcut': 'e', 'callback': 'NERDTreeOSCommand'})

function! NERDTreeOSCommand()
    let command = input('Command: ') . ' ' . g:NERDTreeFileNode.GetSelected().path.str()
    let command = command . ' ' . input('Command: ' . command . ' ')
    echo "\n" . system(command)
endfunction
```
