### ISSUE TITLE
Issue with gi: preview split and gs: preview vsplit on MacOS X

### ISSUE THREAD

**Issue by KevinSjoberg** [scrooloose/nerdtree#210]
I'm running Vim 7.3 on MacOS X.

```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Sep 24 2012 09:34:56)
MacOS X (unix) version
Included patches: 1-646
```

I've noticed that the commands `gi` and `gs` don't work as expected when NERDTree is opened with `e.`. The cursor will not stay in the NERDTree window but instead move to the newly opened split.

The only difference I've found is that `:e.`, set `b:NERDTreeType` to **secondary**, whereas `:NERDTreeToggle` set it to **primary**.

If I change `b:NERDTreeType` to **primary** everything works normal.

**Comment by PhilRunninger** [comment]
This has been fixed some time within the last 5 years. Closing.
