### ISSUE TITLE
Interface for choosing what active window to open Nerdtree's selected file in

### ISSUE THREAD

**Issue by fholgado** [scrooloose/nerdtree#211]
Not an issue, but an idea:

Select a file in Nerdtree, type `oi`, which stands for "open in..."

Nerdtree gives you a list of your visible windows, each with a number attached to them, something like this:

```
------------------------------
|        1      |             |
|_ _ _ _ _ _ _  |      3      |
|        2      |             |
|               |             |
------------------------------
```

Type the number of the window you want the file open in, and Nerdtree opens it in that pane.

GLORIOUS! (I can come up with more detailed wireframes if needed, but this should give you a good idea of what I'm after)

PS. Thanks for your hard work. Nerdtree is indispensable in my every day life. You rock!

EDIT: I forgot that TMUX has an interface for identifying your active splits, by doing Meta + a + q, here is a screenshot:

![Tmux example](http://f.cl.ly/items/251o3F3B462H473d2d29/Screen%20Shot%202012-11-29%20at%2011.50.28%20AM.png)

**Comment by axelson** [comment]
+1

Is there a work-around to decide what window to open in? I typically have 3 vertical splits and up to 3 more horizontal splits (6 windows in total) and I'd love to be able to easily choose which window to open a file or split in.

**Comment by PhilRunninger** [comment]
Interesting idea. I don't know how feasible it would be to recreate the window layout as suggested. One could use this function call
```
let targetWindow = inputlist(insert(map(range(1,winnr('$')), 'v:val . ": " . bufname(winbufnr(v:val))'), 'Select window to split:'))
```
to display the window numbers and the buffers they contain, as well as to ask the user which window to split. This is as far as I'm willing to take this, but someone else can run with it, and make a NERDTree plugin that does this custom split-open capability.
