### ISSUE TITLE
Error on opening vim

### ISSUE THREAD

**Issue by sddhrthrt** [scrooloose/nerdtree#216]
Error detected while processing function <SNR>32_VimEnterHandler..<SNR>32_NERDTreeOpenAllTabs..<SNR>32_NERDTreeMirrorOrCreate..<SNR>29_initNerdTreeMirror..<SNR>29_
echo..Pl#Statusline:
line   18:
E684: list index out of range: 0 
Press ENTER or type command to continue
Error detected while processing function <SNR>32_VimEnterHandler..<SNR>32_NERDTreeOpenAllTabs..<SNR>32_NERDTreeMirrorOrCreate..<SNR>29_initNerdTreeMirror..<SNR>29_
echo..Pl#Statusline:
line   18:
0
NERDTree: No trees to mirror

**Comment by PhilRunninger** [comment]
Not enough information. Too long ago. Closing.
