### ISSUE TITLE
NERDTree can't open files whose name ends with "*"

### ISSUE THREAD

**Issue by denilsonsa** [scrooloose/nerdtree#217]
How to reproduce:
1. `touch 'fails*' 'works*fine'` (Yeah, I know this is a weird filename.)
2. Open Vim or Gvim. Open NERDTree.
3. The `works*fine` file opens correctly, as expected.
4. The `fails*` file silently fails to open. It is also shown in a different color because NERDTree understands `*` as a suffix for executable files.

Known workaround:
- `chmod +x 'fails*'`

**Comment by PhilRunninger** [comment]
Confirmed.

**Comment by PhilRunninger** [comment]
@denilsonsa , would you be willing to test the pull request #868 I've put together for this issue? Details are in the PR. Thanks.

**Comment by PhilRunninger** [comment]
Fixed in #868.
