### ISSUE TITLE
nerdtree encoding problem in ubuntu 

### ISSUE THREAD

**Issue by dfang** [scrooloose/nerdtree#221]
http://stackoverflow.com/questions/9927217/vim-nerdtree-suddenly-broke

LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8

i've put  these line  in zshrc, still doesn't work .

please help !

screenshot:
http://imgur.com/6y1hq

**Comment by PhilRunninger** [comment]
This issue has been idle for about 5 years, so I'm closing it. Feel free to reopen if necessary.
