### ISSUE TITLE
Exception thrown when opening nerdtree

### ISSUE THREAD

**Issue by wedgwood** [scrooloose/nerdtree#225]
After updated to the latest version, my nerdtree seems not working correctly.
When I open the nerdtree, it throw exception about 

> error when function nerdtree#toggle..nerdtree#initNerdTree
> line 27
> lack of :endif
> error when function nerdtree#toggle
> line 12
> lack of  :endif

By the way, the test is on the win7 platform

**Comment by PhilRunninger** [comment]
This issue has been idle for about 5 years, so I'm closing it. Feel free to reopen if necessary.
