### ISSUE TITLE
NERD Tree root line loses syntax colour when truncated (patch)

### ISSUE THREAD

**Issue by keffinbarnaby** [scrooloose/nerdtree#23]
NERDTree version 4.1.0 loses the syntax colour for the line displaying the tree root directory if it is truncated, because the first character on the line becomes < rather than /. The following simple patch solves the problem:

3391a3392
&gt;     syn match treeCWD #^<.*$#   " Match CWD line even when truncated

**Comment by PhilRunninger** [comment]
This has been fixed.
