### ISSUE TITLE
cannot resolve symbolic link using NERDTreeFind

### ISSUE THREAD

**Issue by HongxuChen** [scrooloose/nerdtree#232]
Firstly I would say that actually I am using [The-NERD-Tree from vim-scripts](https://github.com/vim-scripts/The-NERD-tree), whose src is similar to your [refactor-open branch](https://github.com/scrooloose/nerdtree/tree/refactor-open). The details can be seen at [this thread](http://stackoverflow.com/questions/14514963/can-nerdtree-handle-symbolic-link-when-sync-path/14517365#comment20242810_14517365) of stackoverflow and [Ingo Karkat](http://stackoverflow.com/users/813602/ingo-karkat) gives a solution by adding `resolve` at [Line 2558](https://github.com/vim-scripts/The-NERD-tree/blob/master/plugin/NERD_tree.vim#L2558) of `The-NERD-tree/plugin/NERD_tree.vim`.

**Comment by PhilRunninger** [comment]
@HongxuChen , I've been going through the backlog of issues. Can you provide more information about this, or close the issue?

**Comment by HongxuChen** [comment]
@PhilRunninger Sorry not using nerdtree now, I will close it.
