### ISSUE TITLE
Is it possible to move to current root directory after 'C' key?

### ISSUE THREAD

**Issue by breadmj** [scrooloose/nerdtree#235]
'C' key is for 'Change the tree root to the selected dir'.

After I pressed 'C' key,

'Change the tree root to the selected dir' works very well.

But :pwd command does not return the tree root.

In other words, :pwd remains same if I moved the tree root.

I use Command-T plugins with NERDTree

so \t opens the previous tree root directory.

I have to manually press 'cd' to change :pwd to the tree root.

I feel this very uncomfortable.

Is there any way to change :pwd automatically after 'C' key?

**Comment by PhilRunninger** [comment]
This issue has been idle for about 5 years, so I'm closing it. Feel free to reopen if necessary.
