### ISSUE TITLE
Question: Ability to always use existing window/buffer/tab when possible.

### ISSUE THREAD

**Issue by jordwalke** [scrooloose/nerdtree#237]
Hello,

I've found the plugin Ctrl-p to pair very nicely with NERDTree. One thing that Ctrl-p does well, is that it has a mode where all open commands will find the existing file/buffer/tab whenever possible. This means that if you do a vertical split "s", it will only perform the vertical split if that file is not already present somewhere else. If it is present somewhere else, it instead will jump to that file. In other words, the type of open command "s/t" is just a fallback in case the file cannot be found globally. Is it possible to configure NERDTree to do the same?

**Comment by PhilRunninger** [comment]
Closing for reasons cited in #791.
