### ISSUE TITLE
Load session from bookmarks

### ISSUE THREAD

**Issue by mpfusion** [scrooloose/nerdtree#241]
If a session file `Session.vim` is saved in the the bookmarks (`NERDTreeBookmarks`) hitting enter on the session file opens it. Is it possible to _source_ session files instead of opening them?

If one really wants to open the session file instead of sourcing it, one can always use `o`, so no functionality would be lost. Or alternatively a source mapping (e.g. `S`) could be created. This would have the advantage that NERDTree does not need to detect which files actually are session files (other than the obvious `Session.vim`).

**Comment by PhilRunninger** [comment]
This can be accomplished using the NERDTree Plugin API. See `:h NERDTreeAPI` and examples in https://github.com/scrooloose/nerdtree/tree/master/nerdtree_plugin.
