### ISSUE TITLE
Error on trying to open non existing bookmarks 

### ISSUE THREAD

**Issue by altunyurt** [scrooloose/nerdtree#264]
If bookmark's name is written wrong, or a nonexisting bookmark is tried to be opened 
by command 

```
NERDTree  nosuchbookmark
```

NERDTREE outputs following error messages, and after several  enters, ctrl-cs it becomes usable again. I'm using the latest source from github.

E116: Invalid arguments for function len(files) > g:NERDTreeNotificationThreshold
E15: Invalid expression: !a:silent && len(files) > g:NERDTreeNotificationThreshold
Error detected while processing function 169..170..nerdtree#renderView:
line   31:
E117: Unknown function: str
E15: Invalid expression: b:NERDTreeRoot.path.str({'format': 'UI', 'truncateTo': winwidth(0)})
line   32:
E121: Undefined variable: header
E116: Invalid arguments for function setline
Error detected while processing function 169..170..nerdtree#renderView..122..123:
line   60:
E121: Undefined variable: isDirectory
E15: Invalid expression: self.path.isDirectory ==# 1 && self.isOpen ==# 1
Error detected while processing function 169..170..119..107..112..103:
line    1:
E117: Unknown function: str
E15: Invalid expression: self.path.str() ==# a:treenode.path.str()
Error detected while processing function 169..170..119..107:
line    9:
E117: Unknown function: str
E116: Invalid arguments for function substitute(b:NERDTreeRoot.path.str({'format': 'UI'}), '/ *$', '', '')]
E15: Invalid expression: [substitute(b:NERDTreeRoot.path.str({'format': 'UI'}), '/ *$', '', '')]
line   13:
E117: Unknown function: str
E15: Invalid expression: self.path.str({'format': 'UI'})

**Comment by PhilRunninger** [comment]
Fixed.
