### ISSUE TITLE
Ability to theme NERDTree's background color

### ISSUE THREAD

**Issue by jordwalke** [scrooloose/nerdtree#267]
I'd like to be able to control the background color of NERDTree - not just the background color of text, but the entire lines. Currently it seems to always match Normal.

**Comment by jordwalke** [comment]
Does anyone know of any hacks that would make this work?

**Comment by jordwalke** [comment]
This could get you close:
http://stackoverflow.com/questions/8415828/vim-dim-inactive-split-panes

But it only changes the color of the NERDTree file/directory lines, and not the empty space below it (because the empty space presumably has `~` characters - if you could pad those lines with empty space it would work).

**Comment by PhilRunninger** [comment]
You're asking to highlight negative space. Chances are this will severely impact scrolling, which can already happen in large directories. We will not be implementing this.
