### ISSUE TITLE
Open directory bookmarks in current tree

### ISSUE THREAD

**Issue by tommcdo** [scrooloose/nerdtree#271]
When making a bookmark to a directory, it would be nice if opening that bookmark would leave the tree at its present root, and simply open the nodes along the path to that directory. Presently, it changes the tree's root to the directory that defines the bookmark.

This is not necessarily a bug; just doesn't work with my workflow. A new key binding to open the directory in the existing tree would be perfect.

**Comment by PhilRunninger** [comment]
I could see this being done with the `NERDTreeFind` command, passing the bookmark's path in as the argument. It's also a good candidate to be done as a NERDTree plugin.
