### ISSUE TITLE
Add NERDTree support for remote directories.

### ISSUE THREAD

**Issue by esiegel** [scrooloose/nerdtree#275]
It would be nice to be able to browse remote directories using NERDTree.

Something like this:

```
:NERDTree scp://user@host//a/b/c/
```

**Comment by eirikgje** [comment]
+1

**Comment by tiev** [comment]
+1

**Comment by whoOami** [comment]
+1

**Comment by rakshazi** [comment]
+1
@scrooloose any news?

**Comment by Melkor333** [comment]
+1

**Comment by JackofSpades707** [comment]
+1

**Comment by esiegel** [comment]
I'm going to close this issue.  It can be reopened if someone decides to take it on.  @scrooloose has already stated that this isn't something he is considering, and I'd rather close it than let it linger indefinitely.

**Comment by sangeet** [comment]
I know this has been closed forever ago, but lack of this one feature is why I'm currently hunting around every forum and trying to unlearn years of nerdtree and having to learn netrw (which btw is a complete mess in comparison).

As remote work becomes more prevalent, this is a definitely a feature where nerdtree will continue to lag behind. Life would have been so much easier if nerdtree supported this like netrw already does.

It's 2020 and browsing remote directories is a feature that a file browser should support. Please re-consider your stance on this and if possible, please introduce a way to browse files in nerdtree via scp.

**Comment by zwarag** [comment]
There is always SSHFS and FTPFS which allows you to mount a remote folder directly into your system and see it as a normal folder.

sshfs: `sudo sshfs -o allow_other,default_permissions root@xxx.xxx.xxx.xxx:/ /mnt/workdir` 
then `cd /mnt/workdir && vim`

**Comment by sangeet** [comment]
I did try `sshfs` and unfortunately `sshfs` is extremely slow when dealing with larger directories on a server that's 250ms away (India <-> USA). Maybe it is a viable option for connections that aren't too far away, but over long distances `sshfs` is a no go. I did not try `ftpfs` yet, so thanks for mentioning that.

Either way, I played around with `netrw` quite a lot and ended up in a loop of a few issues and hence eventually switched to VSCode which has native integration for editing files remotely on a server far away and is fairly quick.

If working remotely over longer distances then VSCode might be the ideal solution since `sshfs` isn't a viable option over high latency connections.

**Comment by dennisjbell** [comment]
I too am considering moving to VSCode for this one feature, but am loathed to do so.  The fact that you can just use :edit to open remote directories for exploration should make it quite possible to add this feature.

**Comment by amit777** [comment]
> I did try `sshfs` and unfortunately `sshfs` is extremely slow when dealing with larger directories (with lots of files) on a server that's 250ms away (India <-> USA). Maybe it is a viable option for connections that are less than 50-80 ms, but over long distances `sshfs` is a no go. I did not try `ftpfs` yet, so thanks for mentioning that but I believe it would be similarly slow over longer distances accordingly.
> 
> 
> 
> Either way, I played around with `netrw` quite a lot and ended up in a loop of a few issues and hence eventually switched to VSCode which has native integration for editing files remotely on a server far away and is fairly quick. Sure it was a bit of learning, but the vim plugins on VSCode have gotten really good lately ( Shout out to VSCodeVim : https://github.com/VSCodeVim/Vim ). It's not ideal, but it's the most robust solution out there.
> 
> 
> 
> If working remotely over longer distances then VSCode remote might be the ideal solution since `sshfs` isn't a viable option over high latency connections.

I found this issue the same way you did. I was wondering if you tried some techniques to optimize the sshfs connection. I found this example connection string online:

sshfs -o Ciphers=arcfour,compression=no,nonempty,auto_cache,reconnect,workaround=all user@development.net:/usr/local/gitdev/ ~/dev/code
