### ISSUE TITLE
NERDTreeSortOrder doesn't seem to be respected after the first element in the list.

### ISSUE THREAD

**Issue by tankorsmash** [scrooloose/nerdtree#277]
If I alter the sort order to something like `['\.cpp$', '\/$']` to have the `cpp` files listed before the directories, only the `cpp` files are listed first, and then the other files, along with the directories, are listed in alphabetical order. 

http://i.imgur.com/kJ0fLX3.png

At first I thought it was a typo or something similar, but if I re-order the list, so that the directories are first, and the `cpp` files are second, the directories are correctly placed first, but the `cpp` files are mixed in with the rest of the files in the directory.

http://i.imgur.com/tuQiUHY.png

**Comment by PhilRunninger** [comment]
Confirmed.

**Comment by PhilRunninger** [comment]
This should be fixed with #856. @tankorsmash , take another look at this, and reopen this issue if necessary.

**Comment by tankorsmash** [comment]
Thanks @PhilRunninger!
