### ISSUE TITLE
Hide status (Power) line

### ISSUE THREAD

**Issue by nomasprime** [scrooloose/nerdtree#280]
Does anyone know how I can hide the status line, hence Powerline, for NERDTree buffers?

**Comment by habitullence** [comment]
I just came back to the same question and found I'd asked it almost three years ago :laughing:

**Comment by lifecrisis** [comment]
Hey, @nomasprime, sorry for the lag!

There is no way to disable the status line feature for only one window. Unfortunately, the `'laststatus'` setting is global. You can, however, customize the NERDTree status line.

Please read `:h 'NERDTreeStatusline'` for additional information.

As an afterthought, try the following setting in your `vimrc` and see if it helps:
```viml
let g:NERDTreeStatusline = '%#NonText#'
```
... that may be what you actually want.
