### ISSUE TITLE
Feature request: ability to disable checking for bookmarks

### ISSUE THREAD

**Issue by JonathanReeve** [scrooloose/nerdtree#282]
I use sshfs sometimes to edit files remotely, and so many of my bookmarks refer to these files, which are mounted locally and then unmounted when I'm not using sshfs. Thus, unless I have my remote server mounted, NERDTree complains that I have invalid bookmarks. 

It's not that big of a deal, but it'd be nice to be able to disable bookmark checks, so that I don't keep getting this error message on startup.

**Comment by PhilRunninger** [comment]
Per #168, the warning has been diabled; therefore, I'm closing this issue.
