### ISSUE TITLE
Closing nerdtree

### ISSUE THREAD

**Issue by cskeeters** [scrooloose/nerdtree#284]
If I run `:NERDTreeToggle`, then `:bdelete`, then `:NERDTreeToggle` again, I get a vertical split with `~/NERT_tree_1` at the bottom, but there is no text in the buffer.  Is there a way to reset nerdtree without closing vim?

**Comment by lifecrisis** [comment]
This issue appears to have been fixed by a subsequent pull request. However, there is still a problem with running `:bwipeout` on the NERDTree buffer. Thus, this issue will remain open. In addition, the code for dealing with `:bdelete` could use a refactor.

**Comment by PhilRunninger** [comment]
@lifecrisis I think I fixed the `:bwipeout` issue. Can you double-check it, and close this issue if appropriate?

**Comment by lifecrisis** [comment]
I can't replicate the issue I saw before.  Closing now.

**Comment by PhilRunninger** [comment]
The PR that fixed the `:bwipeout` bug is #814.
