### ISSUE TITLE
Add NERDTreeFocus to documentation

### ISSUE THREAD

**Issue by fdinoff** [scrooloose/nerdtree#286]
Can you add NERDTreeFocus to the documentation?

**Comment by moll** [comment]
Stumbled upon the same issue that calling `:NERDTree` itself would reset the tree and was looking for an alternative that would not reset it if it already exists, i.e `NERDTreeFocus`.

**Comment by lifecrisis** [comment]
This issue was fixed by 5f3a44d066a1ab356cc12476ac9f4d271d72645a.
