### ISSUE TITLE
Initial directory listing buffer is not re-used on toggle

### ISSUE THREAD

**Issue by shkm** [scrooloose/nerdtree#289]
When opening a directory in vim, NERDTree pops up with a directory listing. Toggling the NERDTree opens a sidebar with a directory listing in a new buffer.

As a result, any changes made in the initial buffer do not carry over to the sidebar (e.g. expanding/contracting nodes). I use the initial buffer to open the first file I'll be working on (often in a sub-directory), so I find this very tedious.

Ordinarily, using :NERDTreeToggle ensures that NERDTree uses only a single buffer for the sidebar, but there doesn't seem to be any option to use the same buffer as the initial directory listing. This isn't the behaviour I would expect, so is it a bug or a quirk resulting from something I haven't foreseen?

Illustrated:

![r97bz](https://f.cloud.github.com/assets/22677/1037482/88d66de4-0f50-11e3-94eb-b07a2070f166.png)

Initially posted at [StackOverflow](http://stackoverflow.com/questions/18472689/how-can-i-use-the-same-nerdtree-buffer-for-directory-listings-and-the-sidebar).

**Comment by PhilRunninger** [comment]
See this question in the FAQ: https://github.com/scrooloose/nerdtree/wiki/F.A.Q.#how-can-i-open-nerdtree-automatically-when-vim-starts-up-on-opening-a-directory. It will open the toggle-able NERDTree when you start vim with a directory - `vim .`. It won't help when vim is already started and you issue the command `:e <path>`, but you could use `:NERDTreeToggle` or `:NERDTree <path>` instead.
