### ISSUE TITLE
NERDTree should follow vim directory

### ISSUE THREAD

**Issue by bitboxer** [scrooloose/nerdtree#29]
I have searched the docu and googled a bit, but i couldn't find a way that reloads the nerd tree every time I use :cd and switch a directory. The NERDTree dir should reload after I changed the directory for vim. Is this possible somehow?

**Comment by PhilRunninger** [comment]
You can use the shortcut ZyX gave in [Stackoverflow](http://stackoverflow.com/questions/15308311/whats-the-variable-for-current-working-directory-in-vim).

```
nnoremap \f :NERDTree .<CR>
```

I don't see any autocmd in the list that would respond to a changing directory, but the quick `\f` keypress will give you the tree you want.
