### ISSUE TITLE
opens only empty files on windows network share

### ISSUE THREAD

**Issue by 2vek** [scrooloose/nerdtree#290]
I have shared a folder using samba on ubuntu box. I am trying to edit some files from that folder in windows 7.

So, I opened that folder in vim using `:NERDTree \\linuxbox\share\mydir`, folder opened in nerdtree as expected, I then browsed to `myfile.js`, and pressed `o`, a empty file is opened. 
But, that file is not empty, I verified it by opening that file in notepad.
This behaviour is also same for other file in all other shared folders.

However, vim opens that file correctly by using `:e \\linuxbox\share\mydir\myfile.js`

**Comment by PhilRunninger** [comment]
Closing this because of its age. A lot of changes have been made in the last 5 years. Create another issue if the problem persists.
