### ISSUE TITLE
Shouldn't hidden files be shown by default?

### ISSUE THREAD

**Issue by kevinSuttle** [scrooloose/nerdtree#291]
I'd venture to say that if you're using a Vim plugin, you're going to want hidden files shown by default, especially considering you need to edit your .vimrc and use git. 

It could optionally be set in your .vimrc to show or hide hidden files by default. Maybe there's a way to do this already?

**Comment by jones77** [comment]
One argument is that it follows `ls`'s semantics (but then why `I` as the shortcut?).

**Comment by lifecrisis** [comment]
It looks like this issue has been resolved. Generally, most people *don't* want to see the hidden files by default, but I'm glad you found the setting to use in these cases.
