### ISSUE TITLE
How to open a file by command?

### ISSUE THREAD

**Issue by billychan** [scrooloose/nerdtree#297]
I always have a NERDtree window open at left. I'm so lazy that I don't even want to jump to left window to browse file up and down :)

So I created a key mapping

```
:nnoremap nj <C-W><C-H>jo
```

Basically it is expected to jump to left window, down to next file and open it for me.

However VIM gave me an error saying something like "E21: can't modify", I guess that's because `o` had not been converted to NERDtree command yet.

I searched around and can't find such a direct command to use as `o` in NERDtree window so that I can call it like

```
<C-W><C-H>j:PleaseOpenThatFileForMe
```

Anybody has a hint?

Thanks!

**Comment by PhilRunninger** [comment]
`:nnoremap` uses the original definition of keystrokes. `o` has been remapped in the NERDTree buffer, so you need to use `:nmap` instead. I'm going to go ahead and close this because this is a very old issue, and you've probably moved on from this. You can reopen it if necessary.
