### ISSUE TITLE
NerdTree to show open buffers

### ISSUE THREAD

**Issue by justrajdeep** [scrooloose/nerdtree#300]
This is more like a request than an issue :)

Can Nerdtree show the list of open buffers say something like :NerdtreeBuffers

I know there is BufferExplorer but i dont like it for the simple fact that i have to predefine if i want the buffer in a tab/split/vsplit

Nerdtree is awesome ... i just need one command and then from the list i can open it however i want.

**Comment by PhilRunninger** [comment]
This is a neat idea, but I don't think it's a good fit for NERDTree.

**Comment by zwhitchcox** [comment]
This would be great

**Comment by PhilRunninger** [comment]
Check out this NERDTree plugin: https://github.com/PhilRunninger/nerdtree-highlight-open-buffers. It highlights any visible node that is open in Vim. It uses ctermfg=118, which on my setup is bright green.

**Comment by af** [comment]
For anyone looking for the plugin @PhilRunninger mentioned above, looks like it moved to https://github.com/PhilRunninger/nerdtree-buffer-ops
