### ISSUE TITLE
NERD-TREE plugin issue in vim improved -7.3

### ISSUE THREAD

**Issue by dllfpga** [scrooloose/nerdtree#302]
Hi

I installed latest Nerdtree dev version from https://github.com/scrooloose/nerdtree.git.My vim version is 7.3.But the Nerdtree commands are not working except 'u' command.Even, enter key to traverese in, is not working .I did a trial and error and gf works sometimes and not always!!.Sometimes,I get path not found error.Is this a Nerdtree issue or vimrc issue or vim issue? Please let me know the best way to fix this issue.

Thanks-

**Comment by PhilRunninger** [comment]
This issue has been idle for a while, so I'm closing it. Feel free to reopen if necessary.
