### ISSUE TITLE
Pulse check

### ISSUE THREAD

**Issue by tony** [scrooloose/nerdtree#305]
@scrooloose 

Greetings, it's been a few months and a lot of PR's and issues have built up, where do things stand with your time to maintain this?

Would it be helpful if some people were found to help maintain this? It's a pretty important plugin!

**Comment by lifecrisis** [comment]
Hey, @tony and @ain. I was recently added as a collaborator to this project. It is true that a lot of issues and pull requests have built up over time. It's a good thing that source code doesn't rust!

I've fixed a few bugs, added a feature, and begun a small project to refactor one of the more critical scripts in the codebase. I'm sure @scrooloose is a busy guy, and I'll try to be in touch with him about getting the issue count down slowly over the next few months (once I decide how much time I'm willing give to this project).

@PhilRunninger and myself have closed a couple dozen issues in the last few weeks. Hopefully, more will follow! I wouldn't expect too much, but we shall see how things go.
