### ISSUE TITLE
Can't modify files starting with one or more dashes

### ISSUE THREAD

**Issue by caseyhoward** [scrooloose/nerdtree#310]
If you press "m" on a file named "--" and then choose an option, NERDTree acts as if you have selected the root node. I had a file named "--" that I created on accident and wanted to delete it. I ended up deleting an entire project because of this bug and losing all my git stashes.

Also, if you try pressing "m" on a file that starts with a single dash, it says "NERDTree: Put the cursor on a node first".

**Comment by shennyg** [comment]
:+1: I get the following message: `NERDTree: select a node first`.

**Comment by PhilRunninger** [comment]
This seems to have been fixed. It was unstated in the description, but I assume this is a Windows issue. I couldn't even create a file with that name in *nix/MacOS. I'm closing this issue. Reopen it if necessary.

**Comment by caseyhoward** [comment]
Just tried to reproduce and it does appear fixed. However, it wasn't a Windows issue. I was definitely using OS X or Linux. You can create the file using nerdtree with by pressing m, a, --, <ENTER>. Or you can create it by running `touch -- --`.
