### ISSUE TITLE
Error detected while processing BufLeave Auto commands

### ISSUE THREAD

**Issue by ain** [scrooloose/nerdtree#312]
Switching to NERDTree fails. Used to search on a cursor with `*` and then followed next matches by `n`. After that, switching between the editor window and NERDTree broke.

Traceback:

> Error detected while processing BufLeave Auto commands for "<buffer=3>":
> Traceback (most recent call last):
>  File "<string>", line 1, in <module>
>  File "<string>", line 205, in tern_sendBufferIfDirty
>  File "<string>", line 193, in tern_sendBuffer
>  File "<string>", line 71, in tern_findServer
>  File "<string>", line 84, in tern_startServer
>  File "/usr/lib/python2.7/subprocess.py", line 711, in **init**
>    errread, errwrite)
>  File "/usr/lib/python2.7/subprocess.py", line 1308, in _execute_child
>    raise child_exception
> OSError: [Errno 2] No such file or directory

**Comment by hz-stevec** [comment]
+me too

**Comment by PhilRunninger** [comment]
I'm closing this issue for lack of information. The stack trace doesn't include any NERDTree code. Open a new issue with more details if needed.
