### ISSUE TITLE
nerdtree does not support file or directory has comma in it.

### ISSUE THREAD

**Issue by Yggdroot** [scrooloose/nerdtree#314]
This is a bug.

**Comment by mb720** [comment]
Hi,

I just stumbled over this bug and would like to give more details and instructions how to reproduce it:

1. Create a file at `~/Desktop/dir , with , commas/testFile.txt`
2. Open it in Vim
3. Execute `:NERDTreeFind`

This results in the following error message:

> Error detected while processing function <SNR>45_findAndRevealPath:
> line 44:
> E716: Key not present in Dictionary: putCursorHere


I'm on Windows 10, 64 bits and have the latest version of NERDTree (git pull tells me that there's nothing to update).

Thanks a lot in advance.

**Comment by PhilRunninger** [comment]
@Yggdroot @mb720 My Windows VM is acting up on my, so I can't test it there. The bug doesn't exist, or was fixed, in MacOS. Can you try the newest commit to see if the issue still exists?

**Comment by lifecrisis** [comment]
@PhilRunninger, I'm using Windows right now.  Here's what I can confirm...

1. I can create `dir , with , commas\test.txt`, but opening the directory with `o` fails to show the child node.
2. It looks like the problem with `:NERDTreeFind` reported by @mb720 was the same as #779.  It may also be related to the commas, but we can't know until we fix the other problem.

As I recall, spaces in the file name can be an issue, but I remember that only being a problem at the beginning of the file.

**Comment by PhilRunninger** [comment]
@lifecrisis, Not a bug in Mac.
