### ISSUE TITLE
[Feature Request] Add Option to hide directories

### ISSUE THREAD

**Issue by thyseus** [scrooloose/nerdtree#317]
Currently, pressing F in Nerdtree toggles the displaying of files, which is working fine and is very useful. I suggest a key for toggling the displaying of directories, too. This is useful for quickly accessing files after opening a directory with lots of subdirectories using O.

**Comment by PhilRunninger** [comment]
This request would require extensive changes to the code, especially since any hidden folder would hide the files that are underneath it. Thanks for the suggestion, but presently, we're not willing to add this functionality.

**Comment by thyseus** [comment]
Cool! Thanks for the reply 4 years later. :)
