### ISSUE TITLE
Feature request: View highlighted file on cursor move when traverse NERDTree

### ISSUE THREAD

**Issue by Zloy** [scrooloose/nerdtree#319]
The corresponding question on stackoverflow (http://stackoverflow.com/questions/13119754/is-it-possible-to-just-view-files-content-when-traverse-nerdtree) took 6 upvotes, so it's likely useful feature.

I can traverse NERDTree, but to see file content I press go, and once opened file's buffer stays open until I explicitely close it. That makes viewing files too uncomfortable.

when I traverse NERDTree nodes I'd like to see the highlighted file content in a temporary viewer buffer and I'd like to explicitely select some of traversed files for editing, say by pressing e.

When I close NERDTree buffer, the temporary viewer buffer shall close as well, and there should only be opened buffers for those explicitely selected files, not for all viewed files.

**Comment by PhilRunninger** [comment]
The answer in the referenced StackOverflow post has a very workable solution. It needs some refinement, but it could be implemented as a NERDTree plugin, should anyone be ambitious enough to do it. For now, I think we'll leave it out of the NERDTree core.

@lifecrisis, any thoughts? Close this issue if you concur.

**Comment by lifecrisis** [comment]
I agree... this is exactly the kind of feature that should be left to a plugin.
