### ISSUE TITLE
File Marking and execution

### ISSUE THREAD

**Issue by connermcd** [scrooloose/nerdtree#32]
Hey NERDTree huggers,

Great plugin! Love what you've done! There's one feature I'm really missing from netrw that I think would be a great addition to your plugin: the ability to mark multiple files and execute a command on them at once. In netrw this is done by the mf and mx commands, by the functions NetrwMarkFile(islocal, fname) and NetrwMarkFileExe(islocal). From taking a brief peek at the code this should be extremely do-able in NERDTree, and would be extremely useful. For example, say I'm working on NERDTree in my git repository and I want to add certain files. I could mark those files using a command (in different directories in my tree branch even) then use one command to add them all to git! A myriad of other possibilities awaits.

**Comment by PhilRunninger** [comment]
I'm not going to pursue this, but if someone wants to tackle it, I'll entertain a pull request for it. One of the difficulties is that we're running out of letters to use for commands.
