### ISSUE TITLE
[Feature Request] Open previous/next file from tree

### ISSUE THREAD

**Issue by phelix** [scrooloose/nerdtree#320]
Just open the next file ocurring in the NERDTree while the pointer remains in the currently selected window. Maby with with either opening in same or new buffer/tab.

And a big thanks for that fish anyway ;)

**Comment by PhilRunninger** [comment]
This isn't something that should be put into NERDTree. You can use this key mapping to accomplish what you want to do: `:nmap <F8> 99<C-W>hjo` This assume NERDTree is on the left. Focus will move 99 windows to the left (That should be enough, right?), the cursor will move one line down, and then NERDTree's remapping of `o` will be called. Make sure you don't use `:nnoremap`, or you will be trying to `o`pen a new line in the unmodifiable NERDTree buffer.
