### ISSUE TITLE
NERDTree command with bad directory path crashes vim

### ISSUE THREAD

**Issue by bab491** [scrooloose/nerdtree#321]
When entering ":NERDTree bad_directory_name" vim crashes with a bunch of unhandled errors:

"Error detected while processing function 170..171:
line 6:
E718: Funcref required
etc. etc."

**Comment by PhilRunninger** [comment]
This has been fixed. Now you see this friendly message:
```
NERDTree: No bookmark or directory found for: bad_directory_name
```
