### ISSUE TITLE
[Feature Request] Track Active Item

### ISSUE THREAD

**Issue by StuartHa** [scrooloose/nerdtree#322]
NERDTree has :NERDTreeFind to find the current file in the tree, but there's no option to have this update automatically when a new file is opened.

Visual Studio has an option like this called 'Track Active Item'.

**Comment by rishitank** [comment]
you could do:

`function BufNerdHighlight()
   " When NERDTree and more than 1 buffer is open
   if (bufnr("$") > 1 && !(winnr() == 1 && exists("t:NERDTreeBufName")))
      " if not an empty buffer
      if !(getline(1) ==# '' && 1 == line('$'))
         :NERDTreeFind
      else
         :NERDTreeCWD
      endif
      :NERDTreeFocusToggle
   endif
endfunction

autocmd BufWinEnter * call BufNerdHighlight()
`

**Comment by rishitank** [comment]
And similarly for toggling NERDTree:

```
function! NTFinderP()
   " Check if NERDTree is open
   if exists("t:NERDTreeBufName")
      let s:ntree = bufwinnr(t:NERDTreeBufName)
   else
      let s:ntree = -1
   endif
   if (s:ntree != -1)
      " If NERDTree is open, close it.
      :NERDTreeClose
   else
      " if not an empty buffer
      if !(getline(1) ==# '' && 1 == line('$'))
         " Open NERDTree in the file path
         :NERDTreeFind
      else
         :NERDTreeCWD
      endif
   endif
endfunction

" NERD_Tree
map <silent> <Leader>n :call NTFinderP()<CR>
```

**Comment by PhilRunninger** [comment]
I didn't have any success with the above suggestions. `:NERDTreeFocusToggle` isn't a built-in NERDTree command, and I don't think the second suggestion addresses the OP's request.

Putting this code in my .vimrc seems to work pretty well, automatically finding the current buffer in the NERDTree. If NERDTree isn't open or if the buffer being entered isn't a normal buffer, it will do nothing. Non-normal buffers include ones like Vim help files and Quickfix. 
```vim
function! AutoNTFinder()
    if g:NERDTree.IsOpen() && &buftype == ''
        let l:winnr = winnr()
        let l:altwinnr = winnr('#')

        :NERDTreeFind

        execute l:altwinnr . 'wincmd w'
        execute l:winnr . 'wincmd w'
    endif
endfunction

autocmd BufEnter * call AutoNTFinder()
```
This isn't something I want to build into the core of NERDTree. I think it's best left as a .vimrc addition or a NERDTree plugin. Therefore, I am going to close this issue.
