### ISSUE TITLE
Open file in a new tab when clicking twice

### ISSUE THREAD

**Issue by Ziiweb** [scrooloose/nerdtree#323]
Hi,

any way to open a file or folder in a new tab when clicking the left mouse button twice?

I have tried this: `let g:NERDTreeMapOpenInTabSilent = '<2-LeftMouse>'` as said here:

http://stackoverflow.com/questions/10670111/remap-nerdtree-double-click-to-t

Im on NERD tree 4.2.0 and vim 7.4.

**Comment by mokuzon** [comment]
FYI:
 Although it's not good code, I forcefully change the click behavior by putting this in `.vimrc`.

```
autocmd WinEnter * if &ft == 'nerdtree' | call s:MyNERDTreeSetting() | endif
fun! s:MyNERDTreeSetting()
  fun! s:DoubleClickBehavior()
    if match(getline('.'), '▸') == -1 && match(getline('.'), '▾') == -1
      map <buffer> <2-LeftMouse> t
    else
      map <buffer> <2-LeftMouse> o
    endif
  endfun
  autocmd CursorMoved * call s:DoubleClickBehavior()
endfun
```

**Comment by jondkinney** [comment]
@peteonrails This might be useful to you if you're still rockin' the vim?

**Comment by PhilRunninger** [comment]
You need to override the mouse mapping a different way. Put this in your `vimrc`, and you should be good.
```
    autocmd VimEnter * call NERDTreeAddKeyMap({ 'key': '<2-LeftMouse>', 'scope': "FileNode", 'callback': "OpenInTab", 'override':1 })
    function! OpenInTab(node)
        call a:node.activate({'reuse': 'all', 'where': 't'})
    endfunction
```
You need the `autocmd VimEnter *` because `NERDTreeAddKeyMap` hasn't been defined at the time `vimrc` is being sourced.
