### ISSUE TITLE
Cannot read .NERDTreeBookmarks (?)

### ISSUE THREAD

**Issue by spring-haru** [scrooloose/nerdtree#325]
What I did:

I added the following line in .gvimrc:

let NERDTreeBookmarksFile = $HOME.'/Settings_in_Sync/vim/.NERDTreeBookmarks' 

What I got:

After saving a folder, I can see it in the NERDTree window, as expected. However, the window does not show the saved folder after restarting MacVim (Mavericks). This is  despite the fact that I can see the saved folder in .NERDTreeBookmarks opened in TextEdit. No error message is shown. Can you help?

**Comment by PhilRunninger** [comment]
I can't reproduce this issue on my setup. I know it's been a while; is this still an issue for you?

This is problably a side issue, but I have noticed that this variable doesn't like using `~`, or perhaps even relative paths. It's highly unlikely, but if your `$HOME` is set to `~`, this could cause a problem for you. I solved this problem in my vimrc by using the `expand()` function.
```
let NERDTreeBookmarksFile=expand("~/.vim/cache/.NERDTreeBookmarks")
```
