### ISSUE TITLE
Arrow icons don't properly display in shell

### ISSUE THREAD

**Issue by PunkChameleon** [scrooloose/nerdtree#329]
I can no longer see the arrow icons (seems to do with encoding), and therefore can't navigate in the shell. However, in MacVim they seem okay. Did the icons switch?

Also, is there a way to reset nerdtree?

This is in Mac OS X.

**Comment by studiodev** [comment]
I think I have the same problem. I cannot open a file/folder (with o or CR).
I use Iterm 2.0 (osx 10.10) and I'm connected by ssh on a debian server (which run vim).

![vim-nerdtree-invalid-character](https://cloud.githubusercontent.com/assets/872095/5961851/b157eb2a-a7df-11e4-9b65-1ff41a6462c0.png)
