### ISSUE TITLE
Feature request: Automatically set root according to presence of .git directory

### ISSUE THREAD

**Issue by clementpoh** [scrooloose/nerdtree#335]
Hi, great plugin.

The ctrlp plugin automatically attempts to detect the 'root' by going through ancestors until it finds a .git/.svn etc. directory, would it be possible to implement this feature as an option in nerdtree?

**Comment by chirag-applift** [comment]
Has this feature been implemented ? If yes, Is there any configuration required ?

**Comment by PhilRunninger** [comment]
Implemented in PR #872.
