### ISSUE TITLE
NERDtree doesn't play well with Vim sessions

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [scrooloose/nerdtree#337]
When I create a session and quit (see `:help session`), and then re-open vim and load that session, any NERDtree windows become empty windows. Subsequently hitting the NERDtree key leads to me having two tall, thin windows, only of which has a NERDtree in it.

(Using the auto-session snippet from [this StackOverflow post](http://stackoverflow.com/questions/7955232/making-macvim-reopen-with-files-open-when-closed).)

**Comment by PhilRunninger** [comment]
Opening a session bypasses all the initialization that needs to take place when NERDTree starts, and instead just creates an empty buffer named **NERD_tree_1**. This is a limitation of the way sessions are stored and restored. Not a NERDTree issue. You're better off making sure NERDTree is off when you save your session.
