### ISSUE TITLE
Error when creating multiple nodes at once

### ISSUE THREAD

**Issue by jceb** [scrooloose/nerdtree#34]
When I open NERDTree and press "ma" to add a child node, I get the following error message when I try to create multiple non existing nodes at once, e.g /home/joe exists, my input is /home/joe/test/dir/ect/ory/:

Error detected while processing function <SNR>58_showMenu..99..116..NERDTreeAddNo
de:
line   18:
E716: Key not present in Dictionary: isOpen || !empty(parentNode.children)
E15: Invalid expression: parentNode.isOpen || !empty(parentNode.children)
Error detected while processing function <SNR>58_showMenu..99..116:
line    6:
E171: Missing :endif
Error detected while processing function <SNR>58_showMenu..99:
line   19:
E171: Missing :endif

Besides the error message it works fine for directories but file node can not be created. The message is: NERDTree: Node Not Created.

**Comment by PhilRunninger** [comment]
Fixed, presumably by #11 and #295. Closing.
