### ISSUE TITLE
Minimal UI without the directory on top

### ISSUE THREAD

**Issue by chalmagean** [scrooloose/nerdtree#342]
Is it possible to loose the first line of the tree that shows the curent directory ? I don't see any use for that and it's usually too long/ugly. The minimal ui setting doesn't seem to get rid of it.

Thanks

**Comment by lifecrisis** [comment]
You seem to be in a slim minority here. I don't see how removing the root directory would be helpful. Not enough people have asked for this. There needs to be sufficient demand before an issue is given serious consideration. Thanks for the suggestion though!
