### ISSUE TITLE
Add git status support

### ISSUE THREAD

**Issue by Xuyuanp** [scrooloose/nerdtree#344]
@scrooloose Hi, welcome back!
I forked this repo and added a new feature:

![Imgur](http://i.imgur.com/jSCwGjU.gif?1)
(This gif is a little old, some features I added later isn't showing)

I think it's not a basic function for nerdtree but a powerfull extension. 
So I want to refactor it to a plugin of nerdtree. Could you open some APIs for me?

**Comment by albfan** [comment]
This seems to be working. Why this issue is still open? 

I think the only thing missing is a reference on help about `NotifyListeners` and *init*, *refresh* and *refreshFlags* events. Am I right?

**Comment by scrooloose** [comment]
Good point - I have just added some doc now.
