### ISSUE TITLE
Splitting the window selected by number

### ISSUE THREAD

**Issue by paprykarz** [scrooloose/nerdtree#345]
Independently of #313: what do you think about window selection by optional prepending window number to split? This is more precise than "wincmd p", which not distinguish buffer window from another window type.

For example: `5s` would vertically split window 5 (like `:5wincmd w|vsplit /file/under/cursor/in/nerdtree`) and so on (`2i`, `9o`). 

Showing `winnr()` in status bar may be helpful in jumping between windows.

**Comment by lifecrisis** [comment]
This is a good recommendation for a lot of NERDTree code in general. However, it is especially good since window numbers became unique in Vim 8.0.

**Comment by lifecrisis** [comment]
This was a neat idea, but there isn't really an issue to be resolved here.  You may want to explore this further independently.  Thanks!
