### ISSUE TITLE
open file in buffer without showing it from NERDTree

### ISSUE THREAD

**Issue by Ir1sh** [scrooloose/nerdtree#349]
I have just remapped <leader>t to :badd in the hopes that this would open the currently selected file in NERDtree to a buffer without opening it in a window.  Unfortunately it seems there is another step I am missing to tell it to use the currently selected file in nerdtree instead of having to enter the name of the file manually.

Is there an existing NERDTree command to do this, there dosnt seem to be from the help list.  

Can anyone tell me what I need to add the <leader>t :badd in my vimrc to make it do as want?  preferably so I can still type <leader>t filename if a file is not selected in NERDTree or NERDTree is not open

**Comment by sukima** [comment]
This bugged me so I dived in and figured it out. Here is [a NERDTree plugin][1] that will do as you ask. Just add [the file][1] to your `~/.vim/nerdtree_plugin` folder.

[1]: https://github.com/sukima/vimrc/blob/master/vimfiles/nerdtree_plugin/badd_keymap.vim

**Comment by PhilRunninger** [comment]
I'm closing this issue, as a solution has been provided by @sukima.
