### ISSUE TITLE
New releases?

### ISSUE THREAD

**Issue by fladi** [scrooloose/nerdtree#351]
Are there any plans to make start making versioned releases again? 4.2.0 dates back to 28th of December 2011.

This would make it easier to package NERD Tree for GNU/Debian (which is what I want to do).

**Comment by scrooloose** [comment]
about a year and half too late, but v5.0.0 has just been released

**Comment by jungle-boogie** [comment]
I don't see why this needs a release. it's easy to git pull and/or download and put in your vim directory.
