### ISSUE TITLE
Create parent directories as needed when moving.

### ISSUE THREAD

**Issue by kevincox** [scrooloose/nerdtree#360]
Recently support for creating missing intermediate directories when creating or copying nodes has been added to NERDTree.  However it appears that moving nodes hasn't been invited to the party.

It would be nice if intermediate directories could be created when moving as well.

**Comment by Iambecomeroot** [comment]
I have not looked at the source code but this doesn't sound hard. Why has there not been progress since 2014?

**Comment by lifecrisis** [comment]
@Iambecomeroot, you are likely correct. However, commits are rolling in lately and issues are starting to be closed again at a quicker pace. This issue will be addressed soon enough!
