### ISSUE TITLE
How to display NERD Tree fullscreen as opposed to split ?

### ISSUE THREAD

**Issue by nishantvarma** [scrooloose/nerdtree#367]
I have huge directory structure and when NERDTree opens its , the Directory heading is truncated from the left side . Is it possible to show it like /h/p/f/current ? Alternative can I open NERDTree in a new buffer as opposed to having it in a split ?

This looks similar to https://github.com/scrooloose/nerdtree/issues/342

**Comment by lifecrisis** [comment]
When viewing the NERDTree, pressing `A` will maximize/minimize the window (experiment to see for yourself). You may also use the standard `CTRL-W T` to view the tree in a new tab by itself.
