### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by matjon** [scrooloose/nerdtree#368]
Hello,
There should be a global license file to make the licensing situation more clear. There is a note but not on all files.
This may make contacting with contributors necessary in case They modified some files without the headers.

**Comment by ironmancris** [comment]
@scrooloose

:+1:  It would be very helpful if you add a license file, whatever kind of license. If not specified, by default the code is "All Rights Reserved" as explained [here](http://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github)
