### ISSUE TITLE
A function of NERDTreeMapOpenInTab that works only on files

### ISSUE THREAD

**Issue by matjon** [scrooloose/nerdtree#370]
Hello,
It would be nice if the NERD tree had a command working like NERDTreeMapOpenInTab when executed on a file and like NERDTreeMapActivateNode when executed on a directory.
It would be a tab-friendly version of NERDTreeMapActivateNode.
That way it would be more natural to work with nerdtree-tabs as <CR> could be bound to this command.

**Comment by PhilRunninger** [comment]
That's a perfect fit for a NERDTree plugin. See `:h NERDTreeAPI` and the examples in https://github.com/scrooloose/nerdtree/tree/master/nerdtree_plugin.
