### ISSUE TITLE
NERDTreeToggle reacts badly to buffers delete

### ISSUE THREAD

**Issue by dvarrazzo** [scrooloose/nerdtree#375]
Steps to reproduce:

    :NERDTreeToggle
    :bd
    :NERDTreeToggle

This causes:

    Error detected while processing function 191..192:
    line    7:
    E121: Undefined variable: b:NERDTree

and leaves an empty split. Leaving that split you also get:

    Error detected while processing BufLeave Auto commands for "NERD_tree_*":
    E121: Undefined variable: b:NERDTree

Tested in current master 4f1e6ecb057fc0bac189171c1430d71ef25f6bb1

**Comment by evserykh** [comment]
Have the same issue ☹

**Comment by SimpleX91** [comment]
Me too:
```Error detected while processing function 292..293:                                                                                                                                                                            
line    7:                                                                                                                                                                                                                    
E121: Undefined variable: b:NERDTree```
Using NERDTreeFind.

**Comment by scrooloose** [comment]
It should now handle `:bd`. Note that the nerdtree will lose any state when opened again as all of the  state data is in `b:NERDTree` - which is deleted with the buffer.
