### ISSUE TITLE
Cannot open two files with identical names but different case

### ISSUE THREAD

**Issue by mxdubois** [scrooloose/nerdtree#377]
I have `file.js` and `File.js` in the same directory. If `file.js` is open and I attempt to open `File.js`, nerdtree  returns my cursor focus to the `file.js` buffer without opening `File.js`.

Can anyone else reproduce this?

**Comment by lifecrisis** [comment]
Confirmed that this is still a bug.

**Comment by PhilRunninger** [comment]
Here's a weird observation. You can open the second file if you use `t`, `go`, `s`, `gs`, or `v`, but not `<Enter>`, `o` or `gv`.
