### ISSUE TITLE
Releases versioning, Changelog aren't updated

### ISSUE THREAD

**Issue by alonisser** [scrooloose/nerdtree#385]
Nerdtree is a very popular vim plugin, looking at the commit history, looks like a popular open source project and the target of multiple Pull requests.

Unfortunately Nerdtree changelog and releases (git tags) aren't updated to reflect that. last release (and changlog update referring it) is from 2011. This makes it hard to lock versions (as an end user) and even understand what changed (and how could that lead to the  bug you are suffering from.. )

**Comment by scrooloose** [comment]
v5.0.0 was released about 20 seconds ago :)
