### ISSUE TITLE
Error invokeKeyMap When opening a file with nerdtree 

### ISSUE THREAD

**Issue by alonisser** [scrooloose/nerdtree#386]
I always get:

> > Error detected while processing function nerdtree#ui_glue#invokeKeyMap..71..70..>>>><SNR>37_activateFileNode..99..116..166..167..13:

This doesn't happpen in all my installed vim's but only in the one I installed last, but checking an older commit to a previous (working?)  one still has this error.

Any clues?

vim --version output:

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions

**Comment by jgelens** [comment]
This probably has something with your menu setting in vimrc
In my case commenting the following lines in my .vimrc fixed the issue.

# aunmenu Help.
# aunmenu Window.
# let no_buffers_menu=1

**Comment by toszter** [comment]
I'm having the saaaame issue. None of the aforementioned lines are in my .vimrc @jgelens

**Comment by jchayan** [comment]
I managed to solve this. The problem is related to the swap files directory.

if you have this:

```
set swapfile
set dir=<swap files directory>
```

Just check if the directory exists. If it does not. Create it yourself and restart vim

**Comment by prrraveen** [comment]
@jchayan *+1 this soved my issue*

**Comment by cokara** [comment]
Thanks @jchayan that was it!!

**Comment by liang1224** [comment]
@jchayan My vim-config is this[https://github.com/spf13/spf13-vim](url), I meet the same problem. but as  a freshman,I don't konw how to resolve it. please tell me the detail,thanks! I'm Chinese,and I'm weak at English,Excuse me.

**Comment by zekefast** [comment]
Similar error happens in case if you have
```vim
set backupdir=...
set directory=...
set undodir=...
```

in your `.vimrc`, but have no those directories created in appropriate places.
As @jchayan said creation of those directories help solve the issue.
