### ISSUE TITLE
Error detected when opening dir in Vim

### ISSUE THREAD

**Issue by ianks** [scrooloose/nerdtree#387]
Whenever I open NT up with a dir I am hit with this error, but then everything seems to load fine after that. 

```
"bin" is a directory
Error detected while processing function <SNR>190_startup:
line    3:
E85: There is no listed buffer
```

I'm not even sure where this error is originating from as I do not know Vimscript well at all, but maybe this is a candidate? Any tips would be greatly appreciated!

``` VimL
" /vim-nerdtree-tabs/nerdtree_plugin/vim-nerdtree-tabs.vim

" open NERDTree on gvim/macvim startup
if !exists('g:nerdtree_tabs_open_on_gui_startup')
  let g:nerdtree_tabs_open_on_gui_startup = 1
endif
```

**Comment by n8armstrong** [comment]
Same here, and without OP's snippet.

**Comment by scrooloose** [comment]
The startup function is not defined in nerdtree. We can find out which file it _is_ defined by:

1. reproduce the error and note the function name (it is `<SNR>190_startup` in your example)
2. note the number in the function name - 190 in the example
3. run :scriptnames (shows the files that vim has sourced so far). Scroll down until you find the script with the number from the function. This is where the `startup` func is defined.

Can anyone tell me what script it is?

**Comment by PhilRunninger** [comment]
Closed due to no response from issue's creator.
