### ISSUE TITLE
invokeKeyMap Error in NerdTree

### ISSUE THREAD

**Issue by jchayan** [scrooloose/nerdtree#389]
Any time a file is opened with nerdtree. vim throws this error:

Error detected processing function nerdtree#ui_glue#invokeKeyMap..73.
.72..<SNR>44_activateFileNode..101..118..168..169..15: 

Appreciate some help. I'm delaying my work.

**Comment by PhilRunninger** [comment]
This issue has been idle for a while, so I'm closing it. Feel free to reopen with more detail if necessary.
