### ISSUE TITLE
:NERDTreeFind fails if it's the first invocation of nerdtree

### ISSUE THREAD

**Issue by lostscrew** [scrooloose/nerdtree#393]
It would be nice if `:NERDTreeFind` worked even when nerdtree has not yet been used in the current Vim session. Currently it throws an error:

```
Error detected while processing function <SNR>41_findAndRevealPath..153:
line    2:
E605: Exception not caught: NERDTree.InvalidArgumentsError: <path>/<filename> should be under <path>
```

**Comment by Pieter-Jan** [comment]
Is there a solution for this issue?

**Comment by PhilRunninger** [comment]
@lostscrew, @Pieter-Jan, I don't have access to Cygwin. Can you verify this is still an issue?
