### ISSUE TITLE
Auto search NERDTree upon typing

### ISSUE THREAD

**Issue by zxiest** [scrooloose/nerdtree#395]
This is more of a question than an issue...

I would like to be able to automatically move to a node in NERDTree without having to do `/foo` but instead, I want to move there (first result) when I type `foo`. This is useful when I want to see the directory structure but I'm not sure about the file name. (If I knew the file name, I'd use CtrlP)

Typing /foo then Enter is too many keystrokes for me.

Any idea on how to achieve that?

**Comment by lifecrisis** [comment]
Hey, @zxiest... neat suggestion, but I don't believe it's feasible. For example, `f` and `o` are default NERDTree mappings. Thus, typing `foo` without `/` would toggle the NERDTree file filters and then toggle open and closed the directory node under the cursor (or open a file node and then open a line in the buffer that was entered).

You're expecting too much here, I think.

**Comment by zxiest** [comment]
Haha this is many years late - I've gotten used to it now =)

**Comment by lifecrisis** [comment]
Yeah, progress has been slow. However, we're starting to close issues again. It's a pretty critical plugin, so picking it back up is a good thing for everyone.

**Comment by zxiest** [comment]
Ah nice! Welcome aboard and best of luck! :-D
