### ISSUE TITLE
Are you using NERDTree and Ctags? Then Tagexplorer could be useful.

### ISSUE THREAD

**Issue by ReneFroger** [scrooloose/nerdtree#396]
I just discovered the [TagExplorer](http://www.vim.org/scripts/script.php?script_id=483). Actually, the plugin is **12 years old** and never updated. 

When I set the path to Ctags executable, I get a list with `:TagExplorer`. Like NERDTree. 

When you open a file with `o`, you will see a list of functions, classes and variables definied per function in that file, like Taglist. But if you choose instead to just open with `<Enter>`, it will open the file like NERDTree. 

Strangely I found not another alternative for this yet. It could be so useful. Given the fact his old age and not much developed yet, no wonder it's missing some features. Wondering if it could be integrated into NERDTree or Netrw?

**Comment by PhilRunninger** [comment]
This isn't something we'd be willing to support.
