### ISSUE TITLE
Open existing file with space in path on Windows and shellslash set

### ISSUE THREAD

**Issue by marcelocra** [scrooloose/nerdtree#398]
If I have the file "C:\Users\My Name\Devel\MyFile" and I try to open this file from NERDTree once I set the shellslash option, I go to a new file, within a new directory: "C:\Users\My\ Name\Devel\MyFile".

**Comment by mdelbuono** [comment]
I have the same problem. Did you find a solution?

**Comment by marcelocra** [comment]
Not really.. Just avoided that option on Windows, as far as I remember.

**Comment by lifecrisis** [comment]
**ANNOUNCEMENT**:  Pull request #734 offers a potential fix for this problem. Please checkout the branch there for testing. It must be tested before we merge the changes.
