### ISSUE TITLE
Some directories disappears after refresh with R

### ISSUE THREAD

**Issue by milushov** [scrooloose/nerdtree#399]
Hello, thanks for awesome plugin, but I found a problem:
my project's folder
![image](https://cloud.githubusercontent.com/assets/424326/5026615/f2b2821e-6b36-11e4-9113-2e6a964b26ba.png)

after refresh with R becomes
![image](https://cloud.githubusercontent.com/assets/424326/5026625/06ff4112-6b37-11e4-940d-e075c1290d12.png)

How to fix this issue?

**Comment by victoriastuart** [comment]
@milushov: briliant!  NERDtree wasn't showing some files (sometimes was; sometimes not), e.g. *.js files.

Removing *.js from "set wildignore+=..." in my ~.vimrc appeared to solve this!

**Comment by lifecrisis** [comment]
The inconsistency in how the NERDTree behaves in relation to the `g:NERDTreeRespectWildIgnore` setting is being addressed in pull request #716. This issue will be closed when that pull request is merged.

**Comment by lifecrisis** [comment]
This issue was resolved by pull request #717.
