### ISSUE TITLE
NERDTree does not reuse window with scratch/unnamed/nofile buffer when opening file

### ISSUE THREAD

**Issue by alexanderte** [scrooloose/nerdtree#405]
I use the [Kwbd](https://github.com/rgarver/Kwbd.vim) plugin to close buffers without altering the layout of windows. If there are no buffers left then Kwbd creates an empty buffer – or in vim terms, a buffer where `buftype` is set to `nofile`. CtrlP does have a configuration setting which lets it reuse special buffers. However, I cannot find any such setting for NERDTree.

The current behavior for NERDTree is to open a file in a new split. Is is possible somehow to tell NERDTree to reuse `nofile` buffers?

**Comment by PhilRunninger** [comment]
No, it's not possible. I think a better option would be for Kwbd to not set the buftype at all. It should give you a buffer just like you get when you start vim with no parameters.
```vim
$ vim
:set buftype?
  buftype=
```
If you compare https://github.com/rgarver/Kwbd.vim/blob/master/plugin/bclose.vim#L45 against the Vim Wiki entry the plugin was made from - http://vim.wikia.com/wiki/Deleting_a_buffer_without_closing_the_window - you'll see that the `nofile` value was removed from the Wiki entry on [Dec 22, 2011](http://vim.wikia.com/wiki/Deleting_a_buffer_without_closing_the_window?diff=32241&oldid=31466)
