### ISSUE TITLE
Expand a compressed file as a folder

### ISSUE THREAD

**Issue by monkeyqyf** [scrooloose/nerdtree#407]
This is a feature request. 
Is it possible to expand a compressed file (zip tar.gz 7z, etc) as a folder in the directory tree? If there's other more compressed file in upper file, then we could move cursor on it and enter to expand the file recursively.
If this has already been implemented, could you update to let me know? Thanks in advance.

**Comment by yan12125** [comment]
+1 It's a useful function.

Official vim's zip.vim is just usable. I hope I can view files in a zip archive in new tabs.

**Comment by hotoo** [comment]
+1

**Comment by lifecrisis** [comment]
Vim already contains a plugin, `zip.vim`, for exploring Zip files.  Other than that, you could easily author a NERDTree plugin to add the desired functionality.  This is not something that needs to be added to the NERDTree core.  See the documentation for information on how to do this.
