### ISSUE TITLE
invokeKeyMap Error

### ISSUE THREAD

**Issue by jchayan** [scrooloose/nerdtree#408]
Any time I open a file. vim throws this error:

Error detected processing function nerdtree#ui_glue#invokeKeyMap..73.
.72..44_activateFileNode..101..118..168..169..15:

**Comment by PhilRunninger** [comment]
@jchayan, This information is outdated, given the length of time that has passed and changes that have been made to the code. It is quite possible this issue has been resolved, so I'm closing it. Reopen it if necessary.
