### ISSUE TITLE
Arrow color changed

### ISSUE THREAD

**Issue by aaronmoodie** [scrooloose/nerdtree#409]
![screen shot 2014-12-17 at 7 31 35 pm](https://cloud.githubusercontent.com/assets/105030/5490099/f263fc94-869c-11e4-9399-8b9021268e1a.png)

I've just done a clean setup of Vim, and after installing NERDTree, noticed that the arrows on the directories are now a separate color, regardless of theme.

**Comment by Leeiio** [comment]
+1

**Comment by PhilRunninger** [comment]
Closes I don't see anything in the history to indicate the syntax had changed. Regardless, I like the change submitted by @Leeiio .
![image](https://cloud.githubusercontent.com/assets/5598066/19363988/4fc9a2b6-915a-11e6-9fc0-5d54a5462f74.png)
