### ISSUE TITLE
Option to open single subdirectories automatically

### ISSUE THREAD

**Issue by udp** [scrooloose/nerdtree#410]
Particularly in Java projects, one often ends up with a directory structure like this:

    com/
       mycompany/
           myproject/
               MyClass.java

GitHub's file browser now merges those three directories into a single "com > mycompany > myproject" node.  In the context of NERDTree, a simpler yet equally useful feature would be an option to automatically open mycompany/ and myproject/ when "com" is clicked.  Basically, it's a recursive: when directory node is opened and only contains a single directory node, open it.

I attempted to implement it but was thwarted by lack of VimScript knowledge.  I may try again at some point in the next few weeks.

**Comment by matt-gardner** [comment]
Note that nerdtree now behaves like github in merging those into a single node, so this can probably be closed.

**Comment by scrooloose** [comment]
Good point.
