### ISSUE TITLE
ENH,UBY: Tab title from NERD_tree_2 to $PWD

### ISSUE THREAD

**Issue by westurner** [scrooloose/nerdtree#412]
Usability Enhancement: It would be useful if nerdtree tab titles showed the current filepath.

Current tab title when selected:

```
NERD_tree_2
```

Expected tab title when selected (Desired):

```
$PWD <NERD_tree_2>
# OR
NERD_tree_2 $PWD
# OR
# ...
```

**Comment by PhilRunninger** [comment]
See #774.
