### ISSUE TITLE
Opening a file through NERDTree conflicts with vim-rspec

### ISSUE THREAD

**Issue by guvarallo** [scrooloose/nerdtree#413]
The vim-rspec mapping is only getting the right path for files open directly. All the files opened through NERDTree conflicts with the test mapping.

I have the following mapping on my .vimrc

```
 " vim-rspec mappings
 let g:rspec_runner = "os_x_iterm"
 map <Leader>t :call RunCurrentSpecFile()<CR>
 map <Leader>s :call RunNearestSpec()<CR>
 map <Leader>l :call RunLastSpec()<CR>
 map <Leader>a :call RunAllSpecs()<CR>
```

So when I do the spec command inside vim on the file that works, it gives the right path:

 `rspec spec/controllers/queue_items_controller_spec.rb`

But on all files opened through NERDTree, the path comes with the parent folders:

```
rspec /(...)/(...)/(...)/spec/controllers/reviews_controller_spec.rb
```

**Comment by PhilRunninger** [comment]
This probably has more to do with your CWD at the time you run the rspec functions.
