### ISSUE TITLE
NERDTreeRO coloring does not apply to the last (i.e. bottom) file in a directory

### ISSUE THREAD

**Issue by steeeeeeleydan** [scrooloose/nerdtree#415]
The NERDTree syntax doesn't recognize the "last node" symbol "`" for RO files.

I added this <>\syntax\nerdtree.vim:57:

```
syn match NERDTreeRO #`-.*\[RO\]#he=e-5 contains=NERDTreeIgnore,NERDTreeBookmark,NERDTreePart,NERDTreePartFile
```

I've only fixed my local syntax since I don't understand how to propose a change to the main trunk.

**Comment by PhilRunninger** [comment]
This has been refactored. Try the new commit, and see if it works for you. For now, I'm closing the issue. Reopen if necessary.

**Comment by steeeeeeleydan** [comment]
Confirmed repro with 4.2.0 and no repro with 5.0.0.

Thanks !
