### ISSUE TITLE
nerdtree make vim pwd points to parent dir when open a dir with `vim .`

### ISSUE THREAD

**Issue by guoqiao** [scrooloose/nerdtree#418]
For example:
I put all my code repo in ~/src dir.
And I have n projects p1, p2, ..., pn in ~/src.
Normally, if I want to begin work on p1, I'd like to do this:

cd ~/src/p1
vim .

Then I can use :pwd to see the current working dir.
If I disable NERDTree,  pwd is ~/src/p1, which is right.
However, with NERDTree enabled, the pwd will be ~/src

Since I use ctrlp.vim a lot, which will search the project files depends on the pwd.
Now, every  time when I cd into ~/src/p1 and open it with vim . and then try to search a file with ctrlp, it will search all the files in ~/src instead of ~/src/p1

Both NERDTree and ctrlp are my must-have vim plugins. Is there anyway I can fix this?

**Comment by guoqiao** [comment]
If I comment out `set autochdir`,  it's gone.

**Comment by Coacher** [comment]
I can confirm this. Please fix.

**Comment by guoqiao** [comment]
After removing `set autochdir`, it works fine now, the pwd is right.
However, now, every time when I open NERDTree, the dir is the project root, not the dir the current file is in. I still miss autochdir a lot:D

**Comment by PhilRunninger** [comment]
@guoqiao, @Coacher, I can't reproduce this. It may have been fixed sometime in the last 3 years, or I don't understand how to trigger it. Can this be closed?

**Comment by catalyst-joe-guo** [comment]
@PhilRunninger  Yes, please close it. Thank you.

**Comment by guoqiao** [comment]
@PhilRunninger Yes, please close it. Thank you.
