### ISSUE TITLE
How to change displayString() without breaking up the keybindings?

### ISSUE THREAD

**Issue by tbabej** [scrooloose/nerdtree#422]
Hi,

I tried to do a really small visual change for my file nodes in the NERDTree (removes .txt extensions):

https://github.com/tbabej/nerdtree/commit/f35ca32bb8b0e0e01d14734f911239bd745eb187

However, this breaks any keybindings on this node. Can you offer any pointers how to fix this?

**Comment by PhilRunninger** [comment]
Removing parts of filenames will cause NERDTree to be unable to find and open the selected file. This is probably the root cause of your issue, and I don't recommend it. You can add text to the line, such as the readonly flag or git flags, but removing information will lead to problems.
