### ISSUE TITLE
cannot expand folder with name starting with "["

### ISSUE THREAD

**Issue by sherifkandeel** [scrooloose/nerdtree#424]
Whenever I try to "o" a folder in the nerdtree starting with "[" it collapses the whole tree. 
I also noticed it's not even marked like the other openable folders.

![screenshot 2015-03-08 22 25 34](https://cloud.githubusercontent.com/assets/1388434/6547507/976b4c2c-c5e2-11e4-8ded-73432dc0a2fc.png)
![screenshot 2015-03-08 22 26 03](https://cloud.githubusercontent.com/assets/1388434/6547509/9b519666-c5e2-11e4-958e-7e92a070344d.png)

I'm using gVim 7.4 under windows 8.1

**Comment by cukuriwaray** [comment]
Can't open folder if name contains '[':

![nerd-tree](https://cloud.githubusercontent.com/assets/3327005/10997233/879aea36-849c-11e5-8929-b48ee60ef216.png)

Reproduced under VIM 7.4.52 and NVIM v0.1.0-10-g32a9022 under ubuntu 14.04

**Comment by yinflying** [comment]
Yes, the bug also happened at my machine .Not only the folder name ,but also the filename .

**Comment by lifecrisis** [comment]
Confirmed bug. Related bug has been reported in #680, et al.

**Comment by PhilRunninger** [comment]
@sherifkandeel @yinflying @cukuriwaray , would you be willing to test the pull request #868 I've put together for this issue? Details are in the PR. Thanks.

**Comment by sherifkandeel** [comment]
@PhilRunninger wow, thank you for doing that, I will test it this week :)

**Comment by PhilRunninger** [comment]
Fixed in #868.
