### ISSUE TITLE
Moving a file opened in a buffer and then replacing its buffer opens an extra file.

### ISSUE THREAD

**Issue by Grazfather** [scrooloose/nerdtree#426]
Steps to repro:
1. Open a file
2. Open nerdtree and navigate to it
3. Hit m, then m, then choose a new name
4. Select y

Two buffers will be open. One empty file and only that correctly opens the old filename with the new name.

**Comment by moll** [comment]
Seeing the same thing. The old file seems to have the same name, but with an apostrophe at the end.

**Comment by PhilRunninger** [comment]
This bug has been fixed. I vaguely remember the apostrophe symptom. If this issue resurfaces, create a new issue for it.
