### ISSUE TITLE
Document that ctrl-ww moves between open windows is how to move back to nerdtree

### ISSUE THREAD

**Issue by tecfu** [scrooloose/nerdtree#428]
Demand seems sufficient to justify adding this to the docs somewhere. 

See: http://stackoverflow.com/questions/1656591/how-to-jump-back-to-nerdtree-from-file-in-tab

**Comment by scrooloose** [comment]
This is an issue with window navigation. Its not the responsibility of nerdtree to teach people this.

The authoritative source for this is (i.e. `:h windows.txt`) and I guess we could point people there, but then we would potentially have to do this for all sorts of vim concepts.
