### ISSUE TITLE
Don't allow user to use 'o' on the parent folder

### ISSUE THREAD

**Issue by amsheehan** [scrooloose/nerdtree#432]
If a user is on the parent folder of the source tree and uses o, it will recursively open that folder and lock up the terminal.

**Comment by lifecrisis** [comment]
I believe you are talking about the `O` macro. It's a useful mapping.

I'm rejecting your suggestion. There are many cases where the user will want to recursively open the root node of the NERDTree. If the project is small, this can be quite useful. It's up to the user to decide when to use this macro.

If you trigger this operation and realize that the directory is too large for it, you may abort the operation with `CTRL-C` followed by `X`. Triggering `X` will close any nodes that were opened without being rendered, putting you back to where you started.

An alternate method would be to abort with `CTRL-C` and then open a new NERDTree by calling the usual `:NERDTree` command.
