### ISSUE TITLE
Is it possible to remove the help line at the top

### ISSUE THREAD

**Issue by nunoh** [scrooloose/nerdtree#437]
How can I get rid of the `"Press ? for help` line at the very top of NERDtree? Thanks!

**Comment by albfan** [comment]
You just need to find that string on plugin.

[autoload/nerdtree.vim:260](https://github.com/scrooloose/nerdtree/blob/1cbd52aa77541682658f4c8a6d217c77a78c3879/autoload/nerdtree.vim#L260)

that leads to "g:NERDTreeMinimalUI"

[NERD_tree.txt:671](https://github.com/scrooloose/nerdtree/blob/cd5f1685bcb096577ee98f9ff0f73e101b15a1aa/doc/NERD_tree.txt#L671)

so, add this to `.vimrc`

    let NERDTreeMinimalUI=1

to remove it

**Comment by nunoh** [comment]
@albfan Thanks so much :sweat_smile:

**Comment by amk221** [comment]
This also removes `.. (up a dir)` which is actually useful

**Comment by PhilRunninger** [comment]
On the contrary, `.. (up a dir)` is also handled by the `u` and `U` shortcuts. That means you can go up a level no matter where your cursor is, making that line of text very unimportant.

**Comment by amk221** [comment]
rightyho

**Comment by Blainegith** [comment]
F

> This also removes `.. (up a dir)` which is actually useful

Also can be doing in .vimrc:
`let NERDTreeMinimalUI=1`
