### ISSUE TITLE
Pressing 'i' splits in the nerdtree browser when nerdtree is started from autocmd

### ISSUE THREAD

**Issue by joslinm** [scrooloose/nerdtree#438]
I stuck this in my vimrc: `autocmd vimenter * NERDTree`

I then started vim in a directory by doing `vim .` and in the main window, browsed to a file. 

Then I intended to split horizontally another file so I went to nerdtree browser and pressed 'i' on a file. It split it in the nerdtree browser

**Comment by scrooloose** [comment]
I am unable to reproduce this. Can you show me your vimrc?

**Comment by PhilRunninger** [comment]
I can't reproduce this either. With no feedback in over 2 years, I'm going to close this. Reopen if necessary.
