### ISSUE TITLE
how do I resize my windows? 

### ISSUE THREAD

**Issue by fourq** [scrooloose/nerdtree#440]
I swear there was an easy key combo for this that I just forgot.

**Comment by albfan** [comment]
Are you sure your issue is related to NERDTree? 

To maximize/minimize NERDTree you have (A)

   :help NERDTree-A

To toggle (open/close) NERDTree you could add this to `~/.vimrc`

    map <leader>tn :NERDTreeToggle<CR>

And to return to NERDTree from whatever window

    map <leader>fn :NERDTreeFocus<CR>

Try to be more specific if that do not solve your problem

**Comment by fourq** [comment]
oh, sure. Here's a clip of what I'm trying to accomplish with keys instead of mouse: http://screencast.com/t/z5FvrntV

Thanks
