### ISSUE TITLE
Add custom evaluators to ignore node

### ISSUE THREAD

**Issue by albfan** [scrooloose/nerdtree#441]
It would be nice to add custom evaluator to ignore() function. Providing

    addIgnoreEvaluator()

and IgnoreEvaluator being a function like

    bool ignore(path)

ignore() function will be a loop like

    bool ignore
    for(ignoreEval in ignoreEvaluators) {
       ignore = ignoreEval.ignore(path)
       if(ignore)
          return true
    }
    return false

I can provide an implementation but I want to know if it would be merged on NERDTree

**Comment by scrooloose** [comment]
Excellent timing! I was just writing exactly that code :)

See #373 for the discussion that started it. I have just pushed a first stab at the API to a branch and have created a gist with a demo of how to use it (see the comment in the linked issue).

Let me know how you get on.
