### ISSUE TITLE
Intelligently/programatically hide files per directory?

### ISSUE THREAD

**Issue by adambiggs** [scrooloose/nerdtree#451]
Just wondering if anybody knows a way to hide files in a directory based on some conditions.

For example, if I've got a directory with `something.coffee`, which compiles `something.js` and `something.js.map` in the same directory. But there also might be `gulpfile.js` which doesn't have a corresponding `.coffee` file, so I don't want to hide all `.js` files...

It would be cool if I could write some logic to hide `.js`/`.map` files *only if* there's a matching `.coffee` file in the same directory.

**Comment by scrooloose** [comment]
You're in luck - an api for this has been added in the last week.

Here is the code to do what you want: https://gist.github.com/scrooloose/17057040c94b6b9786a4

It could be made a lot more efficient - at the moment it is doing a `globpath` for every js or js.map file each time the tree is rendered. This could probably be cached and reused for each dir i.e. if there are 100 `.js` files in one dir then cache the `globpath()` that grabs the `.coffee` files.

This should be a good start though.

Let me know if there are any issues.

**Comment by adambiggs** [comment]
Awesome! Thanks @scrooloose!

Any chance of creating a repo for this so I can install it with VimPlug?

**Comment by adambiggs** [comment]
FWIW I figured out how to install it with VimPlug from the Gist:

```vim
Plug 'https://gist.github.com/17057040c94b6b9786a4.git', { 'dir': '~/.vim/nerdtree_plugin/coffee_filter.vim' }
```

**Comment by scrooloose** [comment]
Heh, that's pretty awesome :)

That code could be much more efficient. If things start to bog down when you open a dir then look into caching the result of the globpath.
