### ISSUE TITLE
Could NerdTree show file type?

### ISSUE THREAD

**Issue by sensorario** [scrooloose/nerdtree#454]
What I mean is, ... to show if current file is a Class, in Interface, a Trait, or something like that. Is this a possibile?

**Comment by scrooloose** [comment]
Try this: https://gist.github.com/scrooloose/a60ebc0d685c6f5535a2

It will put flags beside class/interface files. The interesting part is how to check a file to determine what type it is.

![demo](https://cloud.githubusercontent.com/assets/1671/7821649/2c7b8ac8-03e8-11e5-8baf-315b5afc07b5.png)


The easiest way would simply be to use the full pathname - e.g. if we have a dir structure like this:  `/path/to/project/class_files/foo.java` then we can trivially match the filename.

My example in the gist greps every single file that is loaded into the tree to see if it is a class/interface. This is pretty hamfisted... but it does the job for demo purposes.

Let me know how you get on.
