### ISSUE TITLE
Fails to hijack netrw when executing :Sex

### ISSUE THREAD

**Issue by h3xx** [scrooloose/nerdtree#455]
`:Explore` explores the directory where the current buffer's file is located in netrw. However, NERDTree does not hijack this explorer buffer.

However, one can cause NERDTree to hijack it if one switches windows away from the netrw browser and then back to it.

Other affected commands:

* `:Sexplore`
* `:Explore`
* `:Texplore`
* `:Hexplore`

*did i get your attention?*

**Comment by scrooloose** [comment]
You did indeed get my attention.

This is by design so people can still get to netrw if they so desire. If you want more nerd tree in your :Sex then you have to use 'sp .'
