### ISSUE TITLE
Does not show broken and circular symlinks in tree

### ISSUE THREAD

**Issue by h3xx** [scrooloose/nerdtree#458]
NERDTree unnecessarily hides directory contents.

OS: Linux with XFS file system.

Steps to reproduce:

    $ mkdir test
    $ cd test
    $ touch real_file ; mkdir real_dir
    $ ln -s real_file real_file_symlink ; ln -s real_dir real_dir_symlink
    $ ln -s no-file broken_symlink
    $ ln -s circular_symlink{1,2} ; ln -s circular_symlink{2,1}
    $ vim .

Only `real_*` will be displayed in the resulting NERDTree buffer.

(Assuming NERDTree hijacks netrw)

**Comment by h3xx** [comment]
**Related to the ticket, but not the same:**

I'm used to `ls -l` output in my directories, so if there were a way to change the way NERDTree displays symlinks to be like ls, that would be optimal.

Stuff like `symlink => ../relative_path` would be nice to see instead of full paths everywhere.

**Comment by scrooloose** [comment]
The cause of this is that `glob()` doesn't return broken symlinks.

Ill look into relative paths for symlinks.

**Comment by h3xx** [comment]
I noticed the default netrw browser **also** hides broken and circular symlinks.

**Comment by scrooloose** [comment]
I would expect so. I haven't checked, but netrw is almost certainly using `glob()` as well.
