### ISSUE TITLE
How to choose specific existing window to open a new file in NERDTree

### ISSUE THREAD

**Issue by Nan-Zhang** [scrooloose/nerdtree#461]
Hi, there,

Currently I am using NERDTree for helping navigation of vim. But it seems that when I selected a specific file and want to open it, NERDTree always opened it by overwriting the most recent window which is a little annoying sometimes. If there is way to open that file so that we can specify which window should be overwritten?

**Comment by phcerdan** [comment]
This would be great

**Comment by PhilRunninger** [comment]
Duplicate of #211.
