### ISSUE TITLE
can nerdtree reload automatically when the file was changed?

### ISSUE THREAD

**Issue by ilovezy** [scrooloose/nerdtree#462]
hello, I am using gulpjs  those days, sometimes I use gulp-uglify to a dist file,when it is done, the nerdtree did't refresh,I have to click "r" to refresh the nerdtree, but in sublime text, it will refresh when the files changed, so I am wondering can nerdtree do this,I look for all doc in help but did'n find something talk about this

**Comment by PhilRunninger** [comment]
You can use `autocmd`s in your vimrc to cause NERDTree to refresh when you save a file in vim. The `'autoread'` setting will cause vim to watch the file system, and reload an open file if something else changed it. But there is no mechanism in NERDTree to watch the file system for changes. Polling would likely cause an undesirable performance hit.
