### ISSUE TITLE
Default NERDTreeStatusline should end with /

### ISSUE THREAD

**Issue by mkoskar** [scrooloose/nerdtree#465]
I believe that for sake of consistency default `NERDTreeStatusline` should produce output ending with `/`. That's consistent with highlighted top of the tree.

```
plugin/NERD_tree.vim:87:    let g:NERDTreeStatusline = "%{exists('b:NERDTreeRoot')?b:NERDTreeRoot.path.str():''}"
```

One way of doing that I've found would be:

```
let g:NERDTreeStatusline = "%{exists('b:NERDTreeRoot')?b:NERDTreeRoot.path._strForUI():''}"
```

**Comment by PhilRunninger** [comment]
I could go either way on this one. It's a simple change, but it could, however unlikely, cause issues if another plugin is relying on that statusline not ending with a slash. Also, that simple change can be just an additional line in a vimrc. @lifecrisis, what do you think?

**Comment by lifecrisis** [comment]
@PhilRunninger, I say leave it to the user's `.vimrc` file.

**Comment by mkoskar** [comment]
@PhilRunninger I can't even conceive a way how could anything rely on the NERDTree's statusline. I mean is there a way to get evaluated value? All you can get is the format and then let's say prepend it to something to form a new format (is that what you meant?). FWIW I used that custom format for well over 2 years without any problems and I use fair amount of other plugins.

Also looking at documentation just now, I believe the default value for `NERDTreeStatusline` is wrong and should be `%{exists('b:NERDTree')?b:NERDTree.root.path.str():''}`.

**Comment by lifecrisis** [comment]
@mkoskar: It doesn't end with slash because of two reasons:

1. The slash varies with the OS.
2. At the root directory, the will show as `//`.  You will need a conditional to stop this from happening.

More code is needed than you think to make this change.  Keep it in your `.vimrc`, please.  It hurts nothing for it to be there.

Your suggestion about the documentation was noted and will be fixed shortly.  Thanks.

**Comment by mkoskar** [comment]
Replying to @lifecrisis above:
1) true
2) I don't see it happening myself, notice I don't add the slash myself, I just have it call `_strForUI()` instead of `str()`

Yeah, no problem with me either way. Thanks for looking at this anyway, I know it's just rather silly thing. I'm a bit of perfectionist so I notice these kind of inconsistencies, what can I say heh :).

**Comment by lifecrisis** [comment]
That's all fine.  I understand.

It's true that `_strForUI()` won't add a redundant slash. I thought you were suggesting simply adding a `/` at the end of the status line setting that was already there.  Pardon me for not following thoroughly.

However,  I also don't use the default status line.  It's really just one of those things that needs to be set by the user to have the best chance of being "correct" (i.e., correct for the user's use case).

In any case, thanks for the issue.  Don't hesitate to raise another one if you find a bug.  Generally, customization issues aren't considered bugs for obvious reasons... everyone has their own opinion on what the defaults should be.
