### ISSUE TITLE
nerdtree directories arrow

### ISSUE THREAD

**Issue by aliev** [scrooloose/nerdtree#472]
is it possible to add the option, which can replace the following symbols?

![](https://dl.dropboxusercontent.com/u/5837324/nerd.png)

I think it would be more comfortable to use the vim-devicons extension: https://github.com/ryanoasis/vim-devicons

**Comment by PickRelated** [comment]
+1 I tried to change lines 386 and 392 in `.vim/bundle/nerdtree/lib/nerdtree/tree_file_node.vim` to other symbols but this makes NERDTree go dumb. It does not react to actions. No help, no expand/collapse, no open files.

**Comment by aliev** [comment]
@PickRelated thats not enough. last 4 commits from my fork (works for me) https://github.com/aliev/nerdtree/commits/master

**Comment by PickRelated** [comment]
@aliev Thanks! I am checking it out! Why don't you make a pull request?

**Comment by aliev** [comment]
@PickRelated we have to put it in a separate option. I'm not good in Vim scripting. as soon as I have some free time, I try to make PR

**Comment by PickRelated** [comment]
@aliev Sorry now I see you made it long ago because code is different now. I had to change it in few more places. And line numbers differ. Guess I will fork some time soon and make a pull request.

**Comment by PickRelated** [comment]
What's said is done. My fork is ready. I will just learn how to contribute correctly in terms of branch management. This will be my first contribution ever. :)

**Comment by PickRelated** [comment]
Done. Waiting for someone to approve this pull request or to critisize my code.

**Comment by aliev** [comment]
@PickRelated amazing! waiting for contributors :)

**Comment by scrooloose** [comment]
Gentlemen, I have merged in @PickRelated's pull req.

Let me know if there are any issues  :)

**Comment by aliev** [comment]
@PickRelated @scrooloose thanks guys!!! :+1:
