### ISSUE TITLE
Moving directories don't refresh buffers

### ISSUE THREAD

**Issue by petersohn** [scrooloose/nerdtree#473]
If I move a file and detects that the file is open in a buffer somewhere, then it asks if I want to replace the buffer with the moved file. However, if I move a directory and there are buffers open for files in the directory structure, NerdTree does not detect it and does not replace buffers. So after moving a directory, I may get "file unavailable" errors from vim.

**Comment by PhilRunninger** [comment]
Confirmed bug.
