### ISSUE TITLE
Can't open file with spaces in mintty

### ISSUE THREAD

**Issue by Pajamaman** [scrooloose/nerdtree#474]
When I try to open a file with the path `/cygdrive/c/www/examples/fullscreen buttons.js` I get this error:

```
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..72..71..<SNR>25_activateFileNode..100..117..167..168..13:
line    1:
E172: Only one file name allowed: edit fullscreen/ buttons.js
Press ENTER or type command to continue
```

I have no other plugins installed. I read something about the `shellslash` setting but apparently my vim doesn't support it. I tried various values for `shellquote` and `shellxquote` without any luck.

I can't reproduce it under Ubuntu 14.04 using so it must be cygwin/mintty/windows specific.

**Comment by jordiFrei** [comment]
I have the same problem. Also in Cygwin minnty. But I think I only have this problem this week when I have reinstalled all my OS

**Comment by hyanliu** [comment]
same here, VIM 8.0 in Cygwin mintty. Any idea or temp workaround? Thanks!

**Comment by lifecrisis** [comment]
**ANNOUNCEMENT**:  Pull request #734 offers a potential fix for this problem. Please checkout the branch there for testing. It must be tested before we merge the changes.

**Comment by ErichDonGubler** [comment]
@hyanliu @jordiFrei @Pajamaman: Does this solve the issue for you? Can we get this confirmed, for Googlers' sakes?

**Comment by lifecrisis** [comment]
@ErichDonGubler, see the pull request mentioned above. A total of 5 related issues were addressed in this PR, all of them had to do with `'shellslash'` not being recognized by the `NERDTreePath` prototype object.

Some of the users in those related issues have confirmed the fix, if that helps.
