### ISSUE TITLE
" Press ? for help should be on bottom

### ISSUE THREAD

**Issue by bogdan** [scrooloose/nerdtree#475]
I don't like the fact that the help banner and the expanded help appear on top. It causes cursor to jump around the buffer.
It is especially bad when tree is long and you somewhere in a middle and just up because you've pressed "?" by accident.

Can we move all that staff to bottom?

**Comment by scrooloose** [comment]
The convention for explorer style plugins is for help to be at the top so this is not something I want to go against.

It might be useful to put this in your vimrc: `let NERDTreeMapHelp = '<f1>'`

This way you will have the `?` back to its normal function.
