### ISSUE TITLE
Invalid range error during tab cycling

### ISSUE THREAD

**Issue by rr-** [scrooloose/nerdtree#476]
```
Error detected while processing function <SNR>34_TabEnterHandler..<SNR>34_RestoreNERDTreeViewIfPossible:
line   20:
E16: Invalid range: 2wincmd w
```

I have no clue where to search for more hints.
It happens all the time, but I'm unable to pinpoint specific circumstances, other than an observation that it seems to happen only when cycling between tabs with unsaved buffers to tabs with no changes and vice versa.

My [.vimrc](https://github.com/rr-/dotfiles/blob/master/mod-vim/.vimrc).

**Comment by rr-** [comment]
This is possibly duplicate of https://github.com/jistr/vim-nerdtree-tabs/issues/68 .

**Comment by PhilRunninger** [comment]
This appears to be a bug in the no-longer-maintained NERDTreeTabs. The function `RestoreNERDTreeViewIfPossible()` is part of that plugin, not NERDTree.
