### ISSUE TITLE
Hi, Is any command I can activate NERDTree's tab ?

### ISSUE THREAD

**Issue by ar1xwe** [scrooloose/nerdtree#479]
I use follow map as suggestion below the github page.
map <...C-n...> :NERDTreeToggle<...CR...>

It toggle the NERDTree map. what If I wanna Activate NERDTree's Tab ?

Such as...
map <...C-n...> :NERDTreeAction<...CR...>

Concept:
IF Exist(...NERDTree:TabHandler...)
    NERDTree:Activate()
ELSE
    NERDTree:Launch()

**Comment by scrooloose** [comment]
I'm not sure I understand, but I think `:NERDTreeFocus` is what you want?
