### ISSUE TITLE
Can't create a folder if there's a file with the same name

### ISSUE THREAD

**Issue by ycavatars** [scrooloose/nerdtree#481]
hi, I'm trying to create a folder but nothing happened if there's a file with the same name. For example, I create a file `hello`, then I try to create `hello/` but nothing is created. Do I miss something? Thanks.

**Comment by Shougo** [comment]
It is feature.
You cannot create the directory.
You must remove "lhello" file before creating.

**Comment by ycavatars** [comment]
Thanks for reply :)
