### ISSUE TITLE
Not able to open file with "$" in filename

### ISSUE THREAD

**Issue by derlaft** [scrooloose/nerdtree#483]
![snapshot20](https://cloud.githubusercontent.com/assets/852606/9883190/5bb0101a-5be1-11e5-8554-74e8d1e39a84.png)

**Comment by netei** [comment]
Works fine for me, however, it doesn't work for me when a filename contains `[`

**Comment by Delapouite** [comment]
I also encounter the same problem while working with files about Angular docs named like `$http.md`

**Comment by dutchgecko** [comment]
See https://github.com/scrooloose/nerdtree/issues/420. There's a workaround but no fix yet.

**Comment by PhilRunninger** [comment]
This should be fixed by PR #649, which has been merged.
