### ISSUE TITLE
how to hidden .pyc files?

### ISSUE THREAD

**Issue by lisper-inmove** [scrooloose/nerdtree#485]
hi, i want to hid the .pyc files, i found NERDTreeMapToggleHidden in some files under lib, but how can i modify any file to reach my goal?

**Comment by aquatix** [comment]
Put this in your ~/.vimrc
let NERDTreeIgnore = ['\.pyc$']

**Comment by cirocosta** [comment]
@aquatix afaik this will make nerdtree completly ignore the file. I think @lisper-inmove wants to be able to see the `.pyc`s when `NERDTreeShowHidden=1`

**Comment by mathstuf** [comment]
You can add `*.pyc` to `wildignore`:

```vim
set wildignore+=*.pyc,*.pyo
```
