### ISSUE TITLE
[Feature Request] Open multiple files at once

### ISSUE THREAD

**Issue by molok** [scrooloose/nerdtree#49]
I'd love to being able to open multiple files at once. This would work like this:
Use Visual Line Mode (Shift+V) to select the files you want to open
Press a key combination
All files selected are opened in background buffers

**Comment by bugeats** [comment]
:horse: yes please

**Comment by eprogramming** [comment]
+1

**Comment by lisandrofernandez** [comment]
+1

**Comment by tankorsmash** [comment]
@scrooloose  I tried a few different places to put the file, even pasting it at the bottom of `fs_menu.vim`, it only lets me use `o` like it was before.

I'll keep at it, but I wanted to thank you for putting the gist up, even if I am a year late.

**Comment by scrooloose** [comment]
I'm away from the computer till Monday night. Currently typing this on my phone (it hurts). Is the code working for you if you change the mapping to something other than 'o'? If so then I guess nerd tree is loading it's own mappings *after* setting the file type

**Comment by rblakeley** [comment]
Nerd Tree tabs?

**Comment by SukumarMehta** [comment]
+1

**Comment by hihihippp** [comment]
+1

**Comment by juegas** [comment]
+1

**Comment by arcadesdude** [comment]
+1 would like this feature as well. Tried putting gist above into:
C:\Users\User\vimfiles\plugged\nerdtree\nerdtree_plugin
in gvim, restarting etc, didn't work for me, the 'o' mapping just toggled back and forth from beg to end cursor position, its default.

**Comment by arcadesdude** [comment]
This might be useful too. Instead of using visual mode to select and open from the tree list view how about using the current directory of nerdtree to pass along the name to the args list and then tab all:

args c:\dir\*
tab all

That should open all files in the directory. It sort of works for me but then the tab bar runs out of room and gvim gives e36 'no more room' and the remaining buffers get put into a single split window. Not so useful.

**Comment by lethargi** [comment]
+1
Didnt try the proposed solution. Will give feedback if I ever get to it. Thanks for the awesome plugin!

**Comment by gabrielps** [comment]
+1

**Comment by mbendaniel-t** [comment]
+1

**Comment by Melkster** [comment]
+1

**Comment by PhilRunninger** [comment]
The problem with the [gist above](https://gist.github.com/scrooloose/5eedbf80a4c62d01d25c) is that it executes while in the `[No Name]` buffer, so the mapping is not available where it's needed. Removing `<buffer>` (which is not the solution) reveals other error messages that may be a result of the age of the code vs. the current version of NERDTree.

**Comment by f1nwe** [comment]
+1

**Comment by PhilRunninger** [comment]
I've updated the gist to work with the current version of NERDTree. You can find it here: https://gist.github.com/PhilRunninger/99f0c78e48de42bf2010f30d983ff61f. Just place this file in your `~/.vim/nerdtree_plugin` folder, and you'll be good to go. I'd like to get some feedback on this, and then we can decide whether (and how) to include it in the base NERDTree code.

Thanks!

**Comment by PhilRunninger** [comment]
I'm going to close this issue, since the gist is available as a NERDTree plugin.

**Comment by elig0n** [comment]
Thanks for this!
I found I need to put the gist in my plugins directory's nerdtree/nerdtree_plugin/ which already existed.
By all means I think such a functionality should be incorporated to the base code with more options (like open in multiple tabs).

**Comment by PhilRunninger** [comment]
@elig0n , If you put it there, it may be deleted when you up date NERDTree or will interfere with the update. Instead, try putting it in the `~/.vim/nerdtree_plugin` folder, which you probably will need to create.

**Comment by PhilRunninger** [comment]
@elig0n, @jimafisk, I don't know if you get @-mention notifications directly from the gist, so I'm tagging you here. I've fixed the issue that required you to put the gist in `~/.vim/bundle/nerdtree/nerdtree_plugin/`. See https://gist.github.com/PhilRunninger/99f0c78e48de42bf2010f30d983ff61f#gistcomment-2890723.

**Comment by jimafisk** [comment]
For folks who are interested in opening in multiple tabs instead of splits, in @PhilRunninger's gist above just change the `h` to a `t` on line 16:
```
call node.open({'where':'t', 'stay':1, 'keepopen':1})
```

**Comment by PhilRunninger** [comment]
I've updated my [gist](https://gist.github.com/PhilRunninger/99f0c78e48de42bf2010f30d983ff61f) to include mappings for opening into split or separate tabs.
