### ISSUE TITLE
how to change the width of the plugin

### ISSUE THREAD

**Issue by wsdjeg** [scrooloose/nerdtree#491]
i want this function 
<space> mapto change the plugin width +=50
and when i reopen the plugin width change to 30

**Comment by wsdjeg** [comment]
i have add the func to my vimrc
alse used with 'A' in NERDTree

**Comment by ilaipi** [comment]
@wsdjeg   can u show your func? thanks

**Comment by wsdjeg** [comment]
Currently, I am using defx.nvim.

**Comment by ilaipi** [comment]
Wow. I will try your SpaceVim!
