### ISSUE TITLE
Rendering error while in Tmux

### ISSUE THREAD

**Issue by datapimp** [scrooloose/nerdtree#497]
I'm experiencing some weird behavior with NERDTree , only in a tmux session.

I have made sure that the character encoding in vim, in my shell, and in tmux are all utf-8

![what could cause this?](https://photos-5.dropbox.com/t/2/AAA0Nlznt9vO1M_d05rwSlO7CwJg9CEIs2K7TqJcGO9OBQ/12/586301/png/32x32/1/1444453200/0/2/Screenshot%202015-10-09%2022.55.04.png/CL3kIyABIAIgAyAGIAcoASgCKAc/yUwdr-zgV246SwuzBRr0eCgoYTEhm5OORCM-ra-QUhY?size=1024x768&size_mode=2)

this happens whenevr i open nertdtree or scroll a buffer.

any suggestions on how to find the root cause?

**Comment by scrooloose** [comment]
Hi, can you repost this screenshot? It is now missing.

**Comment by datapimp** [comment]
<img width="462" alt="screenshot 2015-10-09 22 55 04" src="https://cloud.githubusercontent.com/assets/42960/11432803/dd1e6d00-947a-11e5-9b72-b5edb950a1c7.png">

Here is what it was.  

This problem seemed to have cleared itself up somehow.   I was desperate trying to think about what could be causing it.

**Comment by michaeljs1990** [comment]
I am seeing the same issue now. @datapimp do you mind posting your tmux.conf file?

**Comment by michaeljs1990** [comment]
the following in your `~/.tmux.conf` resolved the issue for me.

```
set -g default-terminal 'screen-256color'
setw -g utf8 on
set -g status-utf8 on
```

**Comment by PhilRunninger** [comment]
Looks like we can close this one.
