### ISSUE TITLE
Errors while opening NERDTree in vim, but works fine after ENTER

### ISSUE THREAD

**Issue by eshansingh** [scrooloose/nerdtree#498]
I get the following error after doing `:NERDTree`:

`
 Error detected while processing /Users/eshan/.vim/bundle/nerdtree/syntax/nerdtree.vim:
line   26:
E121: Undefined variable: g:NERDTreeDirArrowCollapsible
E116: Invalid arguments for function escape(g:NERDTreeDirArrowCollapsible, '~').'# containedin=NERDTreeDir,NERDTreeFile'
E15: Invalid expression: 'syn match NERDTreeClosable #'.escape(g:NERDTreeDirArrowCollapsible, '~').'# containedin=NERDTreeDir,NERDTreeFile'
`

I'm not sure what to do here, can anyone help. If it matters, I installed the NERDTree and the nerdtree-git plugins via Vundle.

**Comment by scrooloose** [comment]
Hi, is this still happening? If so, can you show me the output of `:scriptnames` just after the error occurs?

**Comment by eshansingh** [comment]
No, it turns out defining all thse variables worked. I should have closed this issue, sorry for my naïvety with GitHub.
