### ISSUE TITLE
NERDTreeDirArrows make NT unusable

### ISSUE THREAD

**Issue by matthiasbeyer** [scrooloose/nerdtree#499]
```
let g:NERDTreeDirArrows = 1
let g:NERDTreeDirArrowExpandable = '>'
let g:NERDTreeDirArrowCollapsible = '_'
```

This makes nerdtree unusable for me. I can open one file out of 20 or something, all others just won't work.

**Comment by martin-svk** [comment]
+1

**Comment by scrooloose** [comment]
Hey guys, this should be fixed now.

I have just removed the NERDTreeDirArrows option and fixed the bug that was causing your issues... I just noticed that the highlighting is completely screwed if you use `>` to as the expandable symbol though... I'll have to look more into this.
