### ISSUE TITLE
Do not open nerdtree for certain filetypes

### ISSUE THREAD

**Issue by matthiasbeyer** [scrooloose/nerdtree#500]
Is there such an option and if not, how to script this in vimscript?

I'd like to keep nerdtree closed for git commits, mails and (for example) also `.ical` files. How to do this?

**Comment by scrooloose** [comment]
I assume you have have an autocmd opening nerdtree on startup?

I would probably stick this in your vimrc:

```
"open a nerdtree when vim starts
autocmd vimenter * call s:CheckToOpenNERDTree()

function! s:CheckToOpenNERDTree() abort

    "dont open a tree for gitcommits
    if &ft == 'gitcommit'
        return
    endif

    "dont open a tree for .ical files
    if expand("%:t") =~ '\.ical$'
        return
    endif

    NERDTree
endfunction

```

Its pretty low tech, but easy to extend/maintain.
