### ISSUE TITLE
Support GNU readline keyboard shortcuts in file operations

### ISSUE THREAD

**Issue by rr-** [scrooloose/nerdtree#504]
When I do operations on files (using `mm`, `ma` etc.), I'd like to use GNU readline's hotkeys such as

- <kbd>Alt</kbd>+<kbd>B</kbd> - navigate to previous word
- <kbd>Alt</kbd>+<kbd>F</kbd> - navigate to next word
- <kbd>Ctrl</kbd>+<kbd>W</kbd> - delete last word

etc. These proved to be really handy in other applications, and they're supported pretty much everywhere: zsh, bash, vifm, vim's ctrl+p (partially), vimperator (partially), most of my interactive scripts (even though they're written in Python and I didn't try to make them support such hotkeys)...

**Comment by rr-** [comment]
I found a solution which is explained in the linked issue, but I copy paste it here just in case.

>Looks like this can be solved through `.vimrc` alone:
>
>     " make meta key work (this might be need to be specialized for other terms)
>     " urxvt
>     execute "set <M-b>=\eb"
>     execute "set <M-f>=\ef"

>     cnoremap <C-a> <Home>
>     cnoremap <C-e> <End>
>     cnoremap <C-p> <Up>
>     cnoremap <C-n> <Down>
>     cnoremap <C-b> <Left>
>     cnoremap <C-f> <Right>
>     cnoremap <M-b> <S-Left>
>     cnoremap <M-f> <S-Right>
>
>(...)
>
>Answers on SO that helped me to resolve the issue:
>
>- http://stackoverflow.com/questions/6920943/navigating-in-vims-command-mode
>- http://stackoverflow.com/questions/7501092/can-i-map-alt-key-in-vim/27206531#27206531

**Comment by brianpeiris** [comment]
I'd recommend the readline.vim plugin for this: https://github.com/ryvnf/readline.vim
