### ISSUE TITLE
issue in Windows gVim

### ISSUE THREAD

**Issue by fsw0422** [scrooloose/nerdtree#505]
nerdtree\plugin\NERD_tree.vim
E114: in line #71 missing quotation mark "??)
wrong argument is passed to <SNR> 17_initVariable
E114: in line #72  missing quotation mark "??)
wrong argument is passed to <SNR> 17_initVariable

having problems when firing up gVim in Windows 7
but seems it's not firing this issue on Ubuntu 14.04

**Comment by drneverend** [comment]
I see it, too.

**Comment by scrooloose** [comment]
Hey guys, is this still present on the latest master?

Note: I have just removed the old style UI - so things will look a little different.

**Comment by drneverend** [comment]
Martin, it is fixed at my side. Thanks for your work!






At 2015-11-26 07:49:15, "Martin Grenfell" <notifications@github.com> wrote:


Hey guys, is this still present on the latest master?

Note: I have just removed the old style UI - so things will look a little different.
