### ISSUE TITLE
leaver nerdtree buffer need 1-2 secconds.

### ISSUE THREAD

**Issue by wsdjeg** [scrooloose/nerdtree#506]
with this change 
```
-    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
+    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

```
i find if i use c-w c-h to leave nerdtree buffer,it will need more time than beffore

**Comment by scrooloose** [comment]
Is this still an issue? I can't reproduce it here :-/

**Comment by wsdjeg** [comment]
with mini vimrc test,this issue has gone.sorry,maybe it is due to my autocmd filetype init,so close it
