### ISSUE TITLE
Error detected while processing function nerdtree#ui_glue#invokedKeyMap..74..63

### ISSUE THREAD

**Issue by sensorario** [scrooloose/nerdtree#507]
I've got this error message pressing "e"

```
Error detected while processing function nerdtree#ui_glue#invokedKeyMap..74..63..<SNR>38_openExplorer..148..146..169..171:
line   13:
E716: Key not present in Dictionary: CreateWindow
Press ENTER or type command to continue
```

**Comment by eshansingh** [comment]
Hmm... `:call nerdtree#ui_glue#invokedKeyMap()` reports that the function doesn't exist. However the source clearly has it. I'll have a look, and see if I can notify @scrooloose of the problem.

**Comment by eshansingh** [comment]
The function seems unnecessary because commenting it out makes no difference whatsoever. This might be a temporary solution to your problem, but I'm not sure of the root cause. Try updating NERDTree, or reninstall it as a last resort.

**Comment by wsdjeg** [comment]
also 'i' on a directory show this error
![2015-11-21 21-28-23](https://cloud.githubusercontent.com/assets/13142418/11318688/7429e338-9097-11e5-9623-4852277f6933.png)

**Comment by scrooloose** [comment]
Thanks for the report guys. Let me know if there are any more problems with this :)
