### ISSUE TITLE
autoclose nerdtree not working on latest

### ISSUE THREAD

**Issue by senorsmile** [scrooloose/nerdtree#510]
The following works up to tag 5.0.0:

```
"autoclose nerdtree if last
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
```

However, on the latest commit, dd754c7bc64f8802ab6ff660776e1dee0e0e2761 at the time of writing, that has no effect.

**Comment by scrooloose** [comment]
Hi, use this code now:

`autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif`

Let me know if there are any issues :)

**Comment by senorsmile** [comment]
Thanks!
