### ISSUE TITLE
Cleanup traces of g:NERDTreeDirArrows option

### ISSUE THREAD

**Issue by Coacher** [scrooloose/nerdtree#515]
[This commit](https://github.com/scrooloose/nerdtree/commit/677a83b2b63fda1c52205acd39973fe1b44e8b54) renders NERDTree unusable, because there are still [references to g:NERDTreeDirArrows in the code](https://github.com/scrooloose/nerdtree/search?utf8=%E2%9C%93&q=NERDTreeDirArrows&type=Code).

Please fix.

**Comment by scrooloose** [comment]
Heh, shouldn't have pushed at midnight. Cheers

**Comment by Coacher** [comment]
Thank you.
