### ISSUE TITLE
ClearAllBookmarks does not refresh

### ISSUE THREAD

**Issue by sensorario** [scrooloose/nerdtree#516]
After ClearAllBookmarks command, the view is not refreshed and a reload is mandatory to se new tree status ...

**Comment by lifecrisis** [comment]
Confirmed this bug on my installation.

**Comment by PhilRunninger** [comment]
Not a bug on Mac. I'll check Windows tonight. This bug may have been fixed since last June.

**Comment by PhilRunninger** [comment]
This appears to be working correctly now. I'm going to go ahead and close this one.

**Comment by sensorario** [comment]
👍
