### ISSUE TITLE
How to return pipes, dashes and ` back?

### ISSUE THREAD

**Issue by alexbel** [scrooloose/nerdtree#518]
I've been using `g:NERDTreeDirArrows`, but it's gone and `g:NERDTreeDirArrowExpandable` and 
`g:NERDTreeDirArrowCollapsible` can change only the arrows.

The old look:
![Old](https://ipfs.pics/ipfs/QmQmgdh9cbD2Xok51YSmr88PbZeAkyFLPb2cztET6kUeW5)

**Comment by dodev** [comment]
+1 I miss the pipes, too.

**Comment by PhilRunninger** [comment]
The new look is here to stay. Sorry.
