### ISSUE TITLE
`NERDTreeCascadeOpenSingleChildDir = 0` not working

### ISSUE THREAD

**Issue by kassio** [scrooloose/nerdtree#523]
I'm not being able to come back to the old style of single child dir folders. 
I set the `let NERDTreeCascadeOpenSingleChildDir=0`, however it seems that it didn't work:

![nerdtree](https://cloud.githubusercontent.com/assets/120483/11716733/16f3e8da-9f33-11e5-920f-60b3ee420411.gif)

**Comment by Lebyrt** [comment]
As far as I can see, the option does what is says.

If I set `let NERDTreeCascadeOpenSingleChildDir=1` and try to open `three`, the NERDTree will open `three`, `five` and **will** show contents of the `five`.

If I set `let NERDTreeCascadeOpenSingleChildDir=0` and try to open `three`, the NERDTree will open
`three`, `five` and **won't** show contents of the `five`.

Although, it doesn't do what I expect it to do. No matter which value the option has, the NERDTree shows `three` and `five` in one line. Which is not what I want.

I suggest you could add additional option, e.g. `NERDTreeCascadeShowSingleChildDir` which would do the following.

If I set `let NERDTreeCascadeShowSingleChildDir=1` and try to open `three`, the NERDTree will show `three` and `five` in one line, **like it does now**:
```
three/five/
```

If I set `let NERDTreeCascadeShowSingleChildDir=0` and try to open `three`, the NERDTree will show `three` and `five` in separate lines, **like it used to do**:
```
three/
    five/
```

**Comment by kassio** [comment]
But this is the thing, I set `let NERDTreeCascadeShowSingleChildDir=0` and the nerdtree still openning the single child together with its parent: 
```
three/five
```
and not
```
three/
   /five
```

**Comment by Lebyrt** [comment]
Oh, I guess, I've just added a misleading comment. I'm sorry. I'll try to clear things up. :)

First of all, I'm just a user and I miss the old style too.

Second, there are no such option as `NERDTreeCascadeShowSingleChildDir` yet. It's just my suggestion for the developers. I hope they will consider it.

I'm going to edit my previous message, to make it more clear.

**Comment by PhilRunninger** [comment]
I'm going to close this issue. That option (and the newer one like it: `NERDTreeCascadeSingleChildDir`) are behaving differently now, maybe as a result of the newer option. There needs to be some work to simplify these two options so they work better, so I'm open to a new issue being created for that effort.
