### ISSUE TITLE
NERDTreeToggle causes window to move and/or resize

### ISSUE THREAD

**Issue by meldavis** [scrooloose/nerdtree#524]
On Windows 10, if gvim is docked to the edge of the screen, NERDTreeToggle causes the windows to move and/or resize: 

Before Toggling NERDTree:

![beforenerdtreetoggle](https://cloud.githubusercontent.com/assets/9271152/11719898/dec3bcd6-9f2a-11e5-9665-2c799efa2250.jpg)

After Toggling NERDTree:

![afternerdtreetoggle](https://cloud.githubusercontent.com/assets/9271152/11719892/d86b5704-9f2a-11e5-9a32-4741f3d23466.jpg)

**Comment by PhilRunninger** [comment]
See #513. It's happening because you're using scrollbars in vim.
