### ISSUE TITLE
default view when opening directory from command line

### ISSUE THREAD

**Issue by jayceekay** [scrooloose/nerdtree#525]
hi, not sure if this question is best asked here in the nerdtree repo or somewhere else, but i was curious if it would be possible to open a project dir from the command line, ala `vim .` (`mvim .` in my case), and have the default view look like this upon open:

<img width="1550" alt="screen shot 2015-12-13 at 10 48 09 am" src="https://cloud.githubusercontent.com/assets/1119866/11767780/3ca988cc-a187-11e5-9072-d265bec2da21.png">

what shows after `mvim .` right now is this:

<img width="1550" alt="screen shot 2015-12-13 at 10 50 55 am" src="https://cloud.githubusercontent.com/assets/1119866/11767790/7fd7d220-a187-11e5-8690-14e8be43ddad.png">

**Comment by PhilRunninger** [comment]
Add this line to your vimrc:

```
autocmd VimEnter * NERDTree
```
Then launch vim without a path: `vim`

**Comment by jayceekay** [comment]
i think i am getting closer...

<img width="1550" alt="screen shot 2015-12-14 at 11 16 03 am" src="https://cloud.githubusercontent.com/assets/1119866/11786355/2dbc7c5c-a254-11e5-9bae-53f2c2e49ca8.png">

just to clarify, i'm doing these steps:
1. `cd ~/dev/projectdir`
2. `mvim .`

**Comment by PhilRunninger** [comment]
Leave the `.` off the nvim command line. The path is causing the NERDTree window on the right to appear. Without it, you'll see NERDTree on the left and an empty buffer on the right.

**Comment by jayceekay** [comment]
great, that works, thanks!

i have another general vim question, when i launch `mvim` it seems to be executing a script i was debugging in an earlier session. completely quitting macvim and launch `mvim` from different, arbitrary project dirs still does the same. any ideas?
