### ISSUE TITLE
Cascading directories sometimes jumps to the wrong directory

### ISSUE THREAD

**Issue by matt-gardner** [scrooloose/nerdtree#529]
I've found a (rare) bug in the implementation of cascading directories.  When there's a directory lower in the NERDTree with the same name as the directory that just got cascaded, the cursor will jump there after cascading.  For example, consider the following tree:

> test/
> 
> > other/
> > src/
> > 
> > > bad/
> 
> test2/
> 
> > other/
> > src/

If you make this tree in some temporary directory, open vim (and NERDTree), then expand both `test/` and `test2/`, _then_ you expand `test/src/`, the directory correctly cascades, showing `src/bad/` in one line, but the cursor jumps to `test2/src/`.  The cursor does not jump if `test2/` has not been opened.

Hopefully this makes sense.

**Comment by PhilRunninger** [comment]
Confirmed.

**Comment by lifecrisis** [comment]
@matt-gardner, finally got around to fixing this.  Let me know if you get a chance to test the change in #882.

**Comment by matt-gardner** [comment]
Nice!  I just tested it, and it fixes the issue for me.  I'll keep using that commit for a bit and let you know if I run into any other problems.
