### ISSUE TITLE
Single-click to open file/dir not working

### ISSUE THREAD

**Issue by fungl164** [scrooloose/nerdtree#531]
Issue:
- Single-clicks on any file or directory has no effect.

Expect:
- File to open in window
- Directory to expand  

Using:
- NERDTreeMouseMode=2 (or 3) 
- OSX El Capitan
- NeoVim v0.1.2-181-g3b23d73

Any help would be greatly appreciated.  Many Thnxs!!

**Comment by fuelen** [comment]
click twice

**Comment by fuelen** [comment]
click twice.
single click just moves the cursor

**Comment by fungl164** [comment]
Thanks @fuelen.  In Vim, <code>NERDTreeMouseMode=2</code> opens the file or expands tree when using with single-clicks.  This setting doesn't seem to work with Neovim.  Any suggestions? Thnxs!

**Comment by fuelen** [comment]
@fungl164 it works for me.
nvim-qt.

**Comment by fungl164** [comment]
@fuelen thnxs.  For me it doesn't. : /
nvim terminal - OSX (El Capitan).

**Comment by louwers** [comment]
Perhaps try iTerm2?

**Comment by ericson-cepeda** [comment]
"`let g:NERDTreeMouseMode = 3` in vimrc to get single-click behavior"

**Reference**: https://github.com/carlhuda/janus/issues/57

**Comment by ericson-cepeda** [comment]
`let g:NERDTreeMouseMode = 3` to get single-click behaviour. It works for me on Ubuntu and OSX (iTerm 2)

**Reference**: https://github.com/carlhuda/janus/issues/57

**Comment by PhilRunninger** [comment]
Is this still an issue? If so I'll need to install Neovim again to diagnose it.

**Comment by fungl164** [comment]
Not an issue anymore on neovim v0.2.2 + iTerm 3.1.5 + g:NERDTreeMouseMode = 3.

**Comment by tomtt** [comment]
For somebody else coming here like me with nerdtree mouse not working on iTerm2: my fix was to "Enable mouse reporting" in the terminal section of my profile preferences.
