### ISSUE TITLE
Cannot see files (with numbers ? with spaces ?)

### ISSUE THREAD

**Issue by guillaumewuip** [scrooloose/nerdtree#535]
Hi !

I'm a big fan of nerdtree and I've ran into a strange bug. I cannot see all files in some folders.
Usually I can only see the first.

I may be because there is numbers or spaces in the file name or in one of the parent directory.

Example : same directory right and left but nerdtree sees only the first file.
![capture d ecran 2016-01-19 a 07 29 21](https://cloud.githubusercontent.com/assets/748586/12411471/578bc1fe-be7f-11e5-97c7-2a1c99b0e935.png)

Example 2 : same directory right and left. No spaces in file names, no spaces in current dir name. But spaces in a parent directory.
![capture d ecran 2016-01-19 a 07 42 30](https://cloud.githubusercontent.com/assets/748586/12411579/46afc17c-be80-11e5-961d-378643642f0a.png)

I'm using nerdtree on tag `5.0.0` (same behavior if I checkout the [last commit](https://github.com/scrooloose/nerdtree/commit/4ebbb533c3faf2c480211db2b547972bb3b60f2b)).
Same behavior whether I'm in tmux or not.
OSX 10.11.2, bash, Terminal.app.

**Comment by PhilRunninger** [comment]
@guillaumewuip, I cannot reproduce this issue on `5.0.0` or the latest commit. Can you confirm this issue still exists or close it?

**Comment by guillaumewuip** [comment]
Hello @PhilRunninger. I did not encounter the problem since a few months. We can close :)
