### ISSUE TITLE
A setting to auto-close the bookmarks when selecting a bookmark

### ISSUE THREAD

**Issue by nedbat** [scrooloose/nerdtree#540]
Is this possible already, but I've overlooked it? I'd like to open bookmarks with "B", navigate to a bookmark, hit return to open it, and have the bookmarks close automatically without having to use "B" again.

**Comment by PhilRunninger** [comment]
Proposal: What if we redefined the NERDTreeQuitOnOpen setting, changing it from boolean to integer? `0` and `1` still serve the same purpose, and `2` could be "close bookmark list on open."
