### ISSUE TITLE
Opening dirs in new tab error: Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..73[33]..72[3]..<SNR>41_openInNewTab

### ISSUE THREAD

**Issue by srustamo** [scrooloose/nerdtree#541]
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 14 2016 11:37:19) on OSX

**Comment by charlydagos** [comment]
I got a similar error when I set up my backup and directory commands in my `~/.vimrc` file like

    set directory=~/.vim/backup
    set backupdir=~/.vim/backup   " keep swap files here

But that directory didn't exist. Creating the directory was enough to get that working :)

**Comment by PhilRunninger** [comment]
@srustamo, can you include the steps needed to reproduce this issue?

**Comment by srustamo** [comment]
It's been a year since, I can't remember the context. I suppose this error was related to `t` command while cursor is on a dir node. I'm currently on VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 30 2017 15:13:24). Pressing `t` similar to above does not raise this error.

**Comment by PhilRunninger** [comment]
I'll go ahead and close this issue then. Thanks for your quick reply.
