### ISSUE TITLE
installation proccess incomplete

### ISSUE THREAD

**Issue by dirad** [scrooloose/nerdtree#543]
Hey there,

Following the installation in the README : 
```
mkdir ~/.vim/
mkdir ~/.vim/bundle/
cd ~/.vim/bundle/
git clone repolink
```

now running vim, and trying
`` :Helptags -> E492: Not an editor command: Helptags ``                                             
or
``:help NERD_tree.txt -> E149 Sorry, no help for NERD_tree.txt``

i can guess im doing something wrong - but what?

thanks.

**Comment by vpedabal** [comment]
I am also facing the same issue. I am using vim 7.4 on sles12

**Comment by HangingClowns** [comment]
dittos... what's the dealio? I'm on Redhat 7, vim 7.4.160...

**Comment by PhilRunninger** [comment]
The command is `:helptags`, all lowercase. I corrected the README.
