### ISSUE TITLE
A bug with NERDTreeCascadeOpenSingleChildDir

### ISSUE THREAD

**Issue by mmaxs** [scrooloose/nerdtree#547]
Steps to reproduce:
- create the folder 'A' in some directory
- create the subfolder 'B' in the folder 'A'
- create the file 'file.txt' in the folder 'B'
- open 'file.txt' from the GUI file manager with Vim
- in Vim open NERDTree, you should see '/some directory/A/B/' as a tree root
- select '.. (up dir)'
- then select '.. (up dir)' one more time
- now try to open the 'A/B/' node in NERDTree

It appears that the node cannot be open again from now.

**Comment by juanibiapina** [comment]
Very annoying. I'm trying to disable cascade altogether, but it seems there is no way.

**Comment by mmaxs** [comment]
Now it is needed to press 'C' - (change tree root to the selected dir) + Enter to be able opening such a directory.

**Comment by bcoady** [comment]
I am having the same issue. I went back to NerdTree 4.2 for now which works fine.

**Comment by hh123okbb** [comment]
Click "x" key map(close parent of node) on the line of 'file.txt' will also reproduce this bug @scrooloose .

**Comment by hh123okbb** [comment]
Add a gif
![tty](https://cloud.githubusercontent.com/assets/3201938/15447149/0103b03e-1f6a-11e6-80e5-d5fccb390465.gif)

**Comment by PhilRunninger** [comment]
@juanibiapina , does your PR #558 solve this issue?

**Comment by juanibiapina** [comment]
It doesn't sove the issue at all. It only adds the option to deactivate the feature that has the bug.

**Comment by qifei9** [comment]
I have the same issue.

**Comment by lifecrisis** [comment]
This is a confirmed bug. The same as in issue #526. A fix is in progress.

**Comment by lifecrisis** [comment]
**ANNOUNCEMENT:** Everyone experiencing this bug can try the fix in pull request #720. It should repair this problem without any side effects. The code is currently under review.

**Comment by hookdump** [comment]
PSA: You can set this config to disable this feature too:

`let NERDTreeCascadeSingleChildDir=0`
