### ISSUE TITLE
Open dir in new tab needs refresh

### ISSUE THREAD

**Issue by alambike** [scrooloose/nerdtree#549]
If I open dir in a new tab, with **t** key, it opens a cloned view of the tree, not a new tree focused in selected directory, and this tree isn't usable. After press **R** key to refresh view, the tree appears focused in dir, and working as expected. 
However, open dir in new tab keeping focus in current (**T** key) works fine.
- Latest Nerdtree 5.0 installed with vundle
- VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47), from ubuntu 14.04 package

**Comment by h3110w0r1d** [comment]
same problem

**Comment by lifecrisis** [comment]
This bug has been confirmed.

**Comment by lifecrisis** [comment]
**Announcement**:  All involved should check out the PR #759 and make sure it works as intended.  Confirmation will speed up a merge.
