### ISSUE TITLE
FEATURE REQUEST: Open file in tree in new tab when return

### ISSUE THREAD

**Issue by ayyobro** [scrooloose/nerdtree#551]
When we view our tree in the sidebar, I would like to create the functionality to open the file i hit "enter" on in a new tab. Does this exist? If not, how could I achieve this?

**Comment by devm33** [comment]
You can use `t` when over the file to open in a new tab and move focus to it. Or you can use `T` to open in a new tab without focus.

**Comment by sam3k** [comment]
I 100% agree that the default behavior for when you press Enter should be to open the file in a new tab. 

I've noticed this issue has been brought up before here https://github.com/scrooloose/nerdtree/issues/18 but was closed without giving a reason. 

Maybe there is a valid reason for it? Not sure. Can't think of an IDE that doesn't do this behavior by default. It is good UX. If you don't want to set it by default, it should be an option to allow to press "Enter" and open in a new tab IF it is a file.

**Comment by lifecrisis** [comment]
@sam3k,

I'm going to mark this as an accepted feature request, even though I disagree with the design idea.  I don't think this should be a default, but a feature should exist that could make this possible. Prompting from another collaborator made me see this as somewhat acceptable.

**Comment by PhilRunninger** [comment]
@ayyobro @sam3k , Give the reference PR a try, and let me know if it meets your needs. Thanks.
