### ISSUE TITLE
possibility to create own list

### ISSUE THREAD

**Issue by divramod** [scrooloose/nerdtree#554]
Hey,

i created an array with strings that represent filepathes in a vim function.
now i like to open NERDTree, showing me only the files of that list. (kind of a filter)

Is that somehow possible?

**Comment by lifecrisis** [comment]
The NERDTree is a poor choice as an environment for this kind of functionality. You should investigate the quickfix list feature in Vim. There are functions that allow you to place files in the quickfix list or location list as you please. It's a much better option as it ships with Vim by default.
