### ISSUE TITLE
sourcing .vimrc file put square brackets around file icons

### ISSUE THREAD

**Issue by tnguyen14** [scrooloose/nerdtree#557]
Whenever I try to source `~/.vimrc` file when NERDTree is open, I get square brackets around the file icons like so:
<img width="186" alt="screen shot 2016-03-03 at 11 07 51 am" src="https://cloud.githubusercontent.com/assets/1652595/13500790/09a4c37a-e132-11e5-9f6a-73206d68b910.png">

Is there a way to get rid of them? Is it a bug?

Tri

**Comment by louwers** [comment]
Has nothing to do with NERDTree.
You have [this](https://github.com/ryanoasis/vim-devicons) installed.

https://github.com/tnguyen14/dotfiles/blob/master/home/.vimrc

**Comment by tnguyen14** [comment]
Thanks. I'll file an issue with the devicons repository.
