### ISSUE TITLE
mouse not work when NERDTreeWinPos="right" 

### ISSUE THREAD

**Issue by idning** [scrooloose/nerdtree#560]
I'm using NERDTree under mac/iTerm2

basic config::

```
let g:NERDTreeWinPos = "right"  
set mouse=a
set ttymouse=xterm2
```

if I comment the `g:NERDTreeWinPos = "right"` line, every thing is ok.

but when I put NERDTree window in right, mouse just not work, when I double click a filename, the main code window just enter VISUAL mode.

**Comment by PhilRunninger** [comment]
@idning, Can you confirm this is still happening (and provide more information about how to reproduce it), or close this issue? I'm not able to recreate this issue.

**Comment by idning** [comment]
It have been some time I did not try this setup, let me close it:)
