### ISSUE TITLE
How can I open Nerdtree automaticlly when no filename but not open with filename 

### ISSUE THREAD

**Issue by youthy** [scrooloose/nerdtree#561]
I mean 
vim  ->  open Nerdtree automaticlly
vim filename -> not open

I know auto-open cmd is `autocmd VimEnter * NERDTree`

**Comment by apbarrero** [comment]
`$ vim <dir>`

**Comment by youthy** [comment]
I got it,thks

**Comment by youthy** [comment]
when I use `vim .` it open nerdtree but when I select one file to open, the nerdtree closed... I have to type`:Nerdtree` to open it again...

**Comment by apbarrero** [comment]
I don't know if there's a way to tell NERDTree to open file in a new window.

A tricky way to keep NERDTree opened would be to run `:vsp` before selecting file to open, so you keep one window with NERDTree and the other with the new buffer for the selected file.
