### ISSUE TITLE
how can i exit menu without using esc?

### ISSUE THREAD

**Issue by dragonxlwang** [scrooloose/nerdtree#562]
i tried to search doc for an answer... sorry if duplicated

**Comment by dragonxlwang** [comment]
maybe just to hit (l)ist as it harmlessly exit?

**Comment by lifecrisis** [comment]
You may also exit the file system menu by pressing `CTRL-C`. This is generally more convenient.

**Comment by ghomem** [comment]
It is possible to remap the exist function to another key, such as "q" ? I looked in the documents and did not find an option.

Furthermore, it is not indicated in the initial menu message that we need to use control+C:

```
NERDTree Menu. Use j/k/enter, or the shortcuts indicated
```

**Comment by ghomem** [comment]
After much grepping, could it be that this is hardcoded unlike MenuUp and MenuDown?

https://github.com/preservim/nerdtree/blob/master/lib/nerdtree/menu_controller.vim#L99

![Screenshot_20241010_101753](https://github.com/user-attachments/assets/e25f9a52-abbb-42b8-a41f-7eef10144e5b)

Would you be able to expose something like `g:NERDTreeMenuQuit` ?

**Comment by ghomem** [comment]
I made this local change:

https://github.com/preservim/nerdtree/pull/1433/files

and then set:

```
let NERDTreeMenuQuit='q'
```

on my .vimrc and it works as expected.

Does the PR make sense? (I never touched vim plugins before...).

**Comment by ghomem** [comment]
@rzvxa not sure if I should have attached this PR to a closed issue or if I should create a new one. Please advise and thanks for NERDTree :-)
