### ISSUE TITLE
Number column disappears when leave the nerdtree panel using wincmd

### ISSUE THREAD

**Issue by hatelove85911** [scrooloose/nerdtree#563]
I've set nerdtree to show numbers in vimrc:
`let g:NERDTreeShowLineNumbers=1
`

the numbers column is shown when nerdtree is open. but if I leave the nerdtree window using wincmd, the number column disappears. it won't show automatically even if I navigate back to the nerdtree window.

**Comment by PhilRunninger** [comment]
Is there anything else in your .vimrc related to line numbers? I can't reproduce this issue.
