### ISSUE TITLE
Go to previous window/split on NERDTree quit not working (or not implemented)

### ISSUE THREAD

**Issue by anemator** [scrooloose/nerdtree#564]

**Comment by anemator** [comment]
Just noticed this only happens if its the same buffer that's split.

**Comment by lifecrisis** [comment]
This is still a bug. Thanks for reporting this.

**Comment by lifecrisis** [comment]
Looks like this was fixed by PR #801.  Re-open if you still have a problem with this.  Note that the solution from that PR doesn't work on older versions of Vim (any later version ~7.4+ is fine).
