### ISSUE TITLE
Error on opening new tab with 't' on NERDTree Bookmarks

### ISSUE THREAD

**Issue by aRkadeFR** [scrooloose/nerdtree#565]
Hello,

I just upgraded my NERDTree submodule to `4ebbb53` origin/master. And I can't open my Bookmark anymore with the letter 't'.

This is the "stacktrace":

```
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..73..72..<SNR>45_openInNewTab..76..92..97..86:
line    1:
E716: Key not present in Dictionary: root.AbsoluteTreeRoot() : a:nerdtree.root
E15: Invalid expression: a:searchFromAbsoluteRoot ? a:nerdtree.root.AbsoluteTreeRoot() : a:nerdtree.root
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..73..72..<SNR>45_openInNewTab..76..92:
line    4:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..73..72:
line    3:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..73:
line   43:
E171: Missing :endif
```

**Comment by drewbailey** [comment]
Having this issue as well, were you able to resolve?

**Comment by aRkadeFR** [comment]
I don't have the issue anymore, I upgraded to neovim + latest NERDTree (maybe the same as describe in this ticket).

**Comment by PhilRunninger** [comment]
I'm not getting errors, but `t` is opening the bookmarked file in the same window as NERDTree, and not creating a new tab.

**Comment by osenvosem** [comment]
Having the same issue. MacVim 8.0.771 (135) + latest NERDTree

**Comment by lifecrisis** [comment]
Confirmed this bug on Windows 10.

**Comment by wesleytodd** [comment]
Having the same error on master, if I checkout what looks like the last major version tag, `5.0.0`, the issue is resolved.  Not sure if that helps for a fix since it was from >2 years ago, but if anyone else just wants a working state, that seems to do it.

**Comment by lifecrisis** [comment]
**Announcement**:  All involved should check out the PR #759 and make sure it works as intended.  Confirmation will speed up a merge.
