### ISSUE TITLE
wildignore integration acts funny

### ISSUE THREAD

**Issue by rr-** [scrooloose/nerdtree#569]
Say I'm inspecting a file and I press my precious <kbd>F3</kbd>:

``` vim
autocmd VimEnter * nnoremap <F3> :NERDTreeFind<CR>
```

this focuses the file on NERDTree and all is well. However now I see lots of dreaded `__pycache__` directories that are on my black list:

``` vim
set wildignore+=*.pyc,*.pyo,__pycache__
```

...which is bad. Now, it wouldn't be "funny" if it wasn't for the following trick - if I press <kbd>R</kbd> to reload the NERDTree, the `__pycache__` directories are gone.

**Comment by lifecrisis** [comment]
Confirmed bug, working on a fix.
