### ISSUE TITLE
First time user - get error when hitting Enter on a directory

### ISSUE THREAD

**Issue by shikhanshu** [scrooloose/nerdtree#571]
Today's the first time I have installed Nerdtree using Vundle. Did a "vim ." and can see the directory listing. But as soon as I hit Enter to navigate inside a folder, I get:
```
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..75..116..233..240:
line    3:
E117: Unknown function: strchars
E15: Invalid expression: strchars(a:line[0:numLeadBytes-1])
```

vim version is 7.2.108

**Comment by PhilRunninger** [comment]
This is fixed in commit [4428aba](https://github.com/scrooloose/nerdtree/commit/4428aba2a299cbd117c80e7d18068b2cbb222fff) using @yous 's posted workaround in #517.
