### ISSUE TITLE
NERDTree inserting horizontal lines across screen after each dir listing

### ISSUE THREAD

**Issue by ezuk** [scrooloose/nerdtree#579]
Hi there,

The image says it all:

![ezuk ezuk-mm-vm 10 0 2 15 - byobu 2016-05-06 12 14 08](https://cloud.githubusercontent.com/assets/1092548/15079005/18a15ddc-1384-11e6-8cf5-a55f484a2880.png)

This is on neovim, but I don't think it should matter. After every directory, NERDTree puts a horizontal line across my whole screen. I have no idea how to make it stop, and it's driving me bonkers. :)

Any ideas?

**Comment by PhilRunninger** [comment]
@ezuk, Is this still happening for you? If so, can you provide more details? Platform, commit hash of NERDTree, relevant vimrc statements, miscellaneous syntax files.

**Comment by ezuk** [comment]
I did indeed keep having the issue, but I've since then switched to using another plugin, so you can consider this resolved. Thank you!
