### ISSUE TITLE
Cannot create node in path with accented characters

### ISSUE THREAD

**Issue by tophsic** [scrooloose/nerdtree#580]
Hi,

I do not know if it is a known issue but I cannot create note in NERD Tree inside a path which contains accented characters.

I work actually on a OSX with vim 7.3 (2010 Aug 15, compiled Oct 28 2015 19:46:19) and branch master of scrooloose/master (35c8591)

```
mkdir /tmp/Privé
cd /tmp/Privé
vim
:NERDTree
matest<cr>
```

Give me this errors:

```
Error detected while processing function nerdtree#invokeKeyMap..68..67..<SNR>24_showMenu..42..59..NERDTreeAddNode:
line   18:
E716: Key not present in Dictionary: isOpen || !empty(parentNode.children)
E15: Invalid expression: parentNode.isOpen || !empty(parentNode.children)
Error detected while processing function nerdtree#invokeKeyMap..68..67..<SNR>24_showMenu..42..59:
line    6:
E171: Missing :endif
Error detected while processing function nerdtree#invokeKeyMap..68..67..<SNR>24_showMenu..42:
line   19:
E171: Missing :endif
Error detected while processing function nerdtree#invokeKeyMap..68..67:
line    3:
E171: Missing :endif
Error detected while processing function nerdtree#invokeKeyMap..68:
line   23:
E171: Missing :endif
```

As I write the issue, I observe that that path is incorrect in the NERDTree Menu:

<img width="356" alt="capture d ecran 2016-05-11 a 06 07 49" src="https://cloud.githubusercontent.com/assets/930980/15169739/d426221e-173e-11e6-82c8-b2160e6a9435.png">

I will try to spend some time to dig around to understand why I observe this issue.

Thanks for your great job.

**Comment by tdehaeze** [comment]
Same issue

**Comment by tophsic** [comment]
Did not have time to have a look yet :disappointed:

**Comment by PhilRunninger** [comment]
This appears to be working with the current version of NERDTree and Vim 8.0 on Mac. Is this still an issue for you?

**Comment by PhilRunninger** [comment]
It's been a year and a half with no response. Closing.
