### ISSUE TITLE
How to focus main window on launch?

### ISSUE THREAD

**Issue by mcandre** [scrooloose/nerdtree#583]
I like the idea of having NERDTree open automatically when I launch Vim, but I want the cursor focus to be on the main window (e.g. `hello.c` when I run `vim hello.c`), not NERDTree. What's a good way to configure this behavior?

**Comment by dNItro** [comment]
Add the following to your `.vimrc`
```
augroup NERD
    au!
    autocmd VimEnter * NERDTree
    autocmd VimEnter * wincmd p
augroup END
```

**Comment by therealplato** [comment]
https://github.com/scrooloose/nerdtree/pull/593

**Comment by mcandre** [comment]
Works for me!
