### ISSUE TITLE
BufLeave and BufEnter event not getting triggered when re-entering the same buffer from NERDTree

### ISSUE THREAD

**Issue by kshenoy** [scrooloose/nerdtree#588]
As described  [here](https://github.com/kshenoy/vim-signature/issues/3#issuecomment-222421977), if I open NERDTree and go back to the same file by pressing `<CR>` in NERDTree, it doesn't trigger the `BufLeave` and `BufEnter` autocmds. 

Is this intentional?

**Comment by lifecrisis** [comment]
Previously, this kind of thing was necessary.  However, I'm not able to come up with a general rule for when or why it was needed.

For this particular operation, we can fix this, but it will require some care and review to get it right.

I'll assign myself to this and get to it when I can.

**Comment by writeblankspace** [comment]
I have the same problem when entering a buffer via double-click, `o` or `<CR>`.
