### ISSUE TITLE
Feature Request: Visual selecting node to move to

### ISSUE THREAD

**Issue by zwhitchcox** [scrooloose/nerdtree#596]
when you want to move a file, you have to manually type in the node to which to move it, which kind of takes a long time.. It would be easier and more efficient if we could just select a node in the directory tree to which to move the file

**Comment by PhilRunninger** [comment]
Maybe instead of a visual selection, we could redefine `y`ank and `p`ut inside of NERDTree.

**Comment by iwkse** [comment]
+ 1 for this. Actually copy/moving is a bit complicated, especially when you have to deal with long paths.
I've also noticed there's no way to move a folder inside another subfolder as it acts like renaming instead of moving. Well..I'm browsing issues to find out if there's a way to do this

**Comment by tuzz** [comment]
I'd really like this feature. I frequently move files and the current way of typing the path feels clunky. Maybe I'll look into adding this.

**Comment by PhilRunninger** [comment]
While this is a neat idea, it's not something I want to tackle. If anyone is interested in doing this, I'll of course, accept pull requests for it, but for now, I'm closing this issue.
