### ISSUE TITLE
function nerdtree#openExplorer undefined

### ISSUE THREAD

**Issue by bankexing** [scrooloose/nerdtree#597]
ERROR occurred at
function nerdtree#ui_glue#invokeKeyMap[1]..75[50]..74[5]..<SNR>49_handleMiddleMouse
E117: Undefined function:nerdtree#openExplorer

Step: 
ssh with XShell 5
bash:~$vim
Ctrl+e
Scroll the middle mouse button to show the tree bottom
and then this error occurred.
Maybe some XShell's bugs cause this , I'm not sure.

**Comment by liuxyc** [comment]
+1   same issue
