### ISSUE TITLE
Is there a way to silently open a file as a buffer?

### ISSUE THREAD

**Issue by arechsteiner** [scrooloose/nerdtree#598]
I'd like to use NERDTree at the beginning of a session to open multiple files at once. Is there a way to open a file as a buffer without loosing focus on the NERDTree window? Like `Shift-T` but without opening a new tab.

**Comment by PhilRunninger** [comment]
If I understand your question right, you can use `go` to open a file while staying inside NERDTree. You can also use `gi` and `gs` to split your window before opening the file.

**Comment by arechsteiner** [comment]
Of course, you're totally right. I missed this because when using `go`, my vim-airline buffer bar does not update immediately, but the buffers are indeed opened in the background. Thank you!

**Comment by neelabalan** [comment]
> If I understand your question right, you can use `go` to open a file while staying inside NERDTree. You can also use `gi` and `gs` to split your window before opening the file.

very much helpful
