### ISSUE TITLE
Feature Request: Open new file

### ISSUE THREAD

**Issue by rbjorklin** [scrooloose/nerdtree#601]
Would be useful to be able to open (create) new files from the NERDTree. Maybe this functionality already exists in which case you may happily point me to the correct section in the documentation (I can't find it if it exists).

EDIT: This can be done with `%` in the builtin file explorer if it matters.

**Comment by PhilRunninger** [comment]
@rbjorklin, that functionality exists, but the specifics aren't documented. There is a section of the documentation covering [NERDTreeMenu](https://github.com/scrooloose/nerdtree/blob/master/doc/NERD_tree.txt#L587), but it doesn't tell you what items are in the menu. You can do what you want like so:

1. With your cursor in NERDTree open the folder that will contain the new file.
1. Press `m` to display the NERDTree menu. 
1. Select the `a` option on the menu.
1. Enter the name of the new file. The menu will go away, and your cursor should be on the new file.
1. Press `o` to open the file.

**Comment by rbjorklin** [comment]
Thanks @PhilRunninger! Is there any way I could bind a key to this functionality? I'm guessing [this](https://github.com/scrooloose/nerdtree/blob/master/nerdtree_plugin/fs_menu.vim#L93) is what I want to bind? (Could be [this](https://github.com/scrooloose/nerdtree/blob/master/lib/nerdtree/tree_dir_node.vim#L34) too I suppose) any pointers on how to do this?

**Comment by PhilRunninger** [comment]
You could bind a key to NERDTreeAddNode(), but that's already being done [here](https://github.com/scrooloose/nerdtree/blob/master/nerdtree_plugin/fs_menu.vim#L22). You could also map a key to the function like this: `nnoremap <leader>n :call NERDTreeAddNode()<CR>`, but you would still need to `o`pen the file separately. NERDTree will do everything already that you're asking for. I guess I don't see the benefit of an additional binding.
