### ISSUE TITLE
can't check arrow char in mingw32

### ISSUE THREAD

**Issue by zzs213** [scrooloose/nerdtree#602]
because mingw32 has no full support for unicode, and nerdtree just check win16, wwin32 and win64. So when try to set "▸" , E114 appear.
Maybe need to check has('win32unix') too. I'am not sure. Because of the function runningWindows() was called many place.

**Comment by PhilRunninger** [comment]
@zzs213, do you feel comfortable running git commands in your nerdtree folder? If so, you can do some testing for me, since I don't have access to cygwin. Go to your nerdtree folder, and type these commands:

```
git pull
git checkout win32unix
```

Then go into vim, and see if the error has been fixed.

Thanks!
