### ISSUE TITLE
No colorcolumn in files open from nerdtree

### ISSUE THREAD

**Issue by yevhen-m** [scrooloose/nerdtree#609]
When I open python files from nerdtree, there is no colorcolumn. I have to `:set ft=python` again to get it back.

**Comment by mike-zueff** [comment]
@yevhen-m Why don't you use the following workaround?

https://github.com/mike-zueff/home_config_files/blob/master/.vimrc

```
autocmd FileType nerdtree setlocal colorcolumn&
set colorcolumn=81
```

**Comment by yevhen-m** [comment]
Thanks, I'll try that.
What does it mean `colorcolumn&`?

**Comment by mike-zueff** [comment]
@yevhen-m, see
`:help :set-&`
