### ISSUE TITLE
[feature] :NERDTreeLocate

### ISSUE THREAD

**Issue by Industrial** [scrooloose/nerdtree#611]
Hi!

I really like the `:NERDTreeFind` feature however it always activates the NERDTree buffer/split.

What I really want is that whenever I open an existing file or write a file, it is located in NERDTree without leaving the file buffer.

I propose a new command `:NERDTreeLocate` that does exactly the same as `NERDTreeFind` but without  switching buffers :-)

**Comment by PhilRunninger** [comment]
You could try something like this:
```
augroup NERDTreeFindOnBufferSwitch
    autocmd!
    autocmd! BufEnter,BufReadPost,BufWritePost * NERDTreeFind | wincmd p
augroup END
```
It's not bulletproof by any means, but it's at least a start.

**Comment by Industrial** [comment]
Hi, I had tried something like that but didn't get it to work. I'll get on this tonight :-) cheers!

**Comment by Industrial** [comment]
Works great, but only when I remove the BufEnter, because otherwise I can't switch to NERDTree itself :-)

Thanks!
