### ISSUE TITLE
File coloring based on variable property

### ISSUE THREAD

**Issue by robinfehr** [scrooloose/nerdtree#613]
I just looked around at the existing plugins like [ https://github.com/Xuyuanp/nerdtree-git-plugin](url) and saw that an issue exists to colorize a file based on the git state instead of adding a flag. As far as I've seen in the source it is not rly possible to solve this with a regex. Therefore we'd need an option to kinda tag a nodes and set a custom color for it.

**Comment by robinfehr** [comment]
we're going to try to add a flag using a non displaying character and trying to match it and colorize it.

**Comment by PhilRunninger** [comment]
You could try some techniques I used in this plugin: https://github.com/PhilRunninger/nerdtree-highlight-open-buffers/blob/master/nerdtree_plugin/highlight_open_buffers.vim#L47-L61 I used the conceal feature to hide the flag.

**Comment by robinfehr** [comment]
the non displaying char worked fine.
