### ISSUE TITLE
Bad opening with bookmarks

### ISSUE THREAD

**Issue by w2ak** [scrooloose/nerdtree#614]
Assume you select a bookmark in NERDTree.

| NERDTree                      | File currently open                                                   |

<enter> will indeed open it, but for example "i" or "go" won't open the file in the good window : the file will be open in the NERDTree's window, replacing NERDTree.

[asciinema demo](https://asciinema.org/a/83683)

**Comment by xinxingzhao** [comment]
Assume you set `let NERDTreeShowBookmarks=1` in your .vimrc. Bookmarks will display in NERDTree window. I select a bookmark in NERDTree and execute `t` and `T`. I got error:

Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..73[43]..72[3]..<SNR>32_openInNewTab[1]..76[1]..92[4]..97[3]..86:
line    1:
E716: Key not present in Dictionary: root.AbsoluteTreeRoot() : a:nerdtree.root
E15: Invalid expression: a:searchFromAbsoluteRoot ? a:nerdtree.root.AbsoluteTreeRoot() : a:nerdtree.root
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..73[43]..72[3]..<SNR>32_openInNewTab[1]..76[1]..92:
line    4:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..73[43]..72:
line    3:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..73:
line   43:
E171: Missing :endif

@scrooloose  I assume this is a bug.

@w2ak  Bookmarks has't `i` or `go` mapkey. You can read the quick help `?` about bookmark table mappings.

" Bookmark table mappings~
" double-click,
" o: open bookmark
" t: open in new tab
" T: open in new tab silently
" D: delete bookmark

**Comment by w2ak** [comment]
What abour the bindings for opening in v/hsplits ? Are you using the same version as me ?

**Comment by lifecrisis** [comment]
This issue will be fixed by PR #835.
