### ISSUE TITLE
Nerdtree Split opens empty Buffers

### ISSUE THREAD

**Issue by codepushr** [scrooloose/nerdtree#616]
Hi,

I'm not exactly sure when this happens but sometimes when I open new Files via [s] in a split view Nerdtree seems to create an empty buffer additionally - or is this Vim? 

Basically I have Nerdtree (toggeled) and one split with one buffer. After choosing a second file and pressing [s] another split happens with the new file inside but a new empty buffer appears in the :buffers list. I recognized this when closing buffers.

It's somehow not happening if I split open buffers via Ctrlp.

Any ideas?

**Comment by scrooloose** [comment]
Hi, this is strange. It's hard to fix without some way to reproduce it :(

Can you take a screenshot and record any relevant details next time it happens and then reopen this issue?
