### ISSUE TITLE
Attempting to open file with special characters fails

### ISSUE THREAD

**Issue by webOS101** [scrooloose/nerdtree#618]
I have a file named `$L.js`.  When I double-click on this file in MacVim it attempts to open a file called `.js`.  I'm assuming this is a nerdtree issue.  Just pulled latest nerdtree from github to be sure it wasn't fixed.  (Quick testing reveals that `$` must be escaped with `\` for Vim to load it properly)

**Comment by tomasky** [comment]
The same for me

**Comment by tomasky** [comment]
the same

**Comment by PhilRunninger** [comment]
This should be fixed by PR #649, which has been merged.
