### ISSUE TITLE
Neovim + rename causes an error

### ISSUE THREAD

**Issue by alexbyk** [scrooloose/nerdtree#621]
Very annoying error happens each time I try to rename an open file using Neovim like "Error detecting while processing function nerdTree#uiglue#..."

**Comment by PhilRunninger** [comment]
@alexbyk, I see you like the emojis. Try the newest version. This issue looks like a duplicate of #307 and #622, and should be fixed by #623.

**Comment by ladislas** [comment]
just update nerdtree through plug and still have the same issue :(

**Comment by PhilRunninger** [comment]
Can you provide more information: environment, full error message, etc.

Thanks

**Comment by alexbyk** [comment]
@PhilRunninger Thanks.

I'm closing this issue because this update https://github.com/scrooloose/nerdtree/commit/08773e1e74a622dcf401d95c6e2e578d7b86acf1 fixed it for me.
