### ISSUE TITLE
OpenBookmark error - Windows 10

### ISSUE THREAD

**Issue by thiagoserra** [scrooloose/nerdtree#624]
I'm getting this kind of error when I try use "OpenBookmark name".
File Bookmark is ok on my user profile in Windows 10.

![erro](https://cloud.githubusercontent.com/assets/3385403/19077722/10612cd0-8a24-11e6-91ea-0da8bea3a39c.png)

**Comment by PhilRunninger** [comment]
This is an issue in Windows 7 and Mac, too. I suspect it's on all platforms.

**Comment by xinxingzhao** [comment]
@PhilRunninger It's OK on Ubuntu.

**Comment by msilvagarcia** [comment]
I'm getting this error in CentOS6 as well.

**Comment by lisiur** [comment]
I'm getting this error on macOS.
<img width="567" alt="qq20161217-0 2x" src="https://cloud.githubusercontent.com/assets/15188817/21287143/f644599c-c49f-11e6-8f99-4596e65386e5.png">

**Comment by lifecrisis** [comment]
**ANNOUNCEMENT:** Everyone involved in this issue should try to work with the `:OpenBookmark` command again. It was updated recently in pull request #703. Please report back with the results of your further testing. Currently, I believe this bug to be resolved.

**Comment by msilvagarcia** [comment]
Works fine for me now.

**Comment by lifecrisis** [comment]
Good to hear back.  Closing now.
