### ISSUE TITLE
Split nerdtree window by percentage rather than fixed width

### ISSUE THREAD

**Issue by mcandre** [scrooloose/nerdtree#637]
When I resize my terminal with a nerdtree pane open, the window splits stick in a way that doesn't look right. Is there a way to configure the nerdtree split pane to layout in terms of a percentage of the whole window, rather than a fixed width?

**Comment by lifecrisis** [comment]
Currently, there is not a convenient way to do what you're talking about without writing some custom code. You will want to review the `g:NERDTreeWinSize` setting (see the documentation).

This variable lets you set the width of any *new* NERDTree you create automatically. Note that it applies only to *new* NERDTree windows... not to ones that have been opened and then toggled closed. You could use the `VimResized` autocommand event to make the appropriate adjustments.

I also think you might be expecting too much of the plugin here... Are you using your mouse to resize windows? That's the easiest way to make adjustments.

**Comment by zkghost** [comment]
It would be nice if you could do the lesser of some fixed width/percentage OR the length needed to display the longest string in the tree.

**Comment by lifecrisis** [comment]
After reviewing this request again, I would argue that this is not a critical feature request.  Users should solve these kinds of problems with their own `autocmd` definitions. Now closing...
