### ISSUE TITLE
Error when opening nerdtree. Undefined variable: g:NERDTreeGlyphReadOnly, g:NERDTreeDirArrowCollapsible, and s:dirArrows

### ISSUE THREAD

**Issue by sdazzo** [scrooloose/nerdtree#643]
I'm getting the following error upon opening NerdTree. It still opens, however the error is a little annoying.

```
Error detected while processing ~/.vim/bundle/nerdtree/syntax/nerdtree.vim:
line    3:
E121: Undefined variable: g:NERDTreeGlyphReadOnly
E15: Invalid expression: 'syn match NERDTreeIgnore #\['.g:NERDTreeGlyphReadOnly.'\]#'
line   25:
E121: Undefined variable: g:NERDTreeDirArrowCollapsible
E116: Invalid arguments for function escape(g:NERDTreeDirArrowCollapsible, '~').'# containedin=NERDTreeDir,NERDTreeFile'

E15: Invalid expression: 'syn match NERDTreeClosable #'.escape(g:NERDTreeDirArrowCollapsible, '~').'# containedin=NERDTr
eeDir,NERDTreeFile'
line   26:
E121: Undefined variable: g:NERDTreeDirArrowExpandable
E116: Invalid arguments for function escape(g:NERDTreeDirArrowExpandable, '~').'# containedin=NERDTreeDir,NERDTreeFile'
E15: Invalid expression: 'syn match NERDTreeOpenable #'.escape(g:NERDTreeDirArrowExpandable, '~').'# containedin=NERDTre
eDir,NERDTreeFile'
line   28:
E121: Undefined variable: g:NERDTreeDirArrowCollapsible
E116: Invalid arguments for function escape(g:NERDTreeDirArrowCollapsible, '~]\-').escape(g:NERDTreeDirArrowExpandable,
'~]\-')
E15: Invalid expression: escape(g:NERDTreeDirArrowCollapsible, '~]\-').escape(g:NERDTreeDirArrowExpandable, '~]\-')
line   29:
E121: Undefined variable: s:dirArrows
E15: Invalid expression: 'syn match NERDTreeDir #[^'.s:dirArrows.' ].*/#'
line   31:
E121: Undefined variable: s:dirArrows
E15: Invalid expression: 'syn match NERDTreeFile  #^[^"\.'.s:dirArrows.'] *[^'.s:dirArrows.']*# contains=NERDTreeLink,NE
RDTreeRO,NERDTreeBookmark,NERDTreeExecFile'
line   34:
E121: Undefined variable: g:NERDTreeGlyphReadOnly
E15: Invalid expression: 'syn match NERDTreeRO # *\zs.*\ze \['.g:NERDTreeGlyphReadOnly.'\]# contains=NERDTreeIgnore,NERD
TreeBookmark,NERDTreeFile'
```

I'm on the following version of vim:
```
$ vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jun 14 2016 16:06:49)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses
```

I'm on nerdtree commit eee431d.

**Comment by jgandt** [comment]
This *seems* to have resolved itself for me. I am on commit: [2817010](https://github.com/scrooloose/nerdtree/commit/281701021c5001332a862da80175bf585d24e2e8)

**Comment by masukomi** [comment]
I'm on 281701021c5001332a862da80175bf585d24e2e8 also, and having the same problem. 

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  3 2017 16:49:50)
MacOS X (unix) version
Included patches: 1-297
```

**Comment by smd01** [comment]
This problem has magically disappeared and I'm on the same commit. 
:suspect:

**Comment by exupero** [comment]
Having this problem on 281701021c5001332a862da80175bf585d24e2e8

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 12 2017 23:20:33)
MacOS X (unix) version
Included patches: 1-329
```

**Comment by Karunamon** [comment]
Same commit, same vim version, same problem. 

I can work around this error by forcing the problematic items in my `.vimrc` per #489:

```vimscript
" NERDTree setting defaults to work around http://github.com/scrooloose/nerdtree/issues/489
let g:NERDTreeDirArrows = 1
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
let g:NERDTreeGlyphReadOnly = "RO"
```

**Comment by blutgens** [comment]
I worked around it by adding "let g:NERDTreeGlyphReadOnly = "RO" too.

**Comment by lifecrisis** [comment]
I can't determine how to replicate this problem at the moment. We'll have to let this potential bug sit around until I can reliably trigger it.

**Comment by Harshiv-Patel** [comment]
I face this issue too.
I'm using Termux Android app to run vim on my phone.
Output of vim --version:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  8 2017 12:45:32)
Included patches: 1-1180
Compiled by builder@0c0f51b4254b
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     -gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
-clientserver    +insert_expand   +packages        +title
-clipboard       +job             +path_extra      -toolbar
+cmdline_compl   +jumplist        -perl            +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
+cscope          +lispindent      +python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      -xsmp
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/data/data/com.termux/files/usr/share/vim"
Compilation: arm-linux-androideabi-clang -c -I. -Iproto -DHAVE_CONFIG_H   -I/data/data/com.termux/files/usr/include  -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Oz -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: arm-linux-androideabi-clang   -L/data/data/com.termux/files/usr/lib -march=armv7-a -Wl,--as-needed -o vim        -lm   -lncursesw -liconv     -L/data/data/com.termux/files/usr/lib/python3.6/config-3.6m/ -lpython3.6m -ldl -lutil -lm      
----------------------------------------------------------------------------------------
<hr/>
Im running Lollipop 5.1.1
I took the latest version from this nerdtree repo.
Screen shot of event:
![screenshot_2017-10-11-07-54-22](https://user-images.githubusercontent.com/25936599/31419594-45187c16-ae5a-11e7-842c-ec24559cd1cb.png)

**Comment by Harshiv-Patel** [comment]
@Karunamon 's solution works for me.

**Comment by PhilRunninger** [comment]
If anyone here is still experiencing this issue, please respond. My guess is there's a problem with the way NERDTree is installed in your vim configuration. I need the following information:

- [ ] the Vim plugin manager you are using, if any
- [ ] the location of all the NERDTree folders
- [ ] the output of `:scriptnames`
- [ ] the way vim was started (Did you open a file from the command line?)
- [ ] the way NERDTree was opened (Were any buffers already open?)

One way this can happen is when the files are not in the correct location, and they therefore aren't sourced in the correct order. `nerdtree/plugin/NERD_tree.vim` must be the first of the NERDTree files to be sourced, so these variables are created before other NERDTree functions need them.
