### ISSUE TITLE
Conflict with plugin  Source explorer

### ISSUE THREAD

**Issue by JackNwsuaf** [scrooloose/nerdtree#645]
When the cursor reaches some files or directories in Nerdtree window with the Source explorer opening,the Nerdtree window will lose content.
![BEFORE](https://i.stack.imgur.com/hnwKE.png)
if the cursor reach file init.S,the problem occurs
![AFTER](https://i.stack.imgur.com/KHluC.png)
I also post it on [stackoverflow](http://stackoverflow.com/questions/41032151/vim-plugins-nerdtree-and-source-explorer-have-conflicts)

**Comment by PhilRunninger** [comment]
This appears to be problem outside of the NERDTree project scope.
