### ISSUE TITLE
NERDTreeToggle breaks IndentLines plugin

### ISSUE THREAD

**Issue by cmcginty** [scrooloose/nerdtree#651]
I use [IndentLine](https://github.com/Yggdroot/indentLine) in my setup, but when I run `NERDTreeToggle` all of the indents are turned off in the text window.

The only way to enable them is to run `IndentLinesReset`.

I reported this issue here because if I run `NERDTree` and `NERDTreeClose` the indent marks work correctly. It seems that there must be some additional code in `NERDTreeToggle` that is breaking this plugin.

**Comment by PhilRunninger** [comment]
I can't reproduce this on my setup: vim 8.0, current NERDTree and commit 1993700 from before your issue, Mac OS High Sierra.

Do you have any other information that would help? If it's working now, please close the issue.

Thanks.

**Comment by cmcginty** [comment]
Yeah, this is old. Must have been fixed. I can't repro it either. Thanks for investigating.

**Comment by joaovinicius** [comment]
https://github.com/scrooloose/nerdtree/issues/913#issuecomment-489208151
