### ISSUE TITLE
How to use FileNode in NERDTree API ?

### ISSUE THREAD

**Issue by chocolord** [scrooloose/nerdtree#652]
Hello,

I'm using Vim on Windows and I try to add a new keymapping to open a file with the default program.

I've found a way to open a file with the default program:
```vim
call system("cmd.exe /C start file:///absolute/path/to/file.ext")
```

and I wrote a command Open:
``` vim
command! -n=0 Open :execute ':call system("cmd.exe /C start file:///' . join(split(expand('%:p'), '\'), '/') . '")'
```

I've found the function NERDTreeAddKeyMap to add the keymapping:
``` vim
call NERDTreeAddKeyMap({
    \ 'key': 'O',
    \ 'callback': 'Open',
    \ 'quickhelpText': 'Open file with default program',
    \ 'override': 1,
    \ 'scope': 'FileNode' })
```

But I dont understand how to get the absolute path of the file node passed to the Open function
``` vim
function! Open(fileNode)
  call system('cmd.exe /C start file:///' . a:fileNode.???) " TODO :)
endfunc
```

**Comment by PhilRunninger** [comment]
Look at the mac-only function `NERDTreeExecuteFile()` in `nerdtree_plugin\fs_menu.vim`. It will show you how it's done. 

```
function! NERDTreeExecuteFile()
    let treenode = g:NERDTreeFileNode.GetSelected()
    if treenode != {}
        call system("open '" . treenode.path.str() . "'")
    endif
endfunction
```

In your case, you'd use `a:fileNode.path.str()`.

**Comment by chocolord** [comment]
Thanks a lot @PhilRunninger 

I used `a:filenode.path.str()` and it's works but it also leaded me to an other issue:
Using NERDTree with [Vundle](https://github.com/VundleVim/Vundle.vim) I wasn't able to call the `NERDTreeAddKeyMap` function in my vimrc file, I've managed it by creating a local plugin in my $HOME/vimfiles/bundle repository:

$HOME/vimfiles/nerdtree_windows/plugin/nerdtree_windows.vim
``` vim
" Script init stuff
"============================================================
if exists("loaded_nerd_tree_windows")
    finish
endif

" check nerdtree loaded
if !exists("loaded_nerd_tree")
    echoerr "NERDTreeWindows: this plugin requires NERDTree to be loaded!"
    finish
endif

let loaded_nerd_tree_windows = 1

" NERDTree configuration
function! NERDTreeWindowsOpenFile(filenode)
    call system('cmd.exe /C start file:///' . join(split(a:filenode.path.str(), '\'), '/'))
endfunction

call NERDTreeAddKeyMap({
    \ 'key': '<C-o>',
    \ 'callback': 'NERDTreeWindowsOpenFile',
    \ 'quickhelpText': 'Open file with default program',
    \ 'override': 1,
    \ 'scope': 'FileNode' })

```

$HOME/vimfiles/vimrc
``` vim
" ...
" vundle#begin("...")

" some plugins
Plugin 'scrooloose/nerdtree' " the NERD Tree
" others plugins

Plugin 'file:///C:/Users/user/vimfiles/bundle/nertree_windows' "NERDTree - windows
" vundle#end()
" ...
```

And it finally leaded me to some questions:

1. Is it better to use the scope option in the `NERDTreeAddKeyMap` function or the `g:NERDTreeFileNode.GetSelected()` function ant test the result ?
2. Should I test the argument passed to the NERDTreeWindowsOpen function if I use the `scope` option in the `NERDTreeAddKeyMap` function's argument.
3.  Could it be a good idea to have a per-platefrorm plugin of NERDTree like the [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin) ?

**Comment by lifecrisis** [comment]
@chocolord, this looks way to complicated from my point of view. You should reuse existing code.

Take a look at pull request #724. There, I built a mapping that reused code from the netrw plugin included with Vim.

See the following revised version of the mapping:

```viml
function! s:ScriptFunctionPrefix()
  return matchstr(expand('<sfile>'), '<SNR>\d\+_')
endfunction

function! s:OpenFileHandler(fileNode)
    call g:netrw#BrowseX(a:fileNode.path.str(), 0)
endfunction

call g:NERDTreeAddKeyMap({
            \ 'key' : 'gx',
            \ 'callback' : s:ScriptFunctionPrefix() . 'OpenFileHandler',
            \ 'quickhelpText' : 'open file externally',
            \ 'scope' : 'FileNode',
            \ })
```

This should do what you want. Just position the cursor on a file node and type `gx` to open the file in Windows (the hit enter prompt will be removed in the latest versions of Vim).

Further, you should be saving your NERDTree plugins in a special folder in your `vimfiles` (on Windows) or `.vim` (on Unix) directory. If you save the above mapping in `$HOME\vimfiles\nerdtree_plugin\gx.vim` you'll see that `gx` will work as expected.

Any new plugins you write for the NERDTree should  go in the same directory. You *don't* need to use Vundle to install a plugin you write for the NERDTree!

Let me know if this solves your problem, so we can close this issue.

**Comment by chocolord** [comment]
@lifecrisis, this solution works, it solves my old problem.

I upgraded the plugin I did so it can open a directory with explorer and I added a keymapping to open a shell (it was cmd and finally it's Powershell) in the directory under the cursor.

I moved the files in $HOME/nerdtree_plugin/[gx.vim, nertree_windows.vim] and both are working nicely.

Here is the code of my actual file nerdtree_windows:

```vim
" Script init stuff
"============================================================
if exists("loaded_nerd_tree_windows")
    finish
endif

" check nerdtree loaded
if !exists("loaded_nerd_tree")
    echoerr "NERDTreeWindows: this plugin requires NERDTree to be loaded!"
    finish
endif

if !nerdtree#runningWindows()
    " echo 'nerdtree_windows is for windows OS (win16/win32/win64).'
    finish
endif

let loaded_nerd_tree_windows = 1

" NERDTree configuration

" Windows open node
function! NERDTreeWindowsOpenNode(node)
    call system('cmd.exe /C start ' . join(split(a:node.path.str(), '\'), '/'))
endfunction

call NERDTreeAddKeyMap({
            \ 'key': '<C-o>',
            \ 'callback': 'NERDTreeWindowsOpenNode',
            \ 'quickhelpText': 'Open node with default program',
            \ 'override': 1,
            \ 'scope': 'Node' })

" Windows open cmd
function! NERDTreeWindowsPowerShellHere(dirnode)
    call system('cmd.exe /C start powershell -NoExit -Command cd ' . a:dirnode.path.str())
endfunction

call NERDTreeAddKeyMap({
            \ 'key': '<C-c>',
            \ 'callback': 'NERDTreeWindowsPowerShellHere',
            \ 'quickhelpText': 'Open a terminal in the directory',
            \ 'override': 1,
            \ 'scope': 'DirNode' })
```

**Comment by lifecrisis** [comment]
I'm glad it works for you. Since your problem is solved, I will now close this issue. Thanks.
