### ISSUE TITLE
If "set shellslash", can't open file if path have space.

### ISSUE THREAD

**Issue by bleakwind** [scrooloose/nerdtree#653]
If "set shellslash", can't open file if path have space.

> D:/Program Files/vim/vimrc

Can't open vimrc. It will open:

> D:/Program/ Files/vim/vimrc

**Comment by lifecrisis** [comment]
**ANNOUNCEMENT**:  Pull request #734 offers a potential fix for this problem. Please checkout the branch there for testing. It must be tested before we merge the changes.
