### ISSUE TITLE
Cursor moves with lags when with arrow keys is down

### ISSUE THREAD

**Issue by whitecolor** [scrooloose/nerdtree#654]
On a big tree (actually not so big - around 30 closed first level nodes with Icons) when I hold down the key cursor is moving with lugs jumping over several nodes, it just looks strange as if UI with lags.

Noticed on windows 10 (ubuntu bash shell) [wsltty terminal](https://github.com/mintty/wsltty).

Maybe there some options to improve this visually flawed behavior?

**Comment by whitecolor** [comment]
Oh it is due to `vim-nerdtree-syntax-highlight'`, this is also discussed in the https://github.com/tiagofumo/vim-nerdtree-syntax-highlight/issues/6

**Comment by PhilRunninger** [comment]
Yes, this is a known issue with that plugin. Syntax highlighting can be a performance hit, depending on how complex the regular expressions are or how many are being processed.
