### ISSUE TITLE
Annoying errors with neovim

### ISSUE THREAD

**Issue by alexbyk** [scrooloose/nerdtree#658]
Getting this annoying error, don't know what causes them

```
E716: Key not present in Dictionary:: root.path.str():''
E15: Invalid expression: exists('b:NERDTree')?b:NERDtree.root.path.str():''
```
```
Error: detected while processing BufLeave Auto command for "NERD_tree_*"
Key not present in Dictionary: ui.saveScreenState()|endif
```

**Comment by FuzzOli87** [comment]
I've been getting these often the last few days on Arch but not on my Mac. I also get a weird bug where nerdtree multiplies across buffers when I try to close an existing one.

**Comment by alexbyk** [comment]
After the latest update of neovim problems disappeared.  So I'm clothing this issue.

**Comment by gopalagrawal** [comment]
These problems have not disappeared when installing in gvim 8.0. Installed NerdTree using vim-plug and it gives the same errors while loading.

**Comment by lifecrisis** [comment]
@FuzzOli87, are you using `:bwipeout` to close the NERDTree? That's a bug that is known to me, but it hasn't been reported here yet.

**Comment by lifecrisis** [comment]
**UPDATE:** The first error is from the status line definition and the second error is from a straightforward autocommand that was changed to add spacing to the code.

All of you need to include any special NERDTree configuration code you keep in your `.vimrc` if you want this issue tracked down (no guarantees, of course).

**Comment by gopalagrawal** [comment]
Got this to work with vim as well.  I was initially trying to put all the plugins in  vimfiles/plugin folder.  Read somewhere I should not use that folder (but it certainly seems that would be the purpose of that folder).  So I changed the vimrc to use my own created folder called "vimplugs".  My vimrc below:  

call plug#begin('C:\Program Files (x86)\Vim\vimplugs')
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
call plug#end()

Now nerdtree works as expected.
