### ISSUE TITLE
GVim window resizes on NERDTreeToggle

### ISSUE THREAD

**Issue by dubst3pp4** [scrooloose/nerdtree#659]
When calling `:NERDTreeToggle` the whole GVim window size decreases. I don't know since when this happens, but I'm sure that it first occured with Vim 8.

I'm using elementary OS (Ubuntu 16.04 LTS) with Vim 8.0. Any ideas what could be causing this?

**Comment by PhilRunninger** [comment]
This has been reported on Windows gvim. Perhaps the same thing is happening here. See #513 for the resolution.

**Comment by dubst3pp4** [comment]
Thanks @PhilRunninger, disabling scrollbars with

```
:set guioptions-=L
:set guioptions-=R
```
solves it!
