### ISSUE TITLE
The panel enlarges when I close a tab

### ISSUE THREAD

**Issue by osenvosem** [scrooloose/nerdtree#660]
MacOS 10.12.3, iTerm 3.0.14, neovim 0.1.7
After I close a tab and it jumps on a previous one I got the panel with huge size. After that I am forced to reopen vim.

![screen shot 2017-02-19 at 16 55 24](https://cloud.githubusercontent.com/assets/6762673/23103029/1b2cf6ea-f6c5-11e6-8416-08659487c60d.png)

**Comment by jveillet** [comment]
I have the exact same problem on Debian 8 + gnome-terminal and vim 7.4 (Included patches: 1-488, 576;Extra patches: 8.0.0322, 8.0.0056).

@osenvosem You should be able to click and drag the vertical grey separator to rezise back the window though, whitout the need to restart vim (temporary fix because the problem is happening every time you change tabs).

**Comment by joshuaswilcox** [comment]
I get the same when I accidentally try to close the panel instead of the window.  I can't click to change size though, i have to restart. (macOS, iTerm2)

**Comment by lifecrisis** [comment]
To all involved: *Please include any configurations you have in your* `vimrc` *file*.

To @joshuaswilcox, you should try the following in your `vimrc`:

```viml
if has('mouse')
    set mouse=a
endif
```

**Comment by PhilRunninger** [comment]
What is your definition for the `:NERDTreeTabsToggle` command? That's not defined in NERDTree.

**Comment by osenvosem** [comment]
It has been 7 months already, I've changed my editor.
But I'm apparently not the only one who experienced the issue.

**Comment by lifecrisis** [comment]
Well, the important thing here is that a command is being used that we didn't define.  Therefore, there is not really any bug to fix on our end.

I see no benefit to allowing this issue to remain open.  If the issue is raised again, we can revisit this.

**Comment by joshuaswilcox** [comment]
FWIW, @lifecrisis adding that allowed me to recover from when this happens, Thanks!
