### ISSUE TITLE
Misbehaves after :bdelete

### ISSUE THREAD

**Issue by boompig** [scrooloose/nerdtree#666]
I use the plugin 'ap/vim-buftabline' to display buffers in the tabline. Example of how that looks in MacVim below:

![screen shot 2017-02-27 at 11 04 57 am](https://cloud.githubusercontent.com/assets/2791268/23375276/987f003a-fcdc-11e6-8e2a-597213926844.png)

To start, I open a file, then open NERDTree.

![screen shot 2017-02-27 at 11 08 04 am](https://cloud.githubusercontent.com/assets/2791268/23375376/0921a860-fcdd-11e6-8e63-b33ee5e1bdb1.png)

Then I also open another buffer:

![screen shot 2017-02-27 at 11 08 38 am](https://cloud.githubusercontent.com/assets/2791268/23375404/1cf93060-fcdd-11e6-8c67-4f540863f0c1.png)

Now I decide I no longer want to have `Makefile` open, so I delete that buffer with `:bdelete`. The result is below. Notice how the NERDTree split disappears, but the NERDTree buffer is actually open, and is the active buffer (instead of log_utils.py).

![screen shot 2017-02-27 at 11 09 21 am](https://cloud.githubusercontent.com/assets/2791268/23375597/c4d99004-fcdd-11e6-995d-d726bbd00441.png)

I believe the behaviour should either be:

1. Keep NERDTree split open; or
2. Close the NERDTree split, but then switch to another buffer

**Comment by polyzen** [comment]
Doing `:bn | :bd #` is an option.

**Comment by lifecrisis** [comment]
First, @boompig, I'd like to suggest that you read [this link](https://stackoverflow.com/questions/26708822/why-do-vim-experts-prefer-buffers-over-tabs#26710166).  You may rethink your use of buffers in your tab line.  This is not the intent of Vim feature!

Second, the NERDTree should not take it upon itself to do more work than is necessary.  If you close a buffer, why should you want your project explorer closed?  If you want to automatically go to another file, which file? An empty, new buffer? The alternate buffer?

There is no way we can code a solution to this problem that will satisfy everyone. You'll have to code your own solution, perhaps with autocommands.
