### ISSUE TITLE
Hi open a buffer on a new tab via nered tree 

### ISSUE THREAD

**Issue by elastic7327** [scrooloose/nerdtree#669]
I wanna make some buffer on a new tab via Nered tree.. how can i do ? 

![2017-03-05 1 53 33](https://cloud.githubusercontent.com/assets/16227780/23580972/aff5e10c-0146-11e7-9de9-32f214a94faa.png)

**Comment by lifecrisis** [comment]
You can use the `t` and `T` mappings to open a buffer for a file node in a new tab.  Run the command
```vimscript
:help NERDTreeMappings
```
for a listing of all default mappings.

In the future, please at least take the time to search the documentation before posting an issue. Thanks!

I'm recommending to @PhilRunninger that this issue be closed.

**Comment by PhilRunninger** [comment]
Also note that the mappings can be changed in your .vimrc. Use the `?` key (as seen at the top of your screenshot) to see the actual mappings, if they happen to be different from the defaults.
