### ISSUE TITLE
`p` doesn't work

### ISSUE THREAD

**Issue by masylum** [scrooloose/nerdtree#67]
I updated to the latest nerdtree version and `p` no longer works to visit the parent node.

**Comment by complex857** [comment]
I'm not sure if this is related, but it seems to me that <kbd>p</kbd> only breaks when i want to go up from a directory that's parent line is combined of multiple dirs. This is a new feature from [this commit](https://github.com/scrooloose/nerdtree/commit/2cef8bb6022b9e450cdee23d03024822e1dbeeea).

So if i have it like this
```
  ~ views/some_folder/
    + boxs/ <--- this is where my cursor is
```

Then <kbd>p</kbd> wont work, while if there's no such combined directory in the path then it works as before.

**Comment by lifecrisis** [comment]
I am not sure why this was closed. @complex857 clearly described the problem, and I was able to replicate the issue precisely. It should be a simple fix that I will get to eventually. Re-opening now...
