### ISSUE TITLE
Request: highlight the active window's buffer in NERDtree

### ISSUE THREAD

**Issue by unphased** [scrooloose/nerdtree#670]
I'd like to see at a glance which file in the dir tree is currently opened in a buffer. 

Even more awesome would be if NERDtree would (in addition to the above) autoexpand the filesystem hierarchy to *reveal* the active buffer.

**Comment by lifecrisis** [comment]
Hey, @unphased. Your idea is neat, but I don't think it's feasible or to be recommended. There would need to be some complicated mechanism for keeping this special highlighting up to date as the user moves around among other windows or switches buffers. This is the kind of code that the NERDTree needs to avoid for a number of reasons (including how difficult it is to do this kind of thing in Vim).

To reveal the file in the NERDTree, you can use `:NERDTreeFind` (see the documentation).

I suggest to @PhilRunninger that this feature request be rejected and that this issue be closed.

**Comment by unphased** [comment]
Pretty reasonable. 

I do make heavy use of `:NERDTreeFind`.

**Comment by lifecrisis** [comment]
By the way @unphased, `:NERDTreeFind` may get an update soon so keep an eye out. See pull request #419.

**Comment by unphased** [comment]
Okay! Nice. I thought about it a little more and maybe I don't agree that such a solution has to be so complicated. There are auto commands for buffer switching, and that would be the only ones needed. It'd be more simplistic than the tracking that TagBar would  need to do for instance... but, that pr you linked looks quite promising.

**Comment by lifecrisis** [comment]
Most users don't know this, but the NERDTree ignores select autocommands for efficiency reasons. This would make what you're talking about difficult as the functions that update the highlighting in the NERDTree could not be reliably called. There's a lot of debate about this. If you come up with a solution, I'm sure the maintainers would at least look at it... merging is likely not guaranteed, however.
