### ISSUE TITLE
Can't open a symbolic link in NerdTREE

### ISSUE THREAD

**Issue by galvao** [scrooloose/nerdtree#672]
If one of the tree nodes is actually a symbolic link to another folder in the disk, NerdTREE doesn't open it.

It seems "aware" of the fact that it is a symbolic link (it shows "symlink_name->path/to/actual_folder", but that's all, you can't open the node no matter what you do.

**Comment by lifecrisis** [comment]
What do you mean by "opening" the node? Do you mean externally? Or, do you mean just editing the file like with the `o` macro?

We need more information here. What's your system? What's your Vim version? Can you provide a sample directory hierarchy so that we can replicate the possible bug?

**Comment by galvao** [comment]
I meant opening and listing the directory contents, as it does with a regular directory (by pressing enter).
In any case, I've just tested this now and it works, thank you.

Probably a bit irrelevant now, but anyway:
Fedora 25 (KDE);
Working on (G)Vim 8.0.728

**Comment by lifecrisis** [comment]
Thanks, I'm glad it works for you now.
