### ISSUE TITLE
Moving cursor in create/rename/copy/move files within nerdtree

### ISSUE THREAD

**Issue by nukr** [scrooloose/nerdtree#673]
When I press m -> m to rename file, I want to move cursor by ctrl+b (like ternimal) but my cursor move to the start of path.

How can I move cursor without array key?

**Comment by LinuCC** [comment]
If I understand you correctly, you want to press `Ctrl+f` while renaming to get access to all of Vims normal commands.

**Comment by syguer** [comment]
Try to add following this in your .vimrc
```viml
cnoremap <C-f> <Right>
cnoremap <C-b> <Left>
```

**Comment by nukr** [comment]
@syguer 
Cool! it's work

thanks
