### ISSUE TITLE
can not open file if path contains spaces under Windows

### ISSUE THREAD

**Issue by ZSaberLv0** [scrooloose/nerdtree#674]
occurred only on Windows

open `path/a b/123.txt` would result `123.txt` in path `path/a/ b/`

open `path/123/a b.txt` would result ` b.txt` in path `path/123/a`

**Comment by coralzhang** [comment]
Same here on Mac.

**Comment by PhilRunninger** [comment]
@ZSaberLv0 Can you answer these questions to help diagnose the problem better?
1. Are these preexisting files that you're opening with NERDTree, or are they being created with the NERDTree `m`, `a` menu option?
1. What steps do you take to cause this behavior?
1. Have you set any NERDTree variables?

**Comment by coralzhang** [comment]
Hi, I have no idea if this is a general solution, but works for me. For me it is not really nerdtree, but plain vim. I have been able to work around by adding these to the vimrc file. 

`autocmd BufEnter * silent! lcd %:p:h`

**Comment by ZSaberLv0** [comment]
@PhilRunninger 
1. occurred when openning a existing file, won't occurred when add by `m`, `a`

and after bunch of test, i think the `shellslash` should be the reason

i do need the `shellslash` for convenient, but found NERDTree doesn't support it (long time ago, can't remember why)
so i add `autocmd BufEnter NERD_Tree_*` to disable `shellslash` when using NERDTree as a walkaround

when completely disable `shellslash`, this problem solved

**Comment by lifecrisis** [comment]
**ANNOUNCEMENT**:  Pull request #734 offers a potential fix for this problem. Please checkout the branch there for testing. It must be tested before we merge the changes.

**Comment by ZSaberLv0** [comment]
@lifecrisis PR #734 did solve this issue for my case
