### ISSUE TITLE
Cannot execute python code from :! if the directory contains space

### ISSUE THREAD

**Issue by coralzhang** [scrooloose/nerdtree#678]
Could not resolve the problem of calling file if the directory name has a space in there.

**Comment by coralzhang** [comment]
Just in case anybody might want to know. It is only vim, not nerdtree. Just try add these to your vimrc file 
`autocmd BufEnter * silent! lcd %:p:h`

**Comment by juanibiapina** [comment]
Close this then, please.

**Comment by lifecrisis** [comment]
Thanks, @juanibiapina.
