### ISSUE TITLE
Shortcut for quick adding bookmarks and jumping to bookmarks

### ISSUE THREAD

**Issue by laixintao** [scrooloose/nerdtree#683]
As far as I know, you can add a bookmark only by ":Bookmark [name]", is it possible to set a shortcut for adding bookmarks?

How to get the nodes name, so that I can set a shortcut by my own. :)

**Comment by lifecrisis** [comment]
Creation of custom mappings is accomplished through the use of the NERDTree Key map API. You will want to read `:h NERDTreeKeymapAPI` for more details.  Working through this documentation and having a little knowledge of Vim should give you all that you need.

Recommendation to @PhilRunninger that this issue be closed.

**Comment by laixintao** [comment]
@lifecrisis Thanks, I will try help doc

**Comment by lifecrisis** [comment]
By the way, @laixintao, you should note that NERDTree commands use command-line completion. This means that typing `:Bo<Tab>` will usually give you the command you want. Vim has many native settings for tweaking this feature... too many to be covered here. Enjoy!

**Comment by laixintao** [comment]
@lifecrisis Thanks! It helps a lot :+1:
