### ISSUE TITLE
Parenthesis in path break nerdtree

### ISSUE THREAD

**Issue by CleyFaye** [scrooloose/nerdtree#686]
**Environment:** _Describe your Vim/NERDTree setup._

>* Operating System: KUbuntu yakkety yak (16.10)
>* Vim version 7.4
>* NERDTree version : e671e40
>* NERDTree settings applied in your vimrc, if any: none

**Process:** _List the steps that will recreate the issue._

>1. Be in a directory with parenthesis in it's name (like "/tmp/(")
>2. Run vim to display a file tree, either the working directory, or anything else including the parenthesis: "vim ." and "vim .." both break

**Current Result:** _Describe what you you currently experience from this process._

> Vim output an error:
>> Error detected while processing function nerdtree#checkForBrowse[9]..186[2]..187[17]..188[7]..151[9]..149[32]..262[4]..NERDTreeGitStatusRefreshListener[2]
>> ..NERDTreeGitStatusRefresh:
>> line   16:
>> E484: Can't open file /tmp/vwfTYC1/2
>> Error detected while processing function nerdtree#checkForBrowse[9]..186[2]..187[17]..188[7]..151:
line    9:
>> E171: Missing :endif

**Expected Result:** _Describe what you would expect to have resulted from this process._

> Just see the file tree

---
**Optional**

**Possible Fix:**

> I didn't look in the code, but using absolute path (for example, starting vim with "vim /tmp") fix the issue, so it might be related to parsing relative path.

**Comment by lifecrisis** [comment]
The function `NERDTreeGitStatusRefreshListener()` is an object in the external [NERDTree Git plugin](https://github.com/Xuyuanp/nerdtree-git-plugin). You should report your issue there first.  If it can be identified as an issue with the NERDTree itself, you can open a new issue here describing the problem more clearly.

I recommend to @PhilRunninger that this issue be closed.

**Comment by PhilRunninger** [comment]
I was able to reproduce the error, and I confirmed that without the NERDTree Git plugin, it goes away. Closing.
