### ISSUE TITLE
Hotkey to open NERDTree

### ISSUE THREAD

**Issue by EvanCarroll** [scrooloose/nerdtree#687]
Not an issue, I just found this to be tremendously useful and it's also extremely popular. It may be worth making it a default:

```
let mapleader = ","
nmap <leader>ne :NERDTree<cr>
```

http://stackoverflow.com/q/6467634/124486

Viewed: 15,192; 40 upvotes

**Comment by PhilRunninger** [comment]
These mappings are left to the individual users to set, and one such example is documented in the *README.markdown* file.
