### ISSUE TITLE
Feature request: Flag position setting, align to right

### ISSUE THREAD

**Issue by rafi** [scrooloose/nerdtree#694]
Using the awesome [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin), flags appear on the left-side of items. This can become quite confusing to the eye, especially with hierarchies.

```
</rafi/.config/nvim/     │
▷ [M]colors/             │
▷ [M]config/             │
▷ dev/                   │
▷ [M]ftplugin/           │
▷ [M]plugin/             │
▷ snippets/              │
▷ spell/                 │
▷ [M]themes/             │
  .gitignore             │
  .stfolder              │
  .stignore              │
```

Will it be possible to add a configuration option for placing flags to the right?  for example:

```
</rafi/.config/nvim/     │
▷ colors/ [M]            │
▷ config/ [M]            │
▷ dev/                   │
▷ ftplugin/ [M]          │
▷ plugin/ [M]            │
▷ snippets/              │
▷ spell/                 │
▷ themes/ [M]            │
  .gitignore             │
  .stfolder              │
  .stignore              │
```

It could be perfect if the flags were _aligned_ to the right border:

```
</rafi/.config/nvim/     │
▷ colors/             [M]│
▷ config/             [M]│
▷ dev/                   │
▷ ftplugin/           [M]│
▷ plugin/             [M]│
▷ snippets/              │
▷ spell/                 │
▷ themes/             [M]│
  .gitignore             │
  .stfolder              │
  .stignore              │
```

But this is more difficult.

**Comment by lifecrisis** [comment]
It's a nice idea on the surface, but I think you're expecting too much here. How, for example, should the NERDTree cope with the case where the name of the node is too long to be displayed in the window? In that situation, the flag would no longer be visible (rendering it useless).

The problem described above means that complicated mechanisms would be required to dynamically truncate and render again the lines for nodes with long names.  It would add a lot of code that is not necessary and that would turn out to be quite brittle.

There are other solutions that would be better, like Unicode superscript characters as compact/aesthetic markers or special highlighting... but these would also be quite difficult to get right and would be more likely to just make a mess.

@PhilRunninger, I vote that this feature request be rejected and this issue be closed.

**Comment by PhilRunninger** [comment]
I was thinking the same thing. I did a quick investigation; swapping the order (the second option given) is not too difficult, but it breaks syntax highlighting provided by nertree-git-plugin, and it interferes with `o`pening the files. Not to say these issues can't be overcome, but I believe it's more effort than it's worth, and one of our goals is to stop adding more and more options to the already-large code base. @rafi, are you using a good colorscheme that makes the flags stand out well? Changing your colorscheme may relieve some of the confusion you mentioned.

**Comment by rafi** [comment]
Thanks for the comments, I've tweaked colors and concealed the brackets, looks better now.

![image](https://user-images.githubusercontent.com/147918/27500654-0f642f22-5872-11e7-92bf-493658c0abb3.png)

If anyone is interested in the configuration:

```viml
" Plugin: NERDTree icons and highlights {{{
" ---------------------------------------------------------
let g:NERDTreeIndicatorMapCustom = {
	\ 'Modified':  '·',
	\ 'Staged':    '‧',
	\ 'Untracked': '?',
	\ 'Renamed':   '≫',
	\ 'Unmerged':  '≠',
	\ 'Deleted':   '✃',
	\ 'Dirty':     '⁖',
	\ 'Clean':     '✓',
	\ 'Unknown':   '⁇'
	\ }

let g:NERDTreeDirArrowExpandable = '▷'
let g:NERDTreeDirArrowCollapsible = '▼'

highlight! NERDTreeOpenable ctermfg=132 guifg=#B05E87
highlight! def link NERDTreeClosable NERDTreeOpenable

highlight! NERDTreeFile ctermfg=246 guifg=#999999
highlight! NERDTreeExecFile ctermfg=246 guifg=#999999

highlight! clear NERDTreeFlags
highlight! NERDTreeFlags ctermfg=234 guifg=#1d1f21
highlight! NERDTreeCWD ctermfg=240 guifg=#777777

highlight! NERDTreeGitStatusModified ctermfg=1 guifg=#D370A3
highlight! NERDTreeGitStatusStaged ctermfg=10 guifg=#A3D572
highlight! NERDTreeGitStatusUntracked ctermfg=12 guifg=#98CBFE
highlight! def link NERDTreeGitStatusRenamed Title
highlight! def link NERDTreeGitStatusUnmerged Label
highlight! def link NERDTreeGitStatusDirDirty Constant
highlight! def link NERDTreeGitStatusDirClean DiffAdd
highlight! def link NERDTreeGitStatusUnknown Comment

function! s:NERDTreeHighlight()
	for l:name in keys(g:NERDTreeIndicatorMapCustom)
		let l:icon = g:NERDTreeIndicatorMapCustom[l:name]
		if empty(l:icon)
			continue
		endif
		let l:prefix = index(['Dirty', 'Clean'], l:name) > -1 ? 'Dir' : ''
		let l:hiname = escape('NERDTreeGitStatus'.l:prefix.l:name, '~')
		execute 'syntax match '.l:hiname.' #'.l:icon.'# containedin=NERDTreeFlags'
	endfor

	syntax match hideBracketsInNerdTree "\]" contained conceal containedin=NERDTreeFlags
	syntax match hideBracketsInNerdTree "\[" contained conceal containedin=NERDTreeFlags
	" setlocal conceallevel=2
	" setlocal concealcursor=nvic
endfunction

augroup nerdtree-highlights
	autocmd!
	autocmd FileType nerdtree call s:NERDTreeHighlight()
augroup END
"}}}
```

This also overcomes an issue where syntax & highlights were lost after creating a file.

**Comment by PhilRunninger** [comment]
@rafi I like the concealed brackets. I might have to try that myself.
