### ISSUE TITLE
NERDTree Bookmark Toogle error

### ISSUE THREAD

**Issue by goodwillhacking** [scrooloose/nerdtree#698]
Operating System: Linux Mint
Vim version `:7.4 Patches 1-52
NERDTree version: `c11affa`
NERDTree settings applied in your vimrc, if any:

ISSUE DESCRIPTION
1. Error was introduced after updating NERDTree. Did not exist in previous version (Not sure of previous version but most definitley more than a year since I last updated)
2. Error occurs when I use "B" to open bookmarks (Tested after commenting out customizations in vimrc.)
My vim customization as it relates to NERDtree does the following: 
1. Opens nerdtree with F3 or automaticaly if no args passed to vim
2. Keep bookmarks menu open by default. Using let NERDTreeShowBookmarks=1
NOTE: (configuration worked fine previously and does not seem to be root cause since commenting them out and manually opening bookmarks using B produces the same error)

![image](https://cloud.githubusercontent.com/assets/3004543/26624066/bd66ec26-45bd-11e7-8d10-d3f3923c0cee.png)

STEPS TO REPRODUCE
Pull most up to date version of NERDTree rev-parse version = c11affa
Just hit B when in nerdtree to try open Bookmarks. This issue did not exist before

ERROR
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..73..72..<SNR>36_toggleShowBookmarks..253..228..249..244..95:
line    1:
E725: Calling dict function without Dictionary: 83
E702: Sort compare function failed

![image](https://cloud.githubusercontent.com/assets/3004543/26624239/45992546-45be-11e7-98a3-bd176002facf.png)

**Comment by lifecrisis** [comment]
Could you try adding the `dict` keyword after [this line](https://github.com/scrooloose/nerdtree/blob/master/lib/nerdtree/bookmark.vim#L256) so that it becomes:

```viml
function! s:Bookmark.SortBookmarksList() dict
```

This may fix your problem.

Also, your Vim installation is quite old. A number of bugs have been fixed since 7.4. Have you considered an update?

**Comment by lifecrisis** [comment]
Friendly nudge to @goodwillhacking...

Do you have any feedback regarding the fix proffered above?

**Comment by goodwillhacking** [comment]
@lifecrisis thank you very much. I simply updated vim and all problems went away. Cheers man
