### ISSUE TITLE
gg mapping to go at ".. (up a dir)" line

### ISSUE THREAD

**Issue by Aster89** [scrooloose/nerdtree#700]
I was wondering whether I'm the only one thinking that mapping `gg` to something like `ggjj` would be useful. It happens a lot that I want to go to the parent directory, but when I press `gg` the cursor obviously goes to the very first line `" Press ? for help`, which has no use at all (but just, say, an informative use), and then I have to press `jj` to go to the first "usable" line, where I can then press `CR`.

**Comment by lifecrisis** [comment]
It looks like what you want are the `P` and `p` macros. Refer to the documentation for descriptions of these and other useful mappings.

I personally think that re-mapping `gg` for this purpose would make little sense. If you want, you can use the NERDTree key map API to implement your own custom mapping (again, see the documentation).

I vote that this issue be closed, @PhilRunninger.

**Comment by PhilRunninger** [comment]
Also check out the `NERDTreeMinimalUI` option in the documentation. It gets rid of the boilerplate at the top.
