### ISSUE TITLE
Selecting more than one item

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [scrooloose/nerdtree#71]
How can I “select more than one item” in a NERDTree, if possible at all?

Specifically, I want to select more than one file (for instance, `foo.h` and `foo.c`) and then use `T` to open them in a new tab, together, as vertical splits. If this isn’t implemented yet, then consider it a feature request (in which case, perhaps it would be nice to be able to use two different commands in sequence, i.e. `Ts` to open a new tab in the background and then open each selected item in a split, or `si` to open a new vsplit and then add each selected item to a horizontal split in that new vsplit.)

**Comment by whitecolor** [comment]
Manipulating multiple items still not possible? 😮

**Comment by cabaalexander** [comment]
2011 🤷‍♂️

**Comment by PhilRunninger** [comment]
I've written another plugin to do this. Its URL is https://github.com/PhilRunninger/nerdtree-visual-selection, and it will open all the files in a visual selection (in either the previous window, in horizontal or vertical splits, or in tabs). It can also delete all the files in a visual selection, after confirmation.
