### ISSUE TITLE
Error detected while processing func tion nerdtree#ui_glue#invokeKeyMap[1]..83[33]..82[3]..<SNR>50_showMenu[2]..57[19]..74[6]..NER DTreeMoveNode[15]..135[2]..46:

### ISSUE THREAD

**Issue by shinokada** [scrooloose/nerdtree#712]
When I try to add a directory, I get the following error. If I add a directory/file then it works though.

I am using vim on MacOS Sierra v 10.12.5. Vim version 8.0.512.

> Error detected while processing func
> tion nerdtree#ui_glue#invokeKeyMap[1]..83[33]..82[3]..<SNR>50_showMenu[2]..57[19]..74[6]..NER
> DTreeMoveNode[15]..135[2]..46:

<img width="867" alt="screen shot 2017-06-20 at 11 17 48 am" src="https://user-images.githubusercontent.com/147320/27313718-5c2ccfe6-55aa-11e7-991c-51f1931b403c.png">

**Comment by PhilRunninger** [comment]
@shinokada , your screenshot shows you are **moving/renaming** a node, but you describe **adding** a directory and then a directory/file. I wasn't able to reproduce the error in my attempt to do so. Can you provide the steps you followed to cause the error?
