### ISSUE TITLE
Shows error when open NERDTree

### ISSUE THREAD

**Issue by eezprince** [scrooloose/nerdtree#718]
_To assist in resolving your issue, provide as much information as possible, in place of the ellipses (`…`) below._

---
**Environment:** _Describe your Vim/NERDTree setup._

>* Operating System: Ubuntu14.04
>* Vim version `:version`: 7.4.52
>* NERDTree version `git rev-parse --short HEAD`: 7ed79c0

**Process:** _List the steps that will recreate the issue._

>1.type :NERDTree

**Current Result:** _Describe what you you currently experience from this process._

Error detected while processing function 184..185..188..151..149..143:
line   20:
E118: Too many arguments for function: globpath
Press ENTER or type command to continue
Error detected while processing function 184..185..188..151..149..143:
line   20:
E15: Invalid expression: globpath(l:pathSpec, a:pattern, !g:NERDTreeRespectWildIgnore, 1)
Press ENTER or type command to continue
Error detected while processing function 184..185..188..151..149..143:
line   20:
E118: Too many arguments for function: globpath

**Expected Result:** _Describe what you would expect to have resulted from this process._

no error shows

**Comment by lifecrisis** [comment]
All of you can solve your problems by updating Vim, but it's quite interesting that version 7.4.52 doesn't have a suitable implementation of `globpath()` to support the highest level of functionality. I'm wondering if some patches from the 7.3 version didn't get included in your build.

Please open Vim and run `:h globpath()`. Report back here with the signature of the `globpath()` function that your version of Vim supports. In version 8.0 of Vim, for example, I would answer with:

```viml
globpath({path}, {expr} [, {nosuf} [, {list} [, {alllinks}]]])
```

If  you are at version 7.4 or higher, you should have at least the first four arguments. This could be the problem with your build.

**Comment by lifecrisis** [comment]
**UPDATE:** After more research, I've identified the problem, and it comes from an inaccurate version check in the NERDTree source code. A fix is in progress.

**Comment by lifecrisis** [comment]
A fix is in production, so you should be able to simply update the NERDTree and have everything working. If you have further problems with a similar error message, we will reopen the issue.

Please report back if the fix was a success or a failure.

**Comment by eezprince** [comment]
Thanks, can't repro now!

**Comment by lifecrisis** [comment]
What is the word "repro"???

**Comment by eezprince** [comment]
https://en.wiktionary.org/wiki/repro

**Comment by lifecrisis** [comment]
LOL, thanks.
