### ISSUE TITLE
A ":NERDTreeRefresh" ex command 

### ISSUE THREAD

**Issue by lifecrisis** [scrooloose/nerdtree#727]
A command for refreshing the NERDTree(s) would be useful. Users could use this command to schedule refresh operations at convenient times (with autocommands) or at intervals (with timers).

**Comment by alexjcardell** [comment]
To clarify, is this proposed command to be like the standard R map?

**Comment by lifecrisis** [comment]
Yes, but callable from any window in the current tab page.

**Comment by wgfm** [comment]
I wanted to see if I could write some vimscript and get something working, so I took the opportunity to implement this in https://github.com/scrooloose/nerdtree/pull/897. It turned out I didn't need to write so much, after all.

I hope my contribution is welcome - I could not find any guidelines.

**Comment by PhilRunninger** [comment]
Implemented in #897. Good job @wgfm. Thanks for contributing.
