### ISSUE TITLE
Remap NERDTreeMapOpenSplit?

### ISSUE THREAD

**Issue by ntzrmtthihu777** [scrooloose/nerdtree#728]
_To assist in resolving your issue, provide as much information as possible, in place of the ellipses (`…`) below._

---
**Environment:** _Describe your Vim/NERDTree setup._

>* Operating System: Gentoo Linux
>* Vim version `:version`: NVIM c0.2.0
>* NERDTree version `git rev-parse --short HEAD`: e2a9929
>* NERDTree settings applied in your vimrc, if any: none

**Process:** _List the steps that will recreate the issue._

>1. I'm probably doing this wrong, but basic gist is I want to remap the NERDTree i and gi
keymaps to h and gh (odd setup, I've relocated the vim movment keys to ijkl inverted T instead of hjkl)
so, I used the command ```:call NERDTreeAddKeyMap({'key': 'h', 'callback': 'NERDTreeMapOpenSplit', 'quickhelpText': 'Opens the selected file in a new split window and puts the cursor in the new window', 'scope': 'all'})```
>2. Select a file and hit 'h'

**Current Result:** _Describe what you you currently experience from this process._

>E21: Cannot make changes, 'modifiable' is off when pressing 'h' in the NERDTree buffer or whatever.

**Expected Result:** _Describe what you would expect to have resulted from this process._

>Normal result of NERDTreeMapOpenSplit

---
In addition, I'd like to be able to free the 'i' key from the NERDTreeMapOpenSplit binding, as it is my 'up' movement key in all normal vim contexts ('h' is my insert mode toggle, works fine in normal contexts).

**Comment by lifecrisis** [comment]
You are making it too complicated. The mapping is configurable with a variable. You need to use the following:

```viml
let g:NERDTreeMapOpenSplit = 'h'
let g:NERDTreeMapPreviewSplit = 'gh'
```

You're use of Vim is weird, my friend. Good luck with it.

**Comment by ntzrmtthihu777** [comment]
@lifecrisis ah! gotcha, thanks, lemme try this.
Works fine! thanks, sorry for the dumb-ish question.
