### ISSUE TITLE
Bindings with backslash causes error

### ISSUE THREAD

**Issue by ecly** [scrooloose/nerdtree#735]
Running vim 8.0.851 on linux, newest nerdtree.
I'm trying to make '\' open the selected file in a new vertical split.
I got it working just fine with Backspace, but can't seem to get '\' working.

It actually registers the bind but merely crashes. The backslash seems to be perhaps escaping a quotation mark?

My bind in my .vimrc looks like this.
```
let NERDTreeMapOpenSplit='<BS>'
let NERDTreeMapOpenVSplit='\'
```

When '\' is pressed on on a file in nerdtree the following error occurs:

```
E114: Missing quote: "\")
E116: Invalid arguments for function nerdtree#ui_glue#invokeKeyMap
```

Is there an alternative way for me to make this bind, or is it not possible with the current interpretation?

**Comment by lifecrisis** [comment]
I was able to confirm this bug.  I would say avoid doing this for now.  This is pretty low priority... we've never seen anyone complain about this before.

**Comment by ecly** [comment]
Definitely not a dealbreaker. I'm merely trying to attain some sort of consistency with split binds for all places applicable. Backspace and backslash are the ones I've gone with, so it's only a slight nuisance. Thanks for confirming for starts!

**Comment by und3rdg** [comment]
Is there any workaround for it? I'm using this key for spiting in many places of my system.

**Comment by ecly** [comment]
@und3rdg I am using for many things as well - never managed to find a workaround.

**Comment by ecly** [comment]
Thank you for this @PhilRunninger it works great.
