### ISSUE TITLE
Unable to use `fugitive :Gwrite`, errors detected when `NERDTree` is on

### ISSUE THREAD

**Issue by sitilge** [scrooloose/nerdtree#736]
---
**Environment:**

* Operating System: `4.12.8-2 generic arch linux`
* Vim version `NVIM v0.2.0`
* NERDTree version 5782b22
* NERDTree settings (letting NERDTreeTabs manage the NERDTree):

   ```
   " Start NERDTreeTabs on GUI if dir selected
   let g:nerdtree_tabs_open_on_console_startup=2
   let g:nerdtree_tabs_smart_startup_focus=2
   let g:nerdtree_tabs_focus_on_files=1
 
   " Show hidden files
   let NERDTreeShowHidden=1
   ```

**Process:**

1. Open a file
2. Run `Glog` from `fugitive` plugin
3. Run `cnext`
4. Run `Gwrite`

**Current Result:** 

![image](https://user-images.githubusercontent.com/3306642/29812473-5635bac6-8caf-11e7-9486-3314c2a0b91f.png)

**Comment by lifecrisis** [comment]
Are you using the [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)?

**Comment by sitilge** [comment]
Yes, I am.  Is it relevant?

On Aug 29, 2017 18:41, "Jason Franklin" <notifications@github.com> wrote:

Are you using the nerdtree-git-plugin
<https://github.com/Xuyuanp/nerdtree-git-plugin>?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/scrooloose/nerdtree/issues/736#issuecomment-325705172>,
or mute the thread

**Comment by lifecrisis** [comment]
It could be. When several plugins are mixed, it's hard to find the error.

You need to run `:scriptnames` to see script in which the error is occurring.  The error message will contain something like `<SNR>_{NUMBER}` ... that's the script number.

Please report what script are involved (the numbers are unique to your configuration).

**Comment by sitilge** [comment]
Hmm, I can't find anything like `<SNR>_{NUMBER}` in the output of `scriptnames`. Just a blanket of 

````
  1: ~/Projects/dotfiles/nvim/.config/nvim/init.vim                                                                    
  2: /usr/share/nvim/runtime/filetype.vim                                                                              
  3: /usr/share/nvim/runtime/ftplugin.vim                                                                              
...                                                             
````

**Comment by lifecrisis** [comment]
See the screenshot you submitted. Match the number from your screenshot with the output of `:scriptnames` ... that tells you the script in which a function was defined.

**Comment by sitilge** [comment]
Oh, sorry. I found that the error comes from `nerdtree-git-plugin/nerdtree_plugin/git_status.vim`

**Comment by lifecrisis** [comment]
No problem. You can report your issue there. If it turns out that we are the source of the problem, let us know and we'll re-open.

**Comment by sitilge** [comment]
@lifecrisis thank you for the support anyway.
