### ISSUE TITLE
Allow NERDTreeIgnore to use paths.

### ISSUE THREAD

**Issue by aemonge** [scrooloose/nerdtree#737]
So I know `let NERDTreeIgnore=['[^pre].*[[dir]]']` will hide all the directories that don't start with **pre** as a prefix. But I would like to apply that rule only to directories under *bower_components* directory.

Ideally something like these two options:
 * `let NERDTreeIgnore=['bower_components\/[^pre].*[[dir]]']`
 * `let NERDTreeIgnore=['bower_components\/[^pre].*[[path]]']`

**Comment by lifecrisis** [comment]
This may require a new option, or an expansion of the meaning of the `g:NERDTreeIgnore` option. I'm hesitant to do this.

**Comment by PhilRunninger** [comment]
@aemonge Disregarding your feature request for a moment, can you confirm your setting is working properly? The way I read it, NERDTree will hide all directories that contain any other character that is not `p`, `r`, or `e`. In other words, it would hide just about everything. To do what you want 

> ... hide all the directories that don't start with **pre** as a prefix.

involves some uncommon regex complexity. Using this [StackOverflow thread](https://stackoverflow.com/questions/406230/regular-expression-to-match-a-line-that-doesnt-contain-a-word) and `:h /\@!` as starting points, you could try this:
```
:let NERDTreeIgnore=['^\(pre\)\@!.*$']
```
Of course this doesn't address your feature request, and outside of the bower_components directory, all directories disappear. To get them back, you need to toggle the file filters with the `f` key, so I understand your request.

I had fun discovering this lesser known capability in regular expressions. Thanks for the question.

**Comment by aemonge** [comment]
@PhilRunninger, thanks a lot for the correction of the RegExp, endeed the final version would have to use your fixed version with @lifecrisis  new feature for path :+1:

**Comment by juanibiapina** [comment]
Why not use `NERDTreeAddPathFilter` ?

**Comment by aemonge** [comment]
@juanibiapina could you provide the function that would work ?     I'm not really used to vimscript so I don't really know how to do it

**Comment by aemonge** [comment]
I've progressed a little bit, but I finally got stucked with the regex. My updated code is as follows:

```
call NERDTreeAddPathFilter('FilterNonCdp')

function! FilterNonCdp(params)
  let pwd=expand('%:p:h')
  let fullPath=join([''] + a:params['path']['pathSegments'], '/')
  let relativePath=substitute(fullPath, pwd, '', '')
  let hasHidableMatch=matchstr(relativePath, '^\bower_components/cdp\\@!.*$')

  " echo '============='
  echo relativePath
  echo hasHidableMatch
  " return 0

  if empty(hasHidableMatch)
    return 0
  endif
  return 1
endfunction
```

My intension is to hide all folder inside (./bower_components) that have not a pre

**Comment by juanibiapina** [comment]
You can use path.str() to get a path representation, should make it easier.

**Comment by aemonge** [comment]
Ohhh !!!   Yes!!! I got complicated without need, OFC ! thanks!

**Comment by aemonge** [comment]
Finall working result:
```
call NERDTreeAddPathFilter('FilterNonPre')

function! FilterNonPre(params)
  let pwd=expand('%:p:h')
  let fullPath=join([''] + a:params['path']['pathSegments'], '/')
  let relativePath=substitute(fullPath, pwd, '', '')
  let inBower=matchstr(relativePath, '/bower_components/')

  if !empty(inBower)
    let hasCdp=matchstr(relativePath, 'bower_components/pre')
    if empty(hasCdp)
      return 1 " ignore
    endif
  endif
  return 0
endfunction

**Comment by lifecrisis** [comment]
Hey @aemonge, thanks for working through this. Also, @juanibiapina, thanks for helping out.

@aemonge, are you satisfied enough to close the issue?

**Comment by aemonge** [comment]
Yes !
