### ISSUE TITLE
How I could set version-order sort?

### ISSUE THREAD

**Issue by unclechu** [scrooloose/nerdtree#742]
For example if I have files like these:
```
1.7.9.ext
1.7.10.ext
1.8.1.ext
1.9.0.ext
1.10.0.ext
```
Their order would be by default:
```
1.10.0.ext
1.7.10.ext
1.7.9.ext
1.8.1.ext
1.9.0.ext
```
That doesn't help at all. But I could sort it by `ls | sort -V` (`--version-sort`) command. How I could do the same for NERDTree? Maybe there's a feature to set kinda sort-order function that gets a list of files and outputs new list that ordered differently that would be simplest way to just pass it to shell command `sort -V`.

**Comment by PhilRunninger** [comment]
Use `let NERDTreeNaturalSort=1` in your vimrc.

**Comment by unclechu** [comment]
@PhilRunninger thanks, works for me!
