### ISSUE TITLE
When NERDTree is on the right, 'open split' command splits NERDTree's buffer

### ISSUE THREAD

**Issue by aperiodic** [scrooloose/nerdtree#75]
After opening a NERDTree buffer, rotate it to the right of the main buffer. Then, open a node using NERDTree's "open split" command by typing "i". Instead of the main buffer being split, NERDTRee's buffer is split.

**Comment by PhilRunninger** [comment]
Use the `g:NERDTreeWinPos` option, with a value of `"right"`, if you want the NERDTree window to be on the right side. If you use `<C-W>L` to move NERDTree to the right, it will nevertheless reappear on the left when you open it again.
