### ISSUE TITLE
Bad NerdTree page handling

### ISSUE THREAD

**Issue by brunovlucena** [scrooloose/nerdtree#750]
environment

    vim: Vi IMproved 7.4
    vim-airline: v0.8
    nerdtree: 5.0.0
    OS: Linux
    Have you reproduced with a minimal vimrc: Did not try
    What is your airline configuration: "let g:airline#extensions#tabline#enabled = 1"

if you are using terminal:

    terminal: zsh
    $TERM variable: screen
    color configuration (:set t_Co?):

actual behavior

If I use NerdTree and open two or three tabs... once i close one of them with :bd, and i navigate through the remaining tabs, the Tree is gonna disapear and behave buggy, so that If i try to open the NerdTree again when the remaining file is selected the NT is gonna take the whole screen.

expected behavior

Work normaly?

![out](https://user-images.githubusercontent.com/20466126/31771331-0280909a-b4dc-11e7-831b-948b74a2bd43.gif)

**Comment by lifecrisis** [comment]
First of all, you aren't opening any tabs, you're opening buffers.  They are simply represented in your tab line by whatever plugin you're using (which, to me, is generally a less productive way to use Vim).

When you delete the buffer, the window you're in automatically closes, leaving only the NERDTree window (containing the NERDTree buffer).  You are then switching buffers within that window, so the NERDTree naturally vanishes (you can open it again with `:NERDTreeToggle`).

It looks to me like you are confusing buffers, windows, and tab pages.  This is common for Vim beginners. Even some people who have used Vim for a while fail to understand the distinction (this happened to me).  See [this link](https://stackoverflow.com/questions/26708822/why-do-vim-experts-prefer-buffers-over-tabs#26710166) for an in-depth explanation.  Also, you should read some of `:h windows.txt`.

There's no bug here, so I will close this issue. This is just how Vim works, and you need to be aware of it.
