### ISSUE TITLE
NERDtree opens all files as empty

### ISSUE THREAD

**Issue by davidcbenson** [scrooloose/nerdtree#758]
_To assist in resolving your issue, provide as much information as possible, in place of the ellipses (`…`) below._

---
**Environment:** _Describe your Vim/NERDTree setup._

OS: Windows 10
Version: gvim 8.0

NERDTree version: 45f4d61

NERDTree Settings: 

autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

**Process:** 

>  1. Open vim to any file from the command line.
> 2. NERDTree opens automatically.
>  3. Select a file in NERDTree and press 'o' to open in the main window, or 't' to open in a new tab

**Current Result:** _

> Whether I open the file in the current window or in a new tab, the file opens as empty. When listing it in the buffer it shows the file as being in a "NEW DIRECTORY" but the path is the directory of file I intended to open. If I save the file, it will overwrite the file with a blank file.

**Expected Result:**

> I expect the file to open as I believe I am telling it to do.

I have not poked around in the code, as honestly I have no idea what the problem could be to look for a solution, since apparently the path is correct.

**Comment by lifecrisis** [comment]
Please clarify your process by giving specific commands that we can run in a Vim 8.0/Windows 10 setup to reproduce the bug.  Thanks!

**Comment by davidcbenson** [comment]
Unfortunately, I have long since uninstalled NERDTree, and in the interim my computer crashed, and had to be completely restarted. I can reinstall NERDTree and see if the problem persists, if you think that might be helpful for resolving the bug.

**Comment by PhilRunninger** [comment]
Thanks, but that's not necessary. Closing...
