### ISSUE TITLE
Support collapsing directories with only one subdirectory.

### ISSUE THREAD

**Issue by trygvis** [scrooloose/nerdtree#76]
When working with Java code I often have a rather deep directory structure and it would be nice if the plugin could use less space to render them.

Today:

```
▾ web/
  ▾ src/
    ▾ main/
      ▾ scala/
        ▾ com/
          ▾ company/
            ▾ webshop/
                Foo.java
    ▾ test/
      ▾ scala/
        ▾ com/
          ▾ company/
            ▾ webshop/
                FooSpec.java
```

Possible example:

```
▾ web/src/
  ▾ main/scala/com/company/webshop/
    Foo.java
  ▾ test/scala/com/company/webshop/
    FooSpec.java
```

**Comment by samtstern** [comment]
Bump, this would be great to have.

**Comment by juanibiapina** [comment]
I think this is currently implemented, because I came here looking for a way to disable it.

**Comment by shannonmoeller** [comment]
I find this feature annoying and would like an option to turn it off.
