### ISSUE TITLE
Using vim when logging through Putty to a remote server doesnt display arrows correctly in nerdtree

### ISSUE THREAD

**Issue by alphaCTzo7G** [scrooloose/nerdtree#760]
**Environment:** _Describe your Vim/NERDTree setup._

>* Operating System: …
Ubuntu
>* Vim version `:version`: …
VIM 7.4
**Process:** _List the steps that will recreate the issue._

>1. …I have solved the problem, after working through 

https://serverfault.com/questions/475925/how-to-fix-putty-showing-garbled-characters

and

https://github.com/scrooloose/nerdtree/issues/522

However, since there are a lot of people using Putty, and using nerdtree, is it possible to potentially somehow check if they are using putty, and give a warning about a incorrect font or switch to a better font?

The option would be to provide this as a faq.

**Comment by PhilRunninger** [comment]
Is there anything in the remote system's environment to indicate that it is being launched in a Windows Putty application? An environment variable, perhaps? If yes, then you could put an `if` block in your vimrc to set the arrows to something else. That's the only way I can imagine being able to do this. I have no way to test this on my setups.

**Comment by PhilRunninger** [comment]
Based on this [stackexchange post](https://unix.stackexchange.com/questions/9605/how-can-i-detect-if-the-shell-is-controlled-from-ssh), you need to use this code in the vimrc of the remote system:
```vim
if exists('$SSH_CLIENT') || exists('$SSH_TTY')
    let g:NERDTreeDirArrowExpandable = '+'
    let g:NERDTreeDirArrowCollapsible = '~'
endif
```
I'm closing this issue. If this code doesn't solve your issue, reopen it.
