### ISSUE TITLE
Latest update throws "Error detected while processing User Auto commands for 'NERDTreeInit'"

### ISSUE THREAD

**Issue by JESii** [scrooloose/nerdtree#763]
**Environment:** _Describe your Vim/NERDTree setup._

>* Operating System: macOS Sierra (10.12.6)
>* Vim version `:version`: 8.0-1250
>* NERDTree version `git rev-parse --short HEAD`: b6e3c0d
>* NERDTree settings applied in your vimrc, if any:
>
>   ```
>   function! StartUp()
>     if 0 == argc()
>       NERDTree
>     end
>   endfunction
>   ```

**Process:** _List the steps that will recreate the issue._

>1. vim

**Current Result:** _Describe what you you currently experience from this process._

>1. Get multiple errors on startup:
```
Error detected while processing User Auto commands for "NERDTreeInit":
E121: Undefined variable: b:NERDTreeRoot
Press ENTER or type command to continue
Error detected while processing User Auto commands for "NERDTreeInit":
E116: Invalid arguments for function fugitive#detect
Press ENTER or type command to continue
Error detected while processing User Auto commands for "NERDTreeInit":
E121: Undefined variable: b:NERDTreeRoot
Press ENTER or type command to continue
Error detected while processing User Auto commands for "NERDTreeInit":
E116: Invalid arguments for function ProjectionistDetect
Press ENTER or type command to continue
```
> 2. Once the errors have displayed, I get the usual startup with NERDTree in the left window and an empty window on the right.

> 3. If I start vim with a file, then there is no error

> 4. If I start vim with a file, then run :NERDTree inside vim, then I get the same errors as above, except no prompting for each error:
```
Error detected while processing User Auto commands for "NERDTreeInit":
E121: Undefined variable: b:NERDTreeRoot
E116: Invalid arguments for function fugitive#detect
E121: Undefined variable: b:NERDTreeRoot
E116: Invalid arguments for function ProjectionistDetect
Press ENTER or type command to continue
```

**Expected Result:** _Describe what you would expect to have resulted from this process._

> No startup errors; as it was before the upgrade

---
**Optional**

**Screenshot(s):**

![image](https://user-images.githubusercontent.com/486/32799193-d2b5bb24-c92b-11e7-8276-43f2acb05890.png)

**Possible Fix:** _(Have you poked around in the code?)_

> Nope

**Comment by PhilRunninger** [comment]
I can confirm this error, and it requires you to also have fugitive installed.

It looks like this error is related to an interaction between Fugitive and NERDTree. This commit
https://github.com/scrooloose/nerdtree/commit/2cb0fc78fb4c7a1db5f51c042a447cc50f09983d introduced the NERDTreeInit autocommand so that Fugitive could be signaled when certain events happen in NERDTree. @lifecrisis, it looks like your refactoring caused `b:NERDTreeRoot` to be left unset when the autocommands are being processed.

**Comment by JESii** [comment]
Not a NERDTree bug -- both fugitive and projectionist are still using the deprecated NERDTreeRoot variable, instead of the new NERDTree.root. Closing this issue. There's already a pull request for fugitive and I'll check on projectionist. Thanks!

**Comment by PhilRunninger** [comment]
We can restore this [line of code](https://github.com/scrooloose/nerdtree/commit/b6e3c0db30aea2875da5d9214f05b6586ac7af7c#diff-ea67037158059f5e6f5239b3090f9f30L116) to bring back the compatibility that was being maintained. Or we could leave it out, and encourage fugitive, projectionist, and possibly other plugins to update their code. I don't see a problem putting it back in. What do you think, @lifecrisis?

**Comment by lifecrisis** [comment]
@PhilRunninger 

Ahh, I misunderstood the comment. Yeah, we should probably do both: add it back and encourage the other plugin authors to update.

**Comment by lifecrisis** [comment]
Update now, and you'll get the fix. Thanks.

**Comment by JESii** [comment]
FYI... I submitted a pull request to projectionist to handle this (supporting either one), and I see that someone else submitted a similar change to fugitive.

**Comment by lifecrisis** [comment]
Thanks, @JESii.  It's not like it's a critical problem, but it would be nice to gradually remove some of the deprecated code.
