### ISSUE TITLE
E121: Undefined variable: b:NERDTreeRoot

### ISSUE THREAD

**Issue by katylava** [scrooloose/nerdtree#764]
---
**Environment:** _Describe your Vim/NERDTree setup._

>* Operating System: Mac OS
>* Vim version `:version`: NVIM v0.2.1
>* NERDTree version `git rev-parse --short HEAD`: b6e3c0d
>* NERDTree settings applied in your vimrc, if any:
>
>  ```
>  let NERDTreeIgnore = ['\.pyc$']
>  let NERDTreeWinSize = 45
>  let NERDTreeShowHidden=1
>  ```

**Process:** _List the steps that will recreate the issue._

1. Open any file
2. `:NerdTreeToggle`

**Current Result:** _Describe what you you currently experience from this process._

It works but I see this error:
> Error detected while processing User Auto commands for "NERDTreeInit":
> E121: Undefined variable: b:NERDTreeRoot

**Expected Result:** _Describe what you would expect to have resulted from this process._

I shouldn't see any error messages.

This just started happening after I upgraded. Looks to be related to 0a0374b826dcdb3cdee4b40393205c16c744aa8c.

**Comment by PhilRunninger** [comment]
This is the same bug reported in #763. What other plugins do you have installed?

**Comment by katylava** [comment]
Ah sorry, my google-fu failed me.

So yeah, I also have fugitive. I got error from that too but since I'd upgraded all plugins I didn't know it was related. I'll close this and open an issue with fugitive, unless someone already has.

**Comment by katylava** [comment]
FYI there is already a fugitive issue and PR: https://github.com/tpope/vim-fugitive/pull/966

**Comment by lifecrisis** [comment]
@katylava... yeah we'll add that back... People should update, but I'm not going to force them.

**Comment by lifecrisis** [comment]
Just update to get the fix. Thanks.

**Comment by chocoelho** [comment]
vim-fugitive is now using `NERDTree.root` 😃
