### ISSUE TITLE
when i start vim NERDTree auto opens in ~.

### ISSUE THREAD

**Issue by NikosEfthias** [scrooloose/nerdtree#770]
_To assist in resolving your issue, provide as much information as possible, in place of the ellipses (`…`) below._

---
**Environment:** _Describe your Vim/NERDTree setup._

>* Operating System: `OSX HIGH-SIERRA`
>* Vim version `:version`: `NVIM v0.2.0`
>* NERDTree version `git rev-parse --short HEAD`: …
>* NERDTree settings applied in your vimrc, if any:
>
>   ```
>  noremap <Leader>n :NERDTreeToggle<CR>
>   ```

**Process:** _List the steps that will recreate the issue._

>1. Open vim
>2. NerdTree opens by default

**Current Result:** _Describe what you you currently experience from this process._

>nerdTree opens by default

**Expected Result:** _Describe what you would expect to have resulted from this process._

>Not to open it until i want so

---
**Optional**
This behavior is so annoying will make me uninstall nerdtree soon if i cant find a workaround
**Screenshot(s):**

>…

**Possible Fix:** _(Have you poked around in the code?)_

>…

**Comment by lifecrisis** [comment]
The only possible solution would be to try removing your lone mapping.  There is nothing in the NERDTree plugin that would cause the tree to open automatically.  Have you added an autocommand that does this?

**Comment by PhilRunninger** [comment]
@NikosEfthias Get rid of this line in your init.vm file: https://github.com/NikosEfthias/vimrc/blob/master/init.vim#L99. This autocommand is opening NERDTree when you start neovim.

**Comment by NikosEfthias** [comment]
Thanks it solves the issue so it turns out it was my fault. Thank you @PhilRunninger
