### ISSUE TITLE
Opening NERDTree automatically is conflict with g:NERDTreeQuitOnOpen?

### ISSUE THREAD

**Issue by run27017** [scrooloose/nerdtree#771]
I want to set both functions through below code in .vimrc:

```vimL
let g:NERDTreeQuitOnOpen=0
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | execute 'NERDTreeTabsOpen' | endif
```

When I open vim by `vim` command, the NERDTree panel opened automatically. However, the NERDTree panel does not opened when I type `t` in some file node.

---
Environment:

>* Operating System: openSuse 42.2
>* Vim version: VIM - Vi IMproved 7.4 (2013 Aug 10)
>* NERDTree version: e0e36c5
>* NERDTree settings applied in your vimrc, if any:
>
> ```vimL
> let g:NERDTreeQuitOnOpen=0
> autocmd StdinReadPre * let s:std_in=1
> autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | execute 'NERDTreeTabsOpen' | endif
> ```

**Comment by lifecrisis** [comment]
The `t` mapping will open the selected file in a new tab. Since NERDTree windows are local to a particular tab, you won't automatically see a new NERDTree in the new tab.

There isn't a bug here, that's just how the NERDTree works.  I recommend closing this issue, pending review by @PhilRunninger.

**Comment by PhilRunninger** [comment]
Agreed. See https://github.com/scrooloose/nerdtree/wiki/F.A.Q.#can-i-have-the-nerdtree-on-every-tab-automatically in the Wiki's FAQ page for more information.

**Comment by run27017** [comment]
Thanks at all.
