### ISSUE TITLE
replacing first tab name with real one

### ISSUE THREAD

**Issue by Mamad026** [scrooloose/nerdtree#774]
Hi there.
When I open a new tab with NERDTree the first tab named "2 NERD_tree_1" but I want to name that tab with buffer name as common on other tabs. 
Please let me know how can I fix that?
Thanks.

**Comment by PhilRunninger** [comment]
The label you see on the tab is the active buffer of that tab, so it means that your cursor is still in the NERDTree on that tab. This is the default behavior of Vim, and isn't something I want NERDTree to be interfering with. A quick Google search led me to this StackExchange post: https://superuser.com/questions/715928/vim-change-label-for-specific-tab.

**Comment by Mamad026** [comment]
Many thanks.

**Comment by westurner** [comment]
That's not a useful name: the default behavior is not indicative of the state of the buffer.

If the 'NERD_tree_1' text is helpful for something, would it be possible to append the PWD?

**Comment by taufik-nurrohman** [comment]
~~~ .vim
autocmd BufEnter NERD_tree_* call SomeFunctionToChangeTheTabLabel
~~~
