### ISSUE TITLE
A newly written file cannot be found with NERDTreeFind

### ISSUE THREAD

**Issue by lifecrisis** [scrooloose/nerdtree#779]
To replicate:

1. Open Vim in home directory.
2. Open the NERDTree.
3. In the empty buffer to the right, run command `:w test.txt`.
4. Next, run `:NERDTreeFind`.
5. View the error... 

Looks like a refresh is needed before `:NERDTreeFind` is run.

**Comment by lifecrisis** [comment]
Making a note here that several issues may be possible duplicates of this issue... no time to look into it right now.

**Comment by juanibiapina** [comment]
I have the problem in my fork, but you can't just force a refresh because it might be very slow for some directory trees.

**Comment by lifecrisis** [comment]
There are a few things that need to be dealt with here: 

- [ ] `findAndRevealPath()` needs to be updated to remove some duplication and use better style
- [ ] the documentation for `:NERDTreeFind` has to be modified to reflect the new behavior (directories as well as files can now be found and an argument can be passed)
- [ ] an efficient method needs to be developed to show the new file (i.e., something faster than a full refresh)

I'm doing some work on this right now...

**Comment by lifecrisis** [comment]
For some reason this didn't get closed...

Closing now.

**Comment by lifecrisis** [comment]
I had to reopen this issue because the fix that was added in #785 caused problems reported in #793.  A new fix will have to be devised and added later.

**Comment by PhilRunninger** [comment]
This seems to be working now too.

**Comment by juanibiapina** [comment]
When was the actual fix introduced?

**Comment by PhilRunninger** [comment]
From what I can piece together, #785, merged on 12/22/17 ,fixed this issue, but introduced issue #793, which was reported on 1/2/18. PR #794 fixed that bug when it was merged on 1/5/18.

**Comment by juanibiapina** [comment]
My understanding is that #794 removed the whole fix for this.

**Comment by lifecrisis** [comment]
@PhilRunninger, the fix was removed.  I don't remember the reason, but I remember thinking it was a good idea at the time... so this is still broken, unfortunately.

**Comment by juanibiapina** [comment]
This is how I fixed it on my fork: https://github.com/juanibiapina/vim-lighttree/blob/edd2da237f615441012679f47c371494966dafa1/autoload/lighttree.vim#L46

I just refresh the whole tree if the node cannot be found. For me that's a good trade off between speed and correctness, because the refresh only happens if the node cannot be found.

The code there has diverged considerably, but a similar fix should be possible here.

**Comment by rstacruz** [comment]
This still happens to me when, for example, using :NERDTreeFind with [vim-startify](https://github.com/mhinz/vim-startify).

A workaround is to use `:silent! NERDTreeFind`  rather than just `:NERDTreeFind`.

**Comment by PhilRunninger** [comment]
@rstacruz Your comment is the exact issue reported in #1059, which has just been resolved with the merging of pull request #1081.
