### ISSUE TITLE
Group sequentially numbered files

### ISSUE THREAD

**Issue by jimgreen** [scrooloose/nerdtree#783]
When there are many files in a same folder, it is hard to find a specific files. It might be useful if we can group certain files. Say, group
```
file_1.txt
file_2.txt
file_3.txt
```
as
```
file_*.txt
```

and allows to click into it to access specific file.

An example:
![](http://www.cfdyna.com/Home/OpenFOAM/openVTKfile.png)

**Comment by PhilRunninger** [comment]
That's a neat idea, but NERDTree is already bloated beyond reason. Adding another level of grouping would be both difficult and slow.
