### ISSUE TITLE
Session: change to the correct directory after SessionLoad

### ISSUE THREAD

**Issue by tuxflo** [scrooloose/nerdtree#784]
**Environment:** _Describe your Vim/NERDTree setup._

>* Operating System: KDE Neon
>* Vim version `:version`: 8.0
>* NERDTree version `git rev-parse --short HEAD`: latest (fresh install)
>* NERDTree settings applied in your vimrc, if any:
>  ```
> autocmd StdinReadPre * let s:std_in=1
> autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' >argv()[0] | wincmd p | ene | endif
>
> " close vim and NERDTree if no file is open and we try to close vim
> autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == > > "primary") | q | endif
> ```

**Process:** _List the steps that will recreate the issue._

>1.Change to working dir, setup NERDTree (using cd/C), Open some buffers 
>2. Save a session using vim-session (SessionSave <name>)
>3. Close vim
>4. Open vim and restore the Session (using SessionLoad <name>)

**Current Result:** _Describe what you you currently experience from this process._

> When using NERDTreeToggle the home directory is shown.

**Expected Result:** _Describe what you would expect to have resulted from this process._

> After opening NERDTree, the "correct" directory (as set in step 1.) is opened.

**Comment by tuxflo** [comment]
Hey Phil,
I just tried using `cd` (I actually really thought `C` is a `cd` and a directory change in NERDTree) but the problem still remains. After step 4 `:pwd` shows the right directory, but what I would expect is, that NERDTree changes the location to that position too as I would do manually with `C`.

If your working project is in a deep file tree it kind of sucks, that one always have to change the NERDTree root manually to focus only on project files.

**Comment by PhilRunninger** [comment]
Is NERDTree already open when you restore the session? I just tried that scenario, and it reproduces your issue. The steps I followed are listed below, with the last step being the solution. This is as good as it gets, because session files cannot contain enough information to restore a NERDTree window. It's still a manual step, but at least `CD` doesn't require you to navigate to the potentially deep folder before pressing `C`.
```
$ cd ~
$ vim
:NERDTreeToggle         " NERDTree is rooted in ~
:so fubar/session.vim   " This session file sets CWD to be ~/fubar.
:NERDTreeToggle         " NERDTree still shows ~ as its root, because it just redisplays the existing buffer.
CD                      " This NERDTree command changes its root to be the same as CWD.
```
