### ISSUE TITLE
NerdTree-open does not work in symlinked difrectory

### ISSUE THREAD

**Issue by baserge** [scrooloose/nerdtree#790]
Open function does not work in the symlinked directory.  No reaction to either Enter or o.

>* Operating System: linux mint 18.4
>* Vim version `:version`: 7.4
>* NERDTree version `git rev-parse --short HEAD`: 57788ab
>* NERDTree settings applied in your vimrc, if any: none

**Comment by lifecrisis** [comment]
This was some time ago.  Just now getting to it.

Can you provide commands to create a sample directory hierarchy so that we can *precisely* reproduce your problem?  That would help us take care of this.

**Comment by PhilRunninger** [comment]
A bunch of changes where merged in last night. Update your NERDTree and try again. If the issue persists, please provide additional details so we can properly diagnose it and provide a solution.

**Comment by PhilRunninger** [comment]
I suspect this error was fixed by #896, thus I'm going to close this issue. If the issue still persists, then provide details and reopen the issue.
