### ISSUE TITLE
what does these  'brace' mark mean?

### ISSUE THREAD

**Issue by SailorCrane** [scrooloose/nerdtree#798]
![brace](https://user-images.githubusercontent.com/7468849/35433990-743af87e-02c0-11e8-91a7-5c269b7f3249.png)

**Comment by PhilRunninger** [comment]
The word inside the braces is a bookmark name, and your NERDTree is focused on the nodes (file or folder) that those bookmarks point to. Press `B` in the NERDTree to show or hide the bookmarks at the top of the window.
