### ISSUE TITLE
After cloned into vim/boundle then what?

### ISSUE THREAD

**Issue by jinfagang** [scrooloose/nerdtree#799]
Hi, forgive my stupid question....I just cloned, and using vim open a new txt file, when I am input :nerdtree there nothing happend. How to open nerdtree exactly?

**Comment by PhilRunninger** [comment]
You haven't given much information to work with. 
1. The first thing to try is `:NERDTree`. Commands in vim are case-sensitive.
1. If that doesn't work, you need to see if NERDTree is installed properly. Run the command `:set rtp?` in vim. If you don't see the `vim/boundle/nerdtree/` folder in the output, you haven't installed NERDTree correctly. I am guessing that you're using a plugin manager like `Vundle` or `pathogen`. Check its documentation to see what needs to change.

If neither of these steps yield results for you, post another comment with more details about your setup: relevant directory structure, .vimrc file, etc.

**Comment by PhilRunninger** [comment]
@jinfagang Are you still having issues with your NERDTree setup? If your issue is solved, please close it.

**Comment by lifecrisis** [comment]
This looks like a typical beginner question... No offense, of course! Keep trying! :-)

I would suggest using Vundle to install the NERDTree.  It's one of the better package managers for vim that is currently available.  Read the documentation on that tool, and you should be fine.

Best of luck.
