### ISSUE TITLE
[feature request] Option to open file directly after creating it

### ISSUE THREAD

**Issue by arcseldon** [scrooloose/nerdtree#802]
Thanks so much for this awesome plugin - use it all the time.

One thing that I'd really like to do, is use the `m` then `a` option to create a new file, then have it opened into a buffer window. So instead of `<cr>`, have some other keyboard option for creation, and opening it automatically into the buffer.  Realise it only saves a couple of keystrokes - but, where for example, you haven't yet opened the directory into which you have created the new file, it is a couple more keystrokes to open. And I find 99% of the time, when i am creating a new file, would also like to edit it too.  Finally, my apologies if I did overlook an existing option for this in NerdTree. I tried googling, and reading the official docs (via vim) but didn't see it. Also, tried using `?` within the NerdTree window.  Again, thank you.

**Comment by lifecrisis** [comment]
Hey @arcseldon, we appreciate you contacting us.

There's nothing wrong with your wanting this, but I don't think we, as the maintainers should focus our time on implementing this kind of functionality.  To solve your problem, you should investigate adding a new, custom menu item.  See `:h NERDTreeMenuAPI` for more information.

Unfortunately, we can't implement every feature that any user wants, so we recommend the use of the APIs whenever possible. Best of luck.
