### ISSUE TITLE
Disable question mark to toggle help

### ISSUE THREAD

**Issue by okaymaged** [scrooloose/nerdtree#803]
My finger memory is too used to using question mark as a reverse search. Is it possible to disable '?' to toggle quickhelp?

**Comment by PhilRunninger** [comment]
Most keys in NERDTree are configurable. See `:h NERDTreeMappings`. The specific one you want to change is here: `:h NERDTree-?`. You can put this in your vimrc to override the question mark:

```
let g:NERDTreeMapHelp = '<F1>'
```

**Comment by okaymaged** [comment]
Great, thanks!
