### ISSUE TITLE
What dose the list option do?

### ISSUE THREAD

**Issue by nirgivon** [scrooloose/nerdtree#805]
After pressing the m option, there is a l fir list option.
What dose it do? there so information in the documentation...

I suspect it copes the files name/path to be used but i cant get it to work...

---
>* windows
>* gVim 8.0

**Comment by kutsan** [comment]
It gives you to the value of `ls -l` for that node in the command line. It's basically the same thing with `:!ls -l file` where `file` is your relative or absolute file path.

**Comment by PhilRunninger** [comment]
In Windows, the output is the result of the `DIR /Q` command, which shows filename, modification date/time, file size, and owner of the selected file. @nirgivon , please close this issue if it answers your question. Thanks.

**Comment by nirgivon** [comment]
Thanks!
