### ISSUE TITLE
How to remove the path line at the first line of NERDTree?

### ISSUE THREAD

**Issue by kutsan** [scrooloose/nerdtree#806]
Since I can see the path via `statusline` of NERDTree buffer, showing in there too is kind of pointless. How can I remove that first line?

![](https://user-images.githubusercontent.com/10108377/36358546-470873f4-1521-11e8-9481-962b3bff93ff.png)

**Comment by PhilRunninger** [comment]
There is no way built into NERDTree to remove the root line, but you can customize the statusline. See `:h NERDTreeStatusline`.

I've never played around with Vim's conceal feature. Is it able to hide an entire line? That may be an option for you to dig into.

**Comment by kutsan** [comment]
Thanks @PhilRunninger. I think conceal may work, I'll come back if I find proper solution.

**Comment by kutsan** [comment]
It's possible to hide that with this.

```vim
augroup nerdtreehidecwd
	autocmd!
	autocmd FileType nerdtree syntax match NERDTreeHideCWD #^[</].*$# conceal
augroup end
```

**Comment by kutsan** [comment]
Also screenshot:

![](https://i.imgur.com/dNz7nRg.png)

**Comment by PhilRunninger** [comment]
Awesome! For those who come across this in the future, note that you also need to turn concealment on; it's off by default. An easy way to do that is to add `setlocal conceallevel=3` to the autocmd, like so:
``` vim
augroup nerdtreehidecwd
	autocmd!
	autocmd FileType nerdtree setlocal conceallevel=3 | syntax match NERDTreeHideCWD #^[</].*$# conceal
augroup end
```

**Comment by kutsan** [comment]
Right, I forgot about that because `vim-devicons` plugin sets that to `3` automatically but better to yourself.

**Comment by cevhyruz** [comment]
for those who has `cursorline` enabled, you also need to set `concealcursor` to prevent text from displaying  when cursorline and concealed text were on the same line.
```
augroup nerdtreehidecwd
  autocmd!
  autocmd FileType nerdtree setlocal conceallevel=1
  \ | syntax match NERDTreeHideCWD #^[</].*$# conceal
  \ | setlocal concealcursor=n
augroup end

```

**Comment by KoBruhh** [comment]
![1679726862 screensht](https://user-images.githubusercontent.com/101834410/227701816-dc79ea1c-3106-4625-bff8-2adcca9e741c.png)

According to my configuration file It has 2 lines of margin (after It has removed the current path)

Here is the part that is about NERDTree:

```vim
let NERDTreeShowHidden=1
let NERDTreeMinimalUI=1
let NERDTreeShowBookmarks=1
" let NERDTreeShowLineNumbers=1
let NERDTreeWinPos="right"
let NERDTreeWinSize=30
let g:NERDTreeDirArrowExpandable = ' '
let g:NERDTreeDirArrowCollapsible = ' '

" Hide the current working directory in NERDTree
augroup nerdtreehidecwd
  autocmd!
  autocmd FileType nerdtree setlocal conceallevel=3
          \ | syntax match NERDTreeHideCWD #^[</].*$# conceal
          \ | setlocal concealcursor=n
augroup end

map <C-a> :NERDTreeToggle<CR>
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

" Exit Vim if NERDTree is the only window remaining in the only tab.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif


```
