### ISSUE TITLE
How can I remove the slashes after each directory node?

### ISSUE THREAD

**Issue by kutsan** [scrooloose/nerdtree#807]
Colors and icons already explaining it's a directory. Having extra `/` for each one isn't looking good. Is there any way to remove those slashes?

![](https://user-images.githubusercontent.com/10108377/36358546-470873f4-1521-11e8-9481-962b3bff93ff.png)

**Comment by PhilRunninger** [comment]
The trailing slash is used in the syntax file to differentiate between directories and files when it comes to highlighting. Without digging into the code further, I think there are other areas where that trailing slash is important.

**Comment by kutsan** [comment]
Another job for conceal. ><

**Comment by kutsan** [comment]
I managed to solve this problem by doing this.

```vim
augroup nerdtreehidetirslashes
	autocmd!
	autocmd FileType nerdtree syntax match NERDTreeDirSlash #/# containedin=NERDTreeDir conceal contained
augroup end
```

**Comment by kutsan** [comment]
Now it looks like, like this:

![](https://i.imgur.com/dNz7nRg.png)

**Comment by PhilRunninger** [comment]
Awesome! For those who come across this in the future, note that you also need to turn concealment on; it's off by default. An easy way to do that is to add `setlocal conceallevel=3` to the autocmd, like so:
``` vim
augroup nerdtreehidecwd
	autocmd!
	autocmd FileType nerdtree setlocal conceallevel=3 | syntax match NERDTreeDirSlash #/$# containedin=NERDTreeDir conceal contained
augroup end
```

**Comment by NikosEfthias** [comment]
@kutsan how did you get all those fancy icons and stuff and are they terminal compatible ?

**Comment by kutsan** [comment]
It's just a custom font and that font has glyphs inside it. You can use those glyphs like I did. Check out those link.

- https://github.com/ryanoasis/nerd-fonts
- https://github.com/ryanoasis/vim-devicons
- https://github.com/tiagofumo/vim-nerdtree-syntax-highlight

To be honest, it's little hard to setup.

**Comment by cevhyruz** [comment]
This doesn't seem to work with vim8.1

**Comment by cevhyruz** [comment]
@kutsan weird.. It doesn't work on my vimrc but if I manually type this on commandline it works.

**Comment by cevhyruz** [comment]
Okay so its working now.. silly me! :p
