### ISSUE TITLE
nerdTree wont close after running :grep and getting results

### ISSUE THREAD

**Issue by SpikePy** [scrooloose/nerdtree#808]
**Environment:** using ripgrep as :grep command, let g:NERDTreeQuitOnOpen = 1

>* Operating System: arch linux
>* Vim version `8`

**Current Result:** _If I open vim in a directory like "vim ." i see nerdtree in this window. if i then :grep "someCode" it opens another 2 windows. one with the first result file and the quicklist but nerdtree is also still open_

**Expected Result:** _nerdTree should be closed if there were matches found and stay open if no matches were found, just like netrw behaves_

**Screenshot(s):**
![image](https://user-images.githubusercontent.com/16565183/36410772-cd884fb6-1612-11e8-9f18-a2e9b7f7baec.png)

**Comment by lifecrisis** [comment]
Try putting this in your `vimrc` file:

```vim
autocmd QuickFixCmdPost * if len(getqflist()) > 0 | NERDTreeClose | endif
```

If that works for you, please close this issue.

**Comment by lifecrisis** [comment]
I see.  I didn't read closely enough.  It looks like you opened the tree with the `vim .` command.  If you had opened Vim with `vim` and then run `:NERDTree` the autocommand above would work.

When you use `vim .` or `:edit .`, you are opening the NERDTree in a normal Vim window, not in a side bar. In other words, it is *supposed* to stay open in this case.  You'll have to investigate to find your own custom solution in this case.  It's not in our project's scope to prescribe exactly when a NERDTree window should be closed automatically or kept open.

**Comment by SpikePy** [comment]
ok, so my workaround is closing the filebrowser when starting vim with a directory as argument like this:
`autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) | bd | endif`
