### ISSUE TITLE
:tabprev and :tabnext does not work

### ISSUE THREAD

**Issue by smilesun** [scrooloose/nerdtree#810]
**Environment:** _Describe your Vim/NERDTree setup._

>* Operating System: Ubuntu 14.04 LTS
>* Vim version `:version`: …
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 27 2017 13:21:44)
Included  patches: 1-1349
>* NERDTree version `git rev-parse --short HEAD`: … e47e588
>* NERDTree settings applied in your vimrc, if any:
1.
nnoremap <f1> :NERDTreeTabsToggle<cr>
inoremap <f1> <nop>
vnoremap <f1> <nop>
2.
" nerdtree settings
let g:NERDTreeMouseMode = 2
let g:NERDTreeWinSize = 40
let NERDTreeShowHidden = 1          " show hidden files
let NERDTreeIgnore = ['\.git$']     " dont show swp files in tree
let NERDTreeQuitOnOpen = 0          "dont close after open

>   ```
>   …
>   ```

**Process:** 
I press F1 to execute the :NERDTreeTabsToggle, then  I enter one file and another file, but running shift+arrow or :tabprev or :tabnext does not navigate across the two opened tags. 
>1. …

**Current Result:** _Describe what you you currently experience from this process._

>…

**Expected Result:** _Describe what you would expect to have resulted from this process._

>…

---
**Optional**
I have a huge bunch of plugins, is there an official website to check the consistency of all those plugins?
**Screenshot(s):**

>…

**Possible Fix:** _(Have you poked around in the code?)_

>…

**Comment by PhilRunninger** [comment]
It looks like you have **NERDTree** confused with a different plugin: [vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs) Try reporting your issue there. The project owner says it's no longer being maintained, but maybe someone watching the repository will have an answer for your question.
