### ISSUE TITLE
Messed up nerdtree window while restoring vim session by tmux-resurrect

### ISSUE THREAD

**Issue by L-Jovi** [scrooloose/nerdtree#812]
**Environment:** _Describe your Vim/NERDTree setup._

>* Operating System: macOS version: 10.13.3
>* Vim version `:version`: 8.0
>* NERDTree version `git rev-parse --short HEAD`: 97d2d70

>* NERDTree settings applied in your vimrc, if any:
>
```
    " NERDTREE
    " {
        autocmd vimenter * NERDTree
        autocmd VimEnter * wincmd p
        autocmd StdinReadPre * let s:std_in=1
        autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
        autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
        let NERDTreeShowHidden=1
        let g:NERDTreeWinPos = "left"
        let g:NERDTreeWinSize = 20
        map <Leader>n <plug>NERDTreeTabsToggle<CR>
    " }
```

**Process:** _List the steps that will recreate the issue._

>1. Install and config [tmux-plugins/tmux-resurrect](https://github.com/tmux-plugins/tmux-resurrect) and [tpope/vim-obsession](https://github.com/tpope/vim-obsession)

>2. Follow tmux-resurrect step to restore vim session

>3. Encounter messed up nerdtree window.

**Current Result:** _Describe what you you currently experience from this process._

> I ask for help from [tmux-resurrect/issues/239](https://github.com/tmux-plugins/tmux-resurrect/issues/239) and the author consider excluding tmux-resurrect's responsibility.

**Expected Result:** _Describe what you would expect to have resulted from this process._

> I want my vim and nerdtree display without messed up.

---

**Optional**

**Screenshot(s):**

> ![image](https://user-images.githubusercontent.com/7262199/36943726-e616b8fa-1fc8-11e8-95b0-f5f820cf0986.png)

Thanks for your time.

**Comment by PhilRunninger** [comment]
See #2 and #337. There would be considerable refactoring needed to make sessions work correctly.
