### ISSUE TITLE
bufferwipe causing NERDTree to spam window

### ISSUE THREAD

**Issue by dminca** [scrooloose/nerdtree#813]
_To assist in resolving your issue, provide as much information as possible, in place of the ellipses (`…`) below._

---
**Environment:** _Describe your Vim/NERDTree setup._

>* Operating System: Linux Fedora 27
>* Vim version `:version`: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 28 2018 14:57:49)
>* NERDTree version `git rev-parse --short HEAD`: e47e588
>* NERDTree settings applied in your vimrc, if any:
>
>   ```
>   map <Leader>n :NERDTreeToggle<CR>
>   ```

**Process:** _List the steps that will recreate the issue._

>1. Open 4 files
>2. Close them <kbd>CTRL</kbd>+<kbd>w</kbd><kbd>q</kbd> except for the last one
>3. Wipe previous buffers, except the last file you've got opened via `:1,3bw` or even `:1,3bw!`

**Current Result:** _Describe what you you currently experience from this process._

> After trying to open/close NERDTree, it'll spawn more NERDTree's on the window on each command to open/close the NERDTree, thus polluting the window with NERDTrees without closing them.

**Expected Result:** _Describe what you would expect to have resulted from this process._

> NERDTree should open/close after each `:NERDTreeToggle` trigger.

---
**Optional**

**Screenshot(s):**
> ![screenshot from 2018-03-06 10-00-19](https://user-images.githubusercontent.com/5355219/37020741-92e8207a-2125-11e8-9674-ec1d8712d304.png)

**Possible Fix:** _(Have you poked around in the code?)_

>…

**Comment by PhilRunninger** [comment]
@dminca, this bug was triggered, in part, by your `:1,3bw` command. If you retrace your steps, before you wipeout your buffers, do an `:ls!`, and you'll see that `NERD_tree_1` is probably buffer 2. The bug was that NERDTree wasn't fully checking that the buffer was there, relying only on the existence of a variable that contained the name of the now-deleted buffer.

Feel free to test the fix provided in branch [813-bwipeout_NERDTree_buffer](https://github.com/scrooloose/nerdtree/tree/813-bwipeout_NERDTree_buffer). I will leave it open for review for about a day before merging it into master.

**Comment by dminca** [comment]
@PhilRunninger thank you for the quick reply :smile: 

Even if I close nerdtree via `:NERDTreeToggle`, and repeat the buffer operation bug is still present.

Thank you for providing fix, will test it for sure.

**Comment by PhilRunninger** [comment]
Yes, the bug would happen whether or not the NERDTree is toggled. The tree exists in a buffer just like any other file being edited, and if it's deleted or wiped out, the plugin needs to recreate it. The bug was that the plugin was incorrectly assuming the tree was still in memory.

**Comment by dminca** [comment]
Yep, you're right, I see it via `:ls!`

```sh
:ls!
  1      "ansible.cfg"                  line 1
  2u h-  "NERD_tree_1"                  line 10
  3      "build-playbook.yml"           line 5
  4      "CHANGELOG.md"                 line 1
  5 #    "inventory.yaml"               line 9
  6 %a=  "not_so_private_key"           line 1
```

Tested the fix from your branch, confirming that issue was solved :white_check_mark: Thank you very much!

**Comment by PhilRunninger** [comment]
Two simpler ways to recreate this bug are:
```
:NERDTreeToggle
:bw
:NERDTreeToggle
```
and 
```
:NERDTreeToggle
:NERDTreeToggle
:bw NERD
:NERDTreeToggle
```

**Comment by PhilRunninger** [comment]
@dminca Thanks for testing the fix. I'll go ahead and merge it.
