### ISSUE TITLE
Ignore files and directories

### ISSUE THREAD

**Issue by BigfootN** [scrooloose/nerdtree#817]
Hello,

I am trying to hide the `build` directory in NERDTree. But unfortunately I haven't succeeded.

Here is the option I have used:

`let NERDTreeIgnore = ['\build$']`

### Environment

* Operating System: archlinux
* Vim version `: version`: NVIM v0.2.3-785-gb22d3385b
* NERDTree version: It is the latest (I use `vim-plug`)

Thank you very much in advance.

**Comment by kutsan** [comment]
You should have used

```vim
let g:NERDTreeIgnore = ['build$']
```

**Comment by BigfootN** [comment]
Thank you very much for your precious help.

Problem solved.

**Comment by PhilRunninger** [comment]
The strings in that list are regular expressions, so the `\` is tyring to escape the `b` that follows it. The `\` is not a path separator. Your regular expression should look like this: `^build$` This will ignore all files and folders named **build**, but it won't hide ones like **building**. Additionally, you can use a special NERDTree flag to hide only folders:

`let NERDTreeIgnore = ['^build$[[dir]]']`

**Comment by kutsan** [comment]
@BigfootN You're welcome, always.

**Comment by BigfootN** [comment]
@PhilRunninger Thank you very much for the additional information.
