### ISSUE TITLE
Font problems - unicode related? [SOLVED]

### ISSUE THREAD

**Issue by carlca** [scrooloose/nerdtree#819]
### Environment

* Operating System: 
FreeBSD 11.1 Stable running under Parallels 13 for Apple Mac
Xfce + Slim
Both standard and Urxvt terminals
 

* Vim version `:version`:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 15 2018 17:58:52)
Included patches: 1-1427
Using https://github.com/junegunn/vim-plug as the plug-in manager

* NERDTree version `git rev-parse --short HEAD`: 
Latest commit a172d7c 13 days ago

* NERDTree settings applied in your vimrc, if any:
let g:airline_powerline_fonts = 1
autocmd vimenter * NERDTree
call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/nerdtree'
call plug#end()
### Process

1. Start vim 

### Current Result
Unexpected characters in the tree view.
Also I have no ability to open/close tree nodes

### Expected Result
Lines in the place of the strange characters.

### Screenshot(s)

![screen shot 2018-03-26 at 12 34 52](https://user-images.githubusercontent.com/260612/37904120-94db9d26-30f2-11e8-9b9b-e5aeda1627d8.png)

![screen shot 2018-03-26 at 12 49 02](https://user-images.githubusercontent.com/260612/37904584-2bd1b5b6-30f4-11e8-96d4-3583a6597ed7.png)

### Possible Fix
Over to you!

**Comment by carlca** [comment]
I amended my .vimrc following this SO answer https://stackoverflow.com/5795441...

![screen shot 2018-03-26 at 16 32 47](https://user-images.githubusercontent.com/260612/37916314-6a56a23c-3113-11e8-8948-82ec069e9791.png)

Here's my :version information showing that +multi_byte is there, although there is no explicit mention of unicode or utf-8.

![screen shot 2018-03-26 at 16 14 35](https://user-images.githubusercontent.com/260612/37915263-06651544-3111-11e8-963e-84cb827247f7.png)

Another symptom that something is wrong is the display of my botton tab which is supposed to be enhanced by the airline.vim plugin...

![screen shot 2018-03-26 at 16 34 59](https://user-images.githubusercontent.com/260612/37916423-b2673fd2-3113-11e8-8c5f-9ac4eb54b681.png)

**Comment by johnrobertlawson** [comment]
My only two plugins are nerdtree and airline. Interestingly, I have the same issue as you with weird characters in the tree view (which prevents me from going into directories - I can only go up!), but no problems with airline.

**Comment by carlca** [comment]
Thanks for the reply John. That prompted me to try it with `Airline` commented out (folllowed by a `:PlugInstall`, but it still doesn't work. The symptoms are identical. I cannot enter directories, and can only go `up a dir`. Oh well, hopefully, Monday evening is when Martin does his real geeking, and he'll get back to us soon!

**Comment by carlca** [comment]
Out of interest, are you saying that `Airline.vim` is working for you, with proper characters in the bottom panel? That would suggest that `vim` is coping with the `unicode` characters that `Airline` uses... Strange!

**Comment by carlca** [comment]
I've just tried it again, and I must have changed something because the display has improved (upside down ?'s rather the tri-byte characters) and the keyboard response to the tree has returned.

My `/.vimrc` looks like this now (is it the same as before??)...

![screen shot 2018-03-26 at 17 49 12](https://user-images.githubusercontent.com/260612/37920567-1f88e204-311f-11e8-958b-7481f56879b5.png)

And this is what `vim` looks like now...

![screen shot 2018-03-26 at 17 58 21](https://user-images.githubusercontent.com/260612/37920641-600a0bbe-311f-11e8-845b-7e50c622d69e.png)

**Comment by carlca** [comment]
Aha! That's what changed, I think. I installed the https://vimawesome.com/plugin/unicode-vim package. It didn't help solve the problem entirely but maybe it altered things slightly.

**Comment by carlca** [comment]
Sure thing! Over and out!
