### ISSUE TITLE
nerdtree locks VIM for ~60-90 seconds on launch

### ISSUE THREAD

**Issue by broofa** [scrooloose/nerdtree#82]
Apologies for the ambiguous report to follow ...

My vim spontaneously started taking forever to launch.  One day it was launching in < 1 second, the next it was taking 1-2 minutes.  I experimented with disabling various plugins and narrowed it down to nerdtree.  With nerdtree installed, long delays during launch.  Without it, no delays.

I'm suspicious this may have something to do with the file/dir caching.  I finally fixed the problem by opening NerdTree and changing the root directory to a subdirectory of my root, at which point I got the "caching large directory, this may take a while" message (or something to that effect.)

After the recache, VIM is back to normal - speedy launch with or without nerdtree active.

Where does nerdtree store it's cache files?  If this happens again, I'd like to see what's stored there.  Thx.

**Comment by PhilRunninger** [comment]
This issue has been idle for a while, so I'm closing it. Feel free to reopen if necessary.
