### ISSUE TITLE
Issues with changing movement keys from hjkl to jkl,

### ISSUE THREAD

**Issue by Limeth** [scrooloose/nerdtree#820]
Hello, I am changing my movement keys from hjkl to jkl, and I've stumbled upon this issue that the `l` key acts weird after remapping those keys. I've found the odd behavior is caused by a mapping that is added to the `l` key when the NERDTree window is selected: `nerdtree#ui_glue#invokeKeyMap("l")`. Is there a way to disable this?

### Environment

* Operating System: Linux 4.11.0-14-generic #20~16.04.1-Ubuntu SMP Wed Aug 9 09:06:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Vim version `:version`: NVIM v0.2.3-dev
* NERDTree version `git rev-parse --short HEAD`: 68572ef

### Process

In my .vimrc, I added the following:
```
noremap h <Nop>
noremap <C-h> <Nop>
noremap j h
noremap k gj
noremap l gk
noremap , l
```

### Current Result
```
:map l
n  l           *@:call nerdtree#ui_glue#invokeKeyMap("l")<CR>
   l           * gk
```

### Expected Result
```
:map l
   l           * gk
```

**Comment by PhilRunninger** [comment]
First, you should be using `nnoremap`, not `noremap`. Without the extra `n`, you will see the wrong characters show up in Insert mode and Command mode, when you really want that mapping only in Normal mode.

The `l` key is not used in NERDTree by default. Do you have any NERDTree-specific settings in your `vimrc`, where you define `l` as the key to do a specific action? Do you have any NERDTree plugins installed, other vim plugins that depend on, and extend the functionality of, NERDTree? The `l` mapping may be coming from such a plugin, which uses the NERDTree API to map the `l` key.

**Comment by Limeth** [comment]
Thank you for the response.
I do use a lot of plugins, but the only ones directly related I have are the following:
```
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
```
I also tried to recursively search through all installed plugins for occurrences of the mapping, but the only result I found was from the nerdtree plugin itself:
```
$ rg 'invokeKeyMap\("'
plugged/nerdtree/lib/nerdtree/key_map.vim
47:    exec 'nnoremap <buffer> <silent> '. self.key . premap . ':call nerdtree#ui_glue#invokeKeyMap("'. keymapInvokeString .'")<cr>'
```
Regarding the usage of `noremap`, I haven't encountered any problems in insert mode, but I'm not sure I know what is meant by command mode; typing commands with `:` worked fine.

**Comment by PhilRunninger** [comment]
Try `:verbose map l`. That will tell you which vim script defined the mapping, or the last one of multiple scripts to do so.

**Comment by Limeth** [comment]
This is the output I got:
```
:verbose map l
n  l           *@:call nerdtree#ui_glue#invokeKeyMap("l")<CR>
        Zuletzt gesetzt in ~/.dotfiles/link/.config/nvim/plugged/nerdtree/lib/nerdtree/key_map.vim
   l           * gk
        Zuletzt gesetzt in ~/.dotfiles/link/.config/nvim/map.vim
```

**Comment by PhilRunninger** [comment]
Two more things to try...
1. Something is assigning `l` to one of the NERDTree key mappings. We need to find out what it is. Grep your `.vim` directory and report what you find.
    ```bash
    grep -r "let.*NERDTree.*=.*['\"]l['\"]" .
    ```
1. Open the NERDTree quickhelp with the `?`, and look for the `l` mapping in the listing. That's another way to tell which mapping `l` is assigned to. If the first step doesn't reveal anything, this should give us a specific variable to look for.

My bad on the `:noremap`. I should have read the documentation first. `:h noremap` leads you to `:h mapmode-nvo`. These mappings take effect in Normal, Visual, and Operator-pending modes. Insert and Command mode are not touched.

**Comment by Limeth** [comment]
The grep command unfortunately didn't find any matches.
I then tried looking for the `l` mapping in the NERDTree quickhelp, but again, didn't find anything regarding the `l`, Here is the output of the quickhelp: https://hastebin.com/oxakoweyam

I did try more general search terms with grep and found the following:
```
$ rg "=.*['\"]l['\"]"
function.vim
50:    let l:keys = ['h', 'j', 'k', 'l']

nerdtree_plugin/expanderrific.vim
14:let expanderrific_expand   = ['l', '<Right>']

plugged/incsearch.vim/test/visual_emulation.vim
140:  let e2 = '\v%1l\_.*%' . line('w$') . 'l'

plugged/vim-surround/plugin/surround.vim
212:  elseif newchar ==# 'l' || newchar == '\'

plugged/vim-unimpaired/plugin/unimpaired.vim
21:  let end = '"<CR>'.(a:cmd == 'l' || a:cmd == 'c' ? 'zv' : '')

plugged/vim-javacomplete2/autoload/java_parser.vim
570:    if b:ch == 'l' || b:ch == 'L'

plugged/vim-airline/doc/airline.txt
994:  let g:airline#extensions#vimtex#sub_local = "l"

plugged/ultisnips/test/test_Selection.py
54:    maps = ('H', 'x'), ('e', 'l')
60:    maps = ('H', 'x'), ('e', 'l')
66:    maps = ('e', 'l'), ('H', 'x')

plugged/vim-fugitive/plugin/fugitive.vim
1331:      return (a:cmd =~# '^l' ? 'l' : 'c').'first'.matchstr(a:arg,'\v\C[''" ]\zs\|.*')

plugged/python-mode/pymode/libs/pycodestyle.py
1243:    idents_to_avoid = ('l', 'O', 'I')

plugged/python-mode/pymode/libs/pylint/checkers/format.py
790:            if tok_type == tokenize.NUMBER and token.endswith('l'):

plugged/python-mode/pymode/libs/astroid/tests/unittest_inference.py
466:        n = ast['l']
```

I suspect the culprit here might be the `nerdtree_plugin/expanderrific.vim` file, will investigate further. Thank you for the help so far!

**Comment by Limeth** [comment]
Okay, that `expanderrific.vim` script indeed was the culprit. See the source code: https://hastebin.com/abigefugey
I had to change
```
let expanderrific_expand   = ['l', '<Right>']
let expanderrific_collapse = ['h', '<Left>']
```
to
```
let expanderrific_expand   = [',', '<Right>']
let expanderrific_collapse = ['j', '<Left>']
```

But now I'm wondering whether it could be done in a better way; maybe instead of specifying the movement keys, somehow specify the action of moving the cursor to the left. Just to make it future proof if I decide to return to `hjkl`. Do you think that would be possible? Either way, thank you for the tremendous help, it would've taken me ages to find the cause by myself!
