### ISSUE TITLE
Delete directory does not check children

### ISSUE THREAD

**Issue by SammysHP** [scrooloose/nerdtree#821]
You can delete a node via <kbd>m</kbd> <kbd>d</kbd> and confirm via <kbd>y</kbd>. If the node is a directory which has children, you have to type `yes` instead. But this works only if you have opened the directory in nerdtree previously, it does not read the contents by itself automatically. So sometimes <kbd>y</kbd> is enough to delete a directory that is not empty.

(I would prefer an option to always confirm via <kbd>y</kbd>, but that is a different issue.)

**Comment by PhilRunninger** [comment]
@SammysHP, I just created a pull request to fix this. Can you test it out for me?

Thanks!
