### ISSUE TITLE
Use inotify to watch for FS changes?

### ISSUE THREAD

**Issue by naftulikay** [scrooloose/nerdtree#825]
As I create and move files via the CLI, I don't see these changes reflected in NERDTree. Is there a possibility of using inotify (or equivalent for other platforms) to detect file changes and refresh the tree?

**Comment by lifecrisis** [comment]
I looked into this.  It's not, in my opinion, feasible.  The amount of work involved would be tremendous as there are at least 3 platforms that need to be considered carefully (Mac, Windows, Linux).  All three would require their own special solution written in a language other than VimL.

This is certainly a desirable feature, but the developer time that would be required is too much.  To anyone who wanted to try this, I would recommend that he fork the project.
