### ISSUE TITLE
Error in read-only mode

### ISSUE THREAD

**Issue by SammysHP** [scrooloose/nerdtree#831]
### Environment

* Operating System: Arch Linux
* Vim version `:version`: 
    ```
    VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 26 2018 23:00:19)
    Included patches: 1-1542
    Compiled by Arch Linux
    Huge version with GTK3 GUI.  Features included (+) or not (-):
    ```
* NERDTree version `git rev-parse --short HEAD`:  a172d7cfcb4fe9b927dcc24184204fc89d826301
* NERDTree settings applied in your vimrc, if any:
    ```vim
    let g:NERDTreeMinimalUI=1
    ```

### Process

1. Start vim in read-only mode via `view` or `vim -R`.
1. Open NERDTree (e.g. `:NERDTree`).

### Current Result
An error is shown:

```
Error detected while processing function 183[2]..184[21]..229[1]..250:
line   32:W10: Warning: Changing a readonly file
Press ENTER or type command to continue
```

### Expected Result
NERDTree should open without error.

**Comment by kutsan** [comment]
I think NERDTree itself should have set its buffer-only `'readonly'` option to false. Practically the code below solves the issue but I still think a patch needed.

```
autocmd FileType nerdtree setlocal noreadonly
```
