### ISSUE TITLE
Get indent guides in nerdtree like that of netrw in netrw_liststyle=3

### ISSUE THREAD

**Issue by enanajmain** [scrooloose/nerdtree#836]
### Environment

* Operating System: Mint 18.3 sylvia
* Vim version `:version`: NVIM v0.3.0-dev
* NERDTree version `git rev-parse --short HEAD`: 68313ef0f512
* NERDTree settings applied in your vimrc, if any:
    ```vim
    let NERDTreeMinimalUI=1
    let g:NERDTreeWinPos = "left"
    let NERDTreeShowLineNumbers=1
    let NERDTreeShowHidden=0
    let NERDTreeIgnore = ['\.pyc$', '__pycache__', '.class$']
    let g:NERDTreeWinSize=30
    let NERDTreeDirArrows = 1
    let g:NERDTreeDirArrowExpandable = '⮞'
    let g:NERDTreeDirArrowCollapsible = '⮟'
    let g:NERDTreeHighlightCursorline = 0
    let g:NERDTreeStatusline = " NerdTree"
    let g:NERDTreeRespectWildIgnore = 1
    ```

### Process
Just toggle the nerdtree

### Current Result
The nerdtree looks like [this image](https://images.thoughtbot.com/refrain-from-nerdtree/nerdtree.png). There is no indent guides. How can I put the indent guides?

### Expected Result
Nerdtree should look like [this image](http://www.catonmat.net/blog/wp-content/uploads/2010/01/nerd-tree-vim.png) or [this image](https://blog.htbaa.com/wp-content/uploads/2013/03/nerdtree.png)

**Comment by PhilRunninger** [comment]
You can't. Those lines were removed about 3 years ago.
