### ISSUE TITLE
Forbidden access to link in docs

### ISSUE THREAD

**Issue by kristijanhusak** [scrooloose/nerdtree#841]
Not sure if you can do anything about it, but the link in the docs in `NERDTreeAPI` part for prototype based structure is not working: http://got-ravings.blogspot.com/2008/09/vim-pr0n-prototype-based-objects.html

Is there an alternative link?

**Comment by PhilRunninger** [comment]
@scrooloose , this one is on you to change. Thanks!

**Comment by lifecrisis** [comment]
That's a shame.  That was such a good article.  It was the gateway to understanding the NERDTree for me.

@scrooloose, would you consider letting us incorporate a text version of that article into the NERDTree documentation?

**Comment by scrooloose** [comment]
Hey guys, there was a sensitive situation and I had to take the blog down for a while. I have put it back up again in a slightly more anonymized state. In the current climate, it seems some people are determined to see hate speech everywhere - even in computer nerd blog posts from 10 years ago.

For the record I don't hate anyone. I just think naughty words are funny.
