### ISSUE TITLE
should compare with type instead of its value

### ISSUE THREAD

**Issue by linuxholic** [scrooloose/nerdtree#842]
https://github.com/scrooloose/nerdtree/blob/6188c5ea5f6fd44e24768ccb889aaa739808d9f3/autoload/nerdtree.vim#L76

**Comment by PhilRunninger** [comment]
Thanks for the information. There's another issue, #277, that's probably closely related to this. I'll be taking a closer look at these soon.

**Comment by PhilRunninger** [comment]
@linuxholic , Take a look at your scenario, and see if #856 has fixed it.
