### ISSUE TITLE
Ability to rename Bookmarks to support same directory name bookmarks to not overwrite one another

### ISSUE THREAD

**Issue by mitermayer** [scrooloose/nerdtree#843]
Hi @scrooloose,

nerdtree has been an amazing hammer for me throughout the years. I recently started to use the "Bookmark" feature which is amazing for dealing with extremely large code bases!

One problem that I have encountered is that sometimes directories that I want to bookmark have the same name and overwrite each other example:

* /foo/bar/baz/bleh
* /x/y/bleh

I wish once the bookmark is created I could rename the `bleh` to something else. Please let me know if that sounds like a feature you would think could be added to nerdtree, more than happy to submit a PR for it as well.

**Comment by PhilRunninger** [comment]
This feature is already in NERDTree. The `:Bookmark` command takes an optional `name` argument, which will differentiate them for you. See `:h NERDTreeBookmarks`.

**Comment by mitermayer** [comment]
Thank you, could not find this information the "?" help menu! very happy to see that it is implemented
