### ISSUE TITLE
:edit! freezes vim

### ISSUE THREAD

**Issue by SammysHP** [scrooloose/nerdtree#845]
- open NEERDTree
- type `:edit!<CR>`
- vim will run at 100% CPU and does not respond to any key presses until you abort via <kbd>Ctrl</kbd>+<kbd>C</kbd>.

With just `:e` the NERDTree buffer will be empty.

Commit 6188c5e

**Comment by lifecrisis** [comment]
Interesting...  Can't say this is a high priority bug simply because it's an odd thing to try and do in the NERDTree window.  However, I do find this weird.  One of us will take a look eventually.

**Comment by PhilRunninger** [comment]
I just took a look at this again. It doesn't appear to be happening anymore, as if some commit along the way has "fixed" it. There is a strange side-effect though; after the `:edit!`, syntax highlighting is turned off. Like @lifecrisis said, this is an odd thing to do, so I'm going to close this issue.
