### ISSUE TITLE
Sometimes can't open file

### ISSUE THREAD

**Issue by iwifigame** [scrooloose/nerdtree#847]
### Environment

* Operating System: 
* Vim version `:version`:  8.0 and newer
* NERDTree version `git rev-parse --short HEAD`: 
* NERDTree settings applied in your vimrc, if any:
    ```vim
    ```

### Process

1.  sometimes cant open file, must restart vim to make it work

**Comment by PhilRunninger** [comment]
You have given no useful information we can use to recreate, let alone fix, the issue. Please include steps needed to consistently recreate the issue.

**Comment by lifecrisis** [comment]
It's been two months.  Closing due to lack of feedback.
