### ISSUE TITLE
Possible to have NerdTreeToggle re-use existing NerdTree buffer?

### ISSUE THREAD

**Issue by gdoteof** [scrooloose/nerdtree#854]
From a high level, I would like to be able to switch tabs within a single vim session and have the nerdtree buffer always be the same.  Currently the nerdtree buffer is maintained within each individual tab, so when I close/open with NerdTreeToggle the expanded directories are maintained; but if I switch to a new tab, it is a new NerdTreeBuffer.

currently the only nerdtree specific things I have in my vimrc is this mapping

```vim
map <Leader>n :NERDTreeToggle<CR>
```
Ideally I would like `<Leader>n` to open the same NerdTree buffer for every tab within a single vim instance.

### Environment

* Operating System: 
Ubuntu

* Vim version `:version`: 
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 20:13:43)

* NERDTree version `git rev-parse --short HEAD`: 
a172d7c

### Process

1.   :NerdTreeToggle ::make some changes::
2.   Switch to another tab/buffer in same instance of VIM
3.   :NerdTreeToggle 

### Current Result

The NerdTree buffer will be fresh and not contain any of the expanded directories (closing and opening works fine within a single tab/buffer)

### Expected Result

The ability to share a single nerdtree buffer between all tabs.

**Comment by PhilRunninger** [comment]
After your first `:NERDTreeToggle`, you can use `:NERDTreeMirror` on new tabs to make use of the original NERDTree buffer. You might also consider using the [vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs/blob/master/nerdtree_plugin/vim-nerdtree-tabs.vim) plugin, as mentioned in the NERDTree [README](https://github.com/scrooloose/nerdtree/blob/master/README.markdown).

**Comment by gdoteof** [comment]
`NERDTreeMirror` is exactly what I needed, thank you
