### ISSUE TITLE
NERDTreeCWD and autochdir do not cooperate

### ISSUE THREAD

**Issue by klassegeljakt** [scrooloose/nerdtree#855]
Not sure if this is a bug or not, `NERDTreeCWD` appears to change directory to the `:pwd` of the `NERDTree`'s buffer and not to the current buffer's when using `autochdir`.

### Environment

* OS: macOS High Sierra
* Editor: MacVim
* Version: 8.1
* NERDTree version: d6032c8

### Process

1. `mvim ~/`
2. `:set autochdir`
3. `:cd ~/test/`
4. `:NERDTreeCWD`

### Current Result

NERDTree's root is the `~/`.

### Expected Result

NERDTree's root should be the `~/test/`.

It works when changing the second step (2.) to `:set noautochdir`.

**Comment by PhilRunninger** [comment]
I tracked this error down to this [line in creator.vim](https://github.com/scrooloose/nerdtree/blob/80ee0897ff4d4f0583c0c4985d352162d8166d6e/lib/nerdtree/creator.vim#L189). For some reason it changes the CWD when `'autochdir'` is turned on, but... only when it's run as part of the `:NERDTreeCWD` command. Strangely, executing the command `:topleft vertical 42 new` manually has not effect on the CWD.
