### ISSUE TITLE
Can I use it just via copy the NERD_Tree.vim to ~/.vim/plugin?

### ISSUE THREAD

**Issue by mumuchong** [scrooloose/nerdtree#857]
### Environment

* Operating System: SUSE Linux
* Vim version `:version`: VIM - Vi IMproved 8.1
* NERDTree version `git rev-parse --short HEAD`: 
* NERDTree settings applied in your vimrc, if any:
    ```vim
    ```

### Process

1. Download the latested NERDTree code;
2. Copy the plugin/NERD_Tree.vim to ~/.vim/plugin/;
3. Restart vim;
4. Can't use NERDTree.

### Current Result

Just use ~/.vim/plugin director to place and  manage vim plugin-in.
### Expected Result

Make NerdTree plug-in work well
### Screenshot(s)
When i use command "NERDTree" in vim, it informed:
![default](https://user-images.githubusercontent.com/23065929/42200332-59698372-7ec5-11e8-85ba-55740285b882.png)

**Comment by lifecrisis** [comment]
No.

You need to read the documentation for one of the recommended plugin managers.  See the `README.md` file.
