### ISSUE TITLE
How to change the director color of NERDTree?

### ISSUE THREAD

**Issue by mumuchong** [scrooloose/nerdtree#858]
### Environment

* Operating System: SUSE Linux
* Vim version `:version`:  8.1
* NERDTree version `git rev-parse --short HEAD`: 5.0
* NERDTree settings applied in your vimrc, if any:
    ```vim
    ```
" NERD tree
let NERDChristmasTree=0
let NERDTreeWinSize=35
let NERDTreeChDirMode=2
let NERDTreeIgnore=['\~$', '\.pyc$', '\.swp$']
let NERDTreeShowBookmarks=1
let NERDTreeWinPos="left"
" Automatically open a NERDTree if no files where specified
autocmd vimenter * if !argc() | NERDTree | endif
" Close vim if the only window left open is a NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
" Open a NERDTree
nmap <C-b> :NERDTreeToggle<cr>

### Process

1.  open NERDTree in vim;
2.  the director of NERDTRee displayed is blue,and i want change it.

### Current Result

![default](https://user-images.githubusercontent.com/23065929/42303494-2eef1dec-8054-11e8-9b83-1e3857d36365.png)

### Expected Result

change to other color
### Possible Fix

try find the color setting of director in nerdtree/lib/ , but do not find.

**Comment by PhilRunninger** [comment]
The colors are not configurable NERDTree settings. You likely have the same issue with blue text in other contexts. Try using a different colorscheme. If you don't like any of the default colorschemes, you can always download others as additional plugins. My favorite is [gruvbox](https://github.com/morhetz/gruvbox).

**Comment by mumuchong** [comment]
Thanks for your advice, Inspired by you i change my putty's color， then it displays better .Thanks.

**Comment by lifecrisis** [comment]
@mumuchong:

If you're using PuTTy, you probably need to put `set background=dark` in your `.vimrc` file on the remote machine.  Read `:help 'background'` if you're curious.
