### ISSUE TITLE
NERDTree.txt help file not loading.

### ISSUE THREAD

**Issue by philFernandez** [scrooloose/nerdtree#859]
### Environment

Terminal Vim8/NERDTree out of the box options
* Operating System: 
Ubuntu 18.04 / i3wm
* Vim version `:version`:
Terminal Vim8 
* NERDTree version `git rev-parse --short HEAD`: 
d6032c8 master
* NERDTree settings applied in your vimrc, if any:
None
    ```vim
    ```

### Process

1. 
`:tab h NERDTree.txt`
### Current Result

Nothing
### Expected Result

Open Documentation for NERDTree
### Possible Fix ?

---------------------------------------------------------------------------------------
I have NERDTree installed via vim-plug. For some reason the help tags have not loaded. I cannot open any documentation for NERDTree inside of vim. I've tried manually loading the help tags with `:helptags ~/.vim/plugged/nerdtree/doc`. This doesn't give any error, but it also doesn't load the help tags/file.

**Comment by PhilRunninger** [comment]
I took a peak at your `.vimrc`, and I think it may be because you're delaying the loading of NERDTree.
```
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
```
If you try to access the help page before you run `:NERDTreeToggle`, the help files won't be in the path. Does the help page appear after opening a NERDTree?

**Comment by philFernandez** [comment]
That was it. The help page does appear while NERDTree is open. I can't believe that didn't occur to me. Thank you for pointing it out. I appreciate it!
