### ISSUE TITLE
`shellslash` option interference nerdtree

### ISSUE THREAD

**Issue by zgpio** [scrooloose/nerdtree#860]
### Environment

* Operating System: win10
* Vim version `:version`:  8.1
* NERDTree version `git rev-parse --short HEAD`: latest 
* NERDTree settings applied in your vimrc, if any:
    ```vim
    " no need
    ```

### Process

1.  copy `nerdtree` repo to `...\vimfiles\pack\github\start`
2. start vim, run `:set shellslash` and `:cd d:/`
3. run `:NERDTree`, you will get message
```
NERDTree: No bookmark or dirctory found for:
```

**Comment by lifecrisis** [comment]
Confirmed this bug.  It will take some fixing and a little clean-up to get this working properly.  Thanks.

**Comment by zgpio** [comment]
Thanks a lot.

**Comment by zgpio** [comment]
And `copy the current node` can not work.

**Comment by zgpio** [comment]
Yes, the original problem is fixed, but the `shellslash` option still interference nerdtree.

**Comment by zgpio** [comment]
with the patch:
start vim, run `:set shellslash` and `:cd d:/`, and then expand a directory, you will find like that:
![image](https://user-images.githubusercontent.com/19503791/45923649-54f3fb80-bf1e-11e8-9361-3f4643c25bf8.png)

**Comment by lifecrisis** [comment]
What kind of files are in that directory?  Are they all links?  Please provide more information on how to make this happen in my Vim instance.

**Comment by zgpio** [comment]
Sorry for that.
with the patch 860:
start vim, run `:set shellslash` and `:cd d:/`, and then expand a directory, you will find like that(fig1):
![image](https://user-images.githubusercontent.com/19503791/45934654-b2964f80-bfd3-11e8-9b4a-fbb46a9a0fdd.png)
but it should be fig2:
![image](https://user-images.githubusercontent.com/19503791/45934670-0e60d880-bfd4-11e8-8653-d36954039296.png)

If set noshellslash, vim will block when I expand a directory, so that I waited a long time to list the directories(fig2).

**Comment by PhilRunninger** [comment]
@zgpio , PR #935 has just been merged into master. Please give it a try and close this issue it it's been resolved.

**Comment by zgpio** [comment]
Sorry, replying so late.
Now it seems that nerdtree is working correctly.
