### ISSUE TITLE
change dir to the bookmark dir after using bookmark?

### ISSUE THREAD

**Issue by slmjkdbtl** [scrooloose/nerdtree#861]
is it possible?

**Comment by lifecrisis** [comment]
There isn't a way to specifically do this only for bookmarks.  You would have to create a custom mapping.

Take a look at `:h NERDTreeChDirMode` and see if that does what you want.

**Comment by minusf** [comment]
actually the question is about a use case that `NERDTreeChDirMode` covers.  i will create a separate issue.

**Comment by PhilRunninger** [comment]
`let NERDTreeChDirMode=2` is the answer to the original question. Closing this issue.
