### ISSUE TITLE
Is there a escape character for the space when I create a file by the shortcuts `ma` and input the filename? 

### ISSUE THREAD

**Issue by qs-cosmos** [scrooloose/nerdtree#863]
### Environment

* Operating System: Debian 8
* Vim version `:version`: 8.1.178
* NERDTree version `git rev-parse --short HEAD`: d6032c8
* NERDTree settings applied in your vimrc, if any:
let NERDTreeIgnore = ['\.pyc$[[file]]', '\.o$[[file]]', '\.pro.user$[[file]]']

### Process
Normally create a file or directroy by the shortcuts `ma` provided by the NerdTree. 

### Current Result
If I input  a filename and end up with spaces, the filename which just created were really end of spaces, the same as the input. It may cause some unexpected faults in programming.

### Expected Result
I expect that it can detect the input firstly,  and then ignore the spaces at end of the input before create a file. If the end space were wanted , please add a escape character for it.

**Comment by PhilRunninger** [comment]
If you don't want spaces to be in your filename, just don't type them. NERDTree will take the text you enter to be the exact filename it creates.
