### ISSUE TITLE
How to install nerdtree manually offline?

### ISSUE THREAD

**Issue by Renjielu** [scrooloose/nerdtree#864]
### Environment

* Operating System: Redhat
* Vim version `:version`: 8.1
* NERDTree version `git rev-parse --short HEAD`: 
* NERDTree settings applied in your vimrc, if any:
    ```vim
    ```

### Process

1. Due to some restrictions, I won't be able to do git clone in my work-space. I tried to download the master repo from another computer and unzip in my work-space. Then I manually copy those sub-directory and *.vim files to my local installed vim plugin & autoload directory. However I still see some errors listed as below, can anyone give me some suggestions?

### Current Result

E117: Unknown function: nerdtree#ui_glue#setupCommands
line  164:
E121: Undefined variable: g:NERDTreeCreator
E15: Invalid expression: "autocmd BufLeave ". g:NERDTreeCreator.BufNamePrefix() ."* if g:NERDTree.IsOpen() | call b:NERDTree.ui.saveScreenState() | endif"
line  167:
E121: Undefined variable: g:NERDTreeCreator
E15: Invalid expression: "autocmd BufEnter ". g:NERDTreeCreator.BufNamePrefix() ."* stopinsert"
Error detected while processing function nerdtree#postSourceActions:
line    1:
E121: Undefined variable: g:NERDTreeBookmark
line    2:
E117: Unknown function: nerdtree#ui_glue#createDefaultBindings
Error detected while processing function NERDTreeAddMenuItem:
line    1:

**Comment by lifecrisis** [comment]
Leave the NERDTree project directory intact (after you unzip it) and add its location to the `'runtimepath'` setting in your `.vimrc` file. 

```viml
set rtp+=/path/to/nerdtree/dir
```

That should work.

**Comment by PhilRunninger** [comment]
I'm closing this, as it isn't a NERDTree-specific issue.
