### ISSUE TITLE
E117: Unknown function: NERDTreeAddKeyMap

### ISSUE THREAD

**Issue by andreyvpng** [scrooloose/nerdtree#874]
I'm created new nerdtree key mapping into my .vimrc. When i am start vim, i get this error 

![screenshot_2018-08-14_17-41-20](https://user-images.githubusercontent.com/14147741/44078237-55cde9de-9fe9-11e8-9b80-1740ccaab2be.png)

NERDTree run only if i press < C-n >(my mapping). How to run NERDtree automatically to solve this problem. 

I tried to insert "autocmd vimenter * NERDTree" into my vimrc, but problem did not leave me. My whole of .vimrc you can find in my profile

**Comment by PhilRunninger** [comment]
The `NERDTreeAddKeyMap()` function hasn't been defined when you try to use it in your **.vimrc**. There are two reasons for this.
1. **.vimrc** runs first, before the **NERDTree** (or any other) plugin
1. You're telling **vim-plug** to delay loading **NERDTree** until the `:NERDTreeToggle` command has been issued. See [line 7](https://github.com/andreyvpng/dotfiles/blob/master/vim/.vimrc#L7)

To fix this, you need to handle both of these causes. **NERDTree** needs to be loaded on startup, and `call NERDTreeAddKeyMap(...)` needs to wait until the end of the startup process.
1. First tell **vim-plug** to load **NERDTree** as part of the startup process, by removing `, { 'on' : 'NERDTreeTogle' }`.
1. Add `autocmd VimEnter *` in front of `call NERDTreeAddKeyMap(...)`. This will cause it to run after all the plugins and startup scripts have been run.

**Comment by andreyvpng** [comment]
Thank you for the detailed answer to my problem. But vim still starts with an error

It's from my shell 

```
dotfiles git/master  272s
❯ vim
--- Auto-Commands ---
Error detected while processing /home/andrey/.vimrc:
line  189:
E117: Unknown function: NERDTreeAddKeyMap
Press ENTER or type command to continue
```
When i'm write ` :source ~/.vimrc` in vim, i see this 
```
:source ~/.vimrc
--- Auto-Commands ---
NERDTreeHijackNetrw  VimEnter
    *         silent! autocmd! FileExplorer
              call nerdtree#checkForBrowse(expand("<amatch>"))
fugitive  VimEnter
    *         if empty(expand('<amatch>'))|call FugitiveDetect(getcwd())|endif
gitgutter  VimEnter
    *         if winnr() != winnr('$') | call gitgutter#all(0) | endif
airline  VimEnter
    *         call <sid>on_window_changed()
TagbarAutoCmds  VimEnter
    *         call s:CorrectFocusOnStartup()
jedi_startup  VimEnter
    *         call s:setup_completeopt()
Press ENTER or type command to continue
```
You can see my changes in [my last commit](https://github.com/andreyvpng/dotfiles/commit/579c90d7079e4216acde23490a340408c4028a3e)

**Comment by PhilRunninger** [comment]
I wasn't clear enough in my instructions. The `autocmd VimEnter *` needs to look like this:
```
autocmd VimEnter * call NERDTreeAddKeyMap({
     \ 'key': 'do',
     \ 'callback': 'NERDTreeOpenDjangoApp',
     \ 'quickhelpText': 'open django app with split' })
```

**Comment by andreyvpng** [comment]
Yes. Thanks for helping! It's work.
