### ISSUE TITLE
Allow customized location for `nerdtree_plugin` mappings.

### ISSUE THREAD

**Issue by jordwalke** [scrooloose/nerdtree#881]
Some setups would rather use something like XDG config locations for mappings. Can you please allow this to be supported?

**Comment by lifecrisis** [comment]
Please investigate the vim `'runtimepath'` setting.  You can create a `nerdtree_plugin/` directory as a child of some directory in your `'runtimepath'` list.  NERDTree plugins in that directory will be sourced like plugins in your own `.vim/` directory.

This, in general, how you customize the location of supporting Vim scripts.
