### ISSUE TITLE
How to show the current root directory as relative path from my HOME?

### ISSUE THREAD

**Issue by jdhao** [scrooloose/nerdtree#891]
Currently nerdtree shows the full path of current root in the statusline. I want to show its path relative to my HOME. For example, for `/home/jdhao/tools/`, I want it to be shown as `~/tools`.

After looking up the documentation and googling, I came up with the following setting:

```
let NERDTreeStatusline="%{exists('b:NERDTree')?fnamemodify(b:NERDTree.root.path.str(), ":~"):''}" 
```

There is something wrong with it. But I know it is nearly correct.  Could you please point out what is wrong?

**Comment by PhilRunninger** [comment]
Your quotation marks aren't paired up correctly. Try this instead:

```
let NERDTreeStatusline='%{exists("b:NERDTree")?fnamemodify(b:NERDTree.root.path.str(), ":~"):""}'
```

**Comment by jdhao** [comment]
Thanks, it works now. 👍
