### ISSUE TITLE
Add eventignore to prevent spurious behavior of user autocmd

### ISSUE THREAD

**Issue by dbivolaru** [scrooloose/nerdtree#900]
Related to #684 

### Environment
* Operating System: Linux 4.18.12-200.fc28.x86_64 #1 SMP x86_64 GNU/Linux
* Vim version `:version`: 801
* NERDTree version `git rev-parse --short HEAD`: vim-nerdtree-5.0.0-2.fc28.src.rpm
* vimrc settings that are relevant:
    [...]
    set nocursorline
    let g:NERDTreeWinPos="right"
    [...]
    autocmd WinEnter * setlocal cursorline
    autocmd WinLeave * setlocal nocursorline
    [...]

### Process
1. Open file1
2. Open file2 in a vertical split
3. C-w to the leftmost split
4. :NERDTreeToggle

### Current Result
The leftmost split cursorline is not highlighted anymore (as expected).
The NERDTree cursorline is highlighted (as expected).
The right split for the other file has it's cursorline also highlighted (NOT expected).

### Expected Result
The leftmost split cursorline is not highlighted anymore (as expected).
The NERDTree cursorline is highlighted (as expected).

### Possible Fix
After having a look at #684 I got the idea to disable events for WinEnter/WinLeave when I realized that NERDTree is switching windows internally three times.

    nnoremap <silent> <C-n> :setlocal nocursorline<BAR>set ei=WinEnter,WinLeave<BAR>try<BAR>NERDTreeToggle<BAR>finally<BAR>set ei=<BAR>endtry<BAR>setlocal cursorline<CR>

### Final fix
I believe this can be generalized into `NERDTreeToggle` and `NERDTreeFocus` codebase to include the eventignore try-finally block with a more comprehensive list of events. That should also fix the side-effects described in #684.

**Comment by PhilRunninger** [comment]
@dbivolaru , I cannot reproduce this issue. I tried using two methods, and in each case, the `cursorline`s behave as you expect them.
### Method 1
```
$ vim
:NERDTreeToggle
go
s
<C-W>w
<C-W>w
<C-W>w
```
### Method 2
```
$ vim
:e file1
:vsp file2
:NERDTreeToggle
<C-W>w
<C-W>w
<C-W>w
```
I can't think of any pull request that would have caused this to be fixed now, but it's possible. Can you try again on the latest version of NERDTree? And if I've misunderstood your issue, please clarify.

**Comment by dbivolaru** [comment]
@PhilRunninger Just to confirm I am still able to reproduce it.

```
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun  6 2019 11:29:32)
$ uname -a
Linux localhost 5.1.11-200.fc29.x86_64 #1 SMP Mon Jun 17 19:30:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ git log
commit 2f0d48d632dc303095084b382cb665ae57ad2e63 (HEAD -> master, origin/master, origin/HEAD)
Author: Phil Runninger (mac) <prunninger@vhtcx.com>
Date:   Sun Jul 7 03:53:06 2019 -0400
$ vim
:e file1
:vsp file2
:NERDTreeToggle
```
At this point you should have two highlights: one for the window with file2 and one for the NERDTree window. This is incorrect. If you <C-W>W around you will see that at any one point in time only one window has the line highlighting on (see vimrc relevant settings above).

In order to fix this i use the more complicated macro I mentioned. With that one, when NERDTree is toggled with the ```ei``` disabled, then the windows for file1 or file2 have no highlighted cursor, as it should be.

**Comment by PhilRunninger** [comment]
I think I tracked it down, and it's not a NERDTree issue. Your autocommands aren't what they need to be. With the autocommands in your original issue,

```vim
autocmd WinEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline
```
you will see no cursorlines until you start switching windows or open NERDTree. (I don't know why `:vsp` doesn't trigger these commands. Maybe a Vim bug?)

The autocommands in your current `.vimrc`,
```vim
autocmd VimEnter,BufEnter * setlocal cursorline
autocmd BufLeave * setlocal nocursorline
```
will cause all three windows to have cursorlines in them until you start switching windows.

You need to combine these to handle all the cases (`BufEnter`/`BufLeave` for `:e` and `:vsp`; and (`WinEnter`/`WinLeave` for `<C-W>w`).
```vim
autocmd VimEnter,BufEnter,WinEnter * setlocal cursorline
autocmd BufLeave,WinLeave * setlocal nocursorline
```
There are other issues related to autocommands not working correctly or at all, but I don't think this is one of them. Give this a try not using your `<C-n>` or `<C-m>` keys, and let me know if it works.

**Comment by dbivolaru** [comment]
@PhilRunninger This works. Great! Thank you.

```
autocmd VimEnter,BufEnter,WinEnter * setlocal cursorline
autocmd BufLeave,WinLeave * setlocal nocursorline
```
