### ISSUE TITLE
Folders are no longer expandable using `ENTER` key

### ISSUE THREAD

**Issue by mboughaba** [scrooloose/nerdtree#905]
### Environment

* Operating System: Ubuntu 18
* Vim version `:version`: 8.1 1-409
* NERDTree version `git rev-parse --short HEAD`: b84a8b6
* NERDTree settings applied in your vimrc, if any:
    ```vim
" source: https://github.com/scrooloose/nerdtree/issues/636
let NERDTreeDirArrowExpandable = " "
let NERDTreeDirArrowCollapsible = " "
    ```

### Process

1. Hit `ENTER` key to expand a folder under NERDTree tree

### Current Result

Folders are no longer expandable using `ENTER` key. Also, many other actions such as `m` stopped working

### Expected Result

Folders are expandable using `ENTER` key

### Possible Fix

```vim
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
```

**Comment by PhilRunninger** [comment]
@mboughaba , See #904.
