### ISSUE TITLE
Command to hide files based on extension / pattern?

### ISSUE THREAD

**Issue by olalonde** [scrooloose/nerdtree#909]
I guess this is more of a feature request. I have a bunch of `*.test.js` files that I'd like to be able to hide from NerdTREE when I type some command/key binding. Is there already such a function available? Otherwise it would be a feature request. 👍

**Comment by PhilRunninger** [comment]
Yes, this is already a feature. Just use the `NERDTreeIgnore` setting, like this:
```
let NERDTreeIgnore = ['.*\.test\.js$']
```
Then those files will be hidden in NERDTree. If for some reason, you want to see them in the tree later, just press `f` in NERDTree to toggle them. There is more information available in the help file: `:h NERDTreeIgnore`
