### ISSUE TITLE
create, delete, rename and move files silently?

### ISSUE THREAD

**Issue by cevhyruz** [scrooloose/nerdtree#910]
It's more of a question actually rather than an issue..

I just want to know if its possible to crud operation in nerdtree without firing up the NERDTree menu?

**Comment by PhilRunninger** [comment]
Currently, it's not possible, but it's not hard to add this. For example, add these lines to your `.vimrc`:

```vim
augroup NERDTreeSetup
    autocmd!
    autocmd VimEnter * call NERDTreeAddKeyMap({'key': '<F2>', 'scope': 'all', 'callback': 'NERDTreeDeleteNode'}) |
                     \ call NERDTreeAddKeyMap({'key': '<F3>', 'scope': 'all', 'callback': 'NERDTreeAddNode'}) |
                     \ call NERDTreeAddKeyMap({'key': '<F4>', 'scope': 'all', 'callback': 'NERDTreeMoveNode'})
augroup END
```

The hard part is coming up with keys that make sense and aren't already being used. The same changes (minus the autocmd pieces) can be made in `nerdtree_plugin/fs_menu.vim`, if someone wants to take on a bigger challenge that includes [these issues](https://github.com/scrooloose/nerdtree/issues?q=is%3Aissue+is%3Aopen+label%3A%22multi-file+operations%22).
