### ISSUE TITLE
Error detected while processing VimEnter Autocommands for "*"

### ISSUE THREAD

**Issue by xiebruce** [scrooloose/nerdtree#915]
### Environment
I install it by this way:
``` shell
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
```
this is my `.vimrc`，I also tried to put `autocmd vimenter * NERDTree` to the last line of `.vimrc`, same error.
``` shell
autocmd vimenter * NERDTree
syntax on       "语法高亮
set backspace=2 "设置退格键可以删除非当前输入字
set number      "显示行号，可简写为：set nu，取消：set nonu
set cursorline  "光标所在行显示一条下划线
set hlsearch    "高亮显示查询出来的结果
set incsearch   "搜索的时候逐字高亮匹配
set ruler       "光标移动时，编辑器底部显示当前行号与列号
set nocompatible "不使用vi兼容模式
set autoread    "文件改动时自动载入
set ts=4        "设置tab为4个空格宽
set expandtab   "设置用空格代替tab
set t_Co=256    "terminal Color 支持256色(默认是8色)
```

then I opened a file `vim ~/.vimrc` or open vim itself `vim`, and the error show up at the bottom of the terminal.
![screenflow4](https://user-images.githubusercontent.com/13575500/48316875-217f4480-e624-11e8-9f99-b383677199f8.gif)

* Operating System: macOS Mojave 10.14.1 (iTerm2 v3.2.5)
* Vim version `VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 22 2018 05:24:30)`: 
* NERDTree version `6fe967b`(is the newest, I clone it just now): 
* NERDTree settings applied in your vimrc, if any:
``` vim
as I mentioned above.
```

### Process

1. 
### Current Result

I encountered this error when I open a file by using `vim ~/.vimrc`（actually open any other file is the same）
<img width="472" alt="xnip2018-11-12_02-42-10" src="https://user-images.githubusercontent.com/13575500/48316900-905c9d80-e624-11e8-9737-a4c9c29f673c.png">
``` shell
"~/.vimrc" 13L, 656C
Error detected while processing VimEnter Autocommands for "*":
E492: Not an editor command: NERDTree
Press ENTER or type command to continue
```

### Expected Result

I expect I can use this great plugin, but it's not working on my laptop.

### Screenshot(s)
as I mentioned above.

### Possible Fix

I have no idea about this.

**Comment by PhilRunninger** [comment]
It looks like NERDTree hasn't been loaded yet. You can check by running these commands inside of vim:
1. `:set rtp?` Look for **`~/.vim/bundle/nerdtree`** somewhere in the output.
1. `:scriptnames` This will list all the scripts that were run and the order in which that occurred. You should see the NERDTree plugins listed here, with **`~/.vim/bundle/nerdtree/plugin/NERD_Tree.vim`** being the first of them.

If the above checks fail, review your plugin manager's instructions to be sure you are using it correctly.

**Comment by xiebruce** [comment]
@PhilRunninger It's working now, all I need to do is to add this line `set rtp+=~/.vim/bundle/nerdtree` before this line `autocmd vimenter * NERDTree`, thank you so much!
<img width="504" alt="xnip2018-11-13_15-33-37" src="https://user-images.githubusercontent.com/13575500/48397734-a61faf00-e759-11e8-807e-3b091078a716.png">

**Comment by feiquan123** [comment]
same error when i install `Vim-Plug`  to run vim.

1. `:set rtp?` Look for  `~/.vim/plugged/nerdtree`
2. `mkdir ~/.vim/plugged && cd ~/.vim/plugged`
3. `git clone git@github.com:preservim/nerdtree.git`
4. then enjoy it 😍

**Comment by PhilRunninger** [comment]
@feiquan123 With vim-plug, you don't need to do step 3, and maybe not even step 2. Instead, you would just use vim-plug's `:PlugInstall` command to clone all your plugins, `:PlugUpdate` to pull the newest commits of all your plugins, and `:PlugClean` to remove the ones you no longer list in your `.vimrc`.

**Comment by feiquan123** [comment]
thanks, `:PlugInstall` & `PlugUpdate` working
