### ISSUE TITLE
First Letter Missing in Directory Names and Filenames

### ISSUE THREAD

**Issue by pdrome** [scrooloose/nerdtree#917]
### Environment
* Operating System: Scientific Linux 7.5
* Vim version : 7.4 with patches 1-207 and 209-629
* NERDTree version:  f406af3
* NERDTree settings applied in your vimrc, if any: none

### Process

1. Open NerdTree inside vim

### Current Result
NerdTree cuts off the first letter of file and directory names. This happens when NerdTree is the only plugin installed.

### Expected Result
I expect to see the first letter of file and directory names. 

### Screenshot(s)
I am unable to provide screen shots. However, for directories like this:

dirname1
__filename1
dirname2
__filename2
__filename3

It is displayed like this:

irname1
__ilename1
irname2
__ilename2
__ilename3

### Possible Fix
I have not explored the code for a fix nor have I bisected the commits.  However I first noticed the problem yesterday (November 13, 2018).

**Comment by PhilRunninger** [comment]
@pdrome , Take a look at #916. It contains a workaround that will fix this for you.

**Comment by pdrome** [comment]
That fixed it in my case. Thanks!
