### ISSUE TITLE
Color regression with git & devicons plugins

### ISSUE THREAD

**Issue by avrelaun** [scrooloose/nerdtree#918]
I noticed an unexpected and undesired changed in colors on my NERDTree since commit 6fe967b:
The devicons and git icons were colored as the file extension, which was easier to distinguish.

### Environment

Archlinux
Latest gVim package
Running Vim in terminal (not gVim)

NERDTree
NERDTree-git-plugin
VIM-NERDTree-syntax-highlight
VIM-devicons
(Gruvbox)

### Process

1. Install latest vim and plugins listed above

### Current Result
After commit https://github.com/scrooloose/nerdtree/commit/6fe967b3b357c50c74ca25a3840a66b705593bce :
![nerdtree-after](https://user-images.githubusercontent.com/412102/48569664-a313f280-e902-11e8-8122-89f9068d693e.png)

### Expected (old) Result
Before commit https://github.com/scrooloose/nerdtree/commit/6fe967b3b357c50c74ca25a3840a66b705593bce :
![nerdtree-before](https://user-images.githubusercontent.com/412102/48569635-90012280-e902-11e8-8e5f-ab68f583ffa6.png)

### Possible Fix
Either revert commit 6fe967b or make it configurable.

**Comment by PhilRunninger** [comment]
See my explanation and proposed solution in this comment: https://github.com/ryanoasis/vim-devicons/issues/250#issuecomment-503616655
