### ISSUE TITLE
tcd support

### ISSUE THREAD

**Issue by adelarsq** [scrooloose/nerdtree#919]
Would be nice to change `cd` mapping to allow to use `tcd` instead `cd` on neovim.

Links:
- [How do `cd`, `tcd`, `lcd` work?](https://www.reddit.com/r/neovim/comments/91gbr9/how_do_cd_tcd_lcd_work)
- [Neovim has tab-local working directories now](http://hiphish.github.io/blog/2016/04/22/neovim-tcd/)

**Comment by LuciferK9** [comment]
Is there an update on this?
I would like to tcd when I open it with "t" or "T"

**Comment by adelarsq** [comment]
This option can be used inside the `cd` mapping?
For now I did substitute the command with:

```
diff --git a/lib/nerdtree/path.vim b/lib/nerdtree/path.vim
index d00bb89..eabe9b5 100644
--- a/lib/nerdtree/path.vim
+++ b/lib/nerdtree/path.vim
@@ -87,7 +87,7 @@ function! s:Path.changeToDir()
     endif
 
     try
-        execute "cd " . dir
+        execute "tcd " . dir
         call nerdtree#echo("CWD is now: " . getcwd())
     catch
         throw "NERDTree.PathChangeError: cannot change CWD to " . dir
```

**Comment by PhilRunninger** [comment]
@adelarsq I was able to pick this one up again. Check out the latest version of the PR #1032. I added a new option to choose between `:cd` and `:tcd`. This new option comes into play when you issue the NERDTree `cd` command on a directory node, or when `g:NERDTreeChDirMode` is not zero.

**Comment by adelarsq** [comment]
@PhilRunninger Nice! Just what I was looking for. All my workflow is based on nerdtree, using the bookmarks to manage the projects. On each tab I open a diferent project, so this change helps a lot. Thanks.

I was thinking to send a pull request but didn't have time for that.
