### ISSUE TITLE
auto-toggle nerdtree on pane size

### ISSUE THREAD

**Issue by Fandekasp** [scrooloose/nerdtree#920]
Similar to request made at TagBar: https://github.com/majutsushi/tagbar/issues/512

### Environment

* Operating System:  Arch Linux
* Vim version `:version`: NVIM v0.3.1
* NERDTree version `git rev-parse --short HEAD`: f406af3
* NERDTree settings applied in your vimrc, if any:
    ```vim
	Plug 'Xuyuanp/nerdtree-git-plugin'
	Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
	" NERDTREE
	map <C-n> :NERDTreeToggle<CR>
	"let g:NERDTreeWinSize = 15
	augroup NERD
	    au!
	    autocmd VimEnter * NERDTree
	    autocmd VimEnter * wincmd p
	    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
	augroup END
    ```

### Process

1. Open a file
    ![](https://i.imgur.com/zX67AtJ.png)

### Current Result

No matter what the window/pane size is, NERDTree opens

### Expected Result

When the pane width is smaller than specified (eg 80 chars), I'd like NERDTree to auto-close

### Possible Fix

Either there's some vim setting I'm not aware of (can't believe I'm the only one in years requesting this feature), or we'd need to add some new setting `g:NERDTreeOpenIfPaneSizeMoreThan = 80`

**Comment by PhilRunninger** [comment]
This kind of request should probably be handled in with `autocmd`s in your **vimrc**. Play around with this one and see if it meets your needs. You may run into issues with the window switching that takes place with the `NERDTree` and `wincmd p` commands.
```vim
autocmd CursorHold * if &columns < 90 | NERDTreeClose | else | NERDTree | wincmd p | endif
```

**Comment by Fandekasp** [comment]
@PhilRunninger 	thanks for the tip. After looking at autocmd doc, I updated my vim conf as follow (using terminal neovim within tmux within i3wm, no mouse event).

```vim
augroup NERD
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
    autocmd VimEnter * if &columns >= 90 | NERDTree | wincmd p | endif
    autocmd VimResized * if &columns >= 90 | NERDTree | wincmd p | else | NERDTreeClose | endif
augroup END
```
Strangely, when I try to reproduce this conf for TagBar, the TagBarClose doesn't work (unrelated to this issue).

One thing that annoys me is that this config will be run everytime the vim window changes size, re-running NerdTree even if it's already opened. I wish I could set rules like "if columns count was below 90 before and is now more than 90, only then trigger the command"

**Comment by Fandekasp** [comment]
Thanks for all the tips @PhilRunninger, that helped me write the following config:

```vim
augroup sidebars
    let g:openSidebars = &columns >= 90 ? 1 : 0

    function! ToggleSidebars()
        if (!g:openSidebars && &columns >= 90) || (g:openSidebars && &columns < 90)
            NERDTreeToggle
            TagbarToggle
            wincmd p
            let g:openSidebars = !g:openSidebars
        endif
    endfunction

    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
    autocmd VimEnter * call ToggleSidebars()
    autocmd VimResized * call ToggleSidebars()
augroup END
```

**Comment by PhilRunninger** [comment]
Awesome! Glad it worked out for you.
