### ISSUE TITLE
Shift+o/Recursively Open all nodes does not work

### ISSUE THREAD

**Issue by esn89** [scrooloose/nerdtree#922]
I have my NERDTree in a project directory with some dirs and its subdirs.
Pressing O on the root node does not seem to recursively open my directories.

### Environment
I have NERDTree installed via vim-plug
Using neovim v0.3.1.

* Operating System: macOS
* Vim version `:version`:  neovim v0.3.1
* NERDTree version `git rev-parse --short HEAD`:   370eb5b
* NERDTree settings applied in your vimrc, if any:
    ```
 g:NERDTreeWinSize = 37
g:NERDTreeStatusline = " File Explorer"
g:NERDTreeShowFiles = 1
:map <F5> :NERDTreeToggle<CR>
    ```

### Process

press "C" to go into the directory of your choice with subdirectories and files
press O on that root
1. 

### Current Result

NERDTree: Recursively opening node.  Please wait... DONE
### Expected Result

I expect to see all the directories and subdirectories and their files opened and dispalyed.

**Comment by PhilRunninger** [comment]
I'm not seeing this behavior. Can you retry this with the latest version of NERDTree?

**Comment by esn89** [comment]
Sure thing.  I will close this meanwhile.
