### ISSUE TITLE
why I see ^G in the NERDTree explorer

### ISSUE THREAD

**Issue by reubinoff** [scrooloose/nerdtree#928]
when I enable this plugin, I see the ^G in the NerdTree explorer
![screen shot 2018-12-10 at 11 40 22](https://user-images.githubusercontent.com/15376058/49724466-024ef380-fc72-11e8-9411-f3ba04c2db8e.png)

**Comment by reubinoff** [comment]
workaround is to put:
let g:NERDTreeNodeDelimiter = "\u00a0"
in vimrc

**Comment by PhilRunninger** [comment]
@reubinoff , that is the correct workaround, but I'm curious to know why you are seeing the `^G`. It should be concealed. What version of vim are you using? Are there other plugins that could be interfering with NERDTree? What other settings do you have in your `vimrc`?

Thanks!

**Comment by reubinoff** [comment]
my vimrc: [https://github.com/reubinoff/DotFiles/blob/master/.vimrc](vimrc)
vim version: 
`VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug 17 2018 17:08:16)
Included patches: 1-503, 505-680, 682-1283
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    -mouse_sgr       +tag_old_static
-arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           -mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     -termguicolors
-browse          -footer          +multi_byte      -terminal
+builtin_terms   +fork()          +multi_lang      +terminfo
+byte_offset     -gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
-clientserver    +insert_expand   +packages        +title
-clipboard       +job             +path_extra      -toolbar
+cmdline_compl   +jumplist        -perl            +user_commands
+cmdline_hist    -keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        -langmap         +printer         +visual
-conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             -rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
-emacs_tags      -mouseshape      +startuptime     -xpm
+eval            -mouse_dec       +statusline      -xsmp
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
-farsi           -mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa`

**Comment by keonjeo** [comment]
> workaround is to put:
> let g:NERDTreeNodeDelimiter = "\u00a0"
> in vimrc

Thank you very much. It works for me.

**Comment by PhilRunninger** [comment]
@reubinoff I see from the output of your `:version` command that the **conceal** feature was not included in your build of vim. @keonjeo, I'm just guessing, but it's probably the case for you too. If you can compile your own **vim** from source, you could turn that on with the right switches, and then you wouldn't need the workaround.

Because you don't have the **conceal** feature, the syntax file instead links the **NERDTreeNodeDelimiter** highlight group to the **Ignore** highlight group, which unfortunately doesn't do well with the `^G` character.

**Comment by cozzbie** [comment]
Funny thing is I have the same issue and my `conceal` flag is intact and only this offered answer cleared things up for me.

![image](https://user-images.githubusercontent.com/3672236/49994171-10aa5180-ff89-11e8-94bd-d242de149268.png)

```VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 29 2018 04:52:18)
macOS version
Included patches: 1-550
Compiled by Homebrew```

**Comment by npupko** [comment]
Same problem when I set `syntax off`

**Comment by msimkins** [comment]
Workaround works for me, Standard vim on MAC does not have conceal either

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug 17 2018 17:24:51)
Included patches: 1-503, 505-680, 682-1283
Compiled by root@apple.com
Normal version without GUI.
.......
-conceal         +libcall         -profile         +visualextra
.......

**Comment by cdekok** [comment]
The workaround works only it adds some extra whitespace between the arrow and folder, if I make it empty I cannot open the folder.

**Comment by mtilson115** [comment]
'brew install vim' could also be a viable solution.

**Comment by CharlesB2** [comment]
Can it be detected that vim doesn't have the `conceal` feature, and use appropriate NERDTreeNodeDelimiter?

**Comment by davidpolverari** [comment]
I second @CharlesB2 suggestion too, because it happens with macOS default's vim with no complicated config.

**Comment by PhilRunninger** [comment]
If you all wouldn't mind, I have a new PR out that could use some testing. You can just do
```
git pull
git checkout smarter_delimiter_default
git pull
```
on the NERDTree repo to give it a go. All my vims have the conceal feature, so I can't give it a complete test.

Thanks!

**Comment by davidpolverari** [comment]
Looks good to me by using this PR on macOS. I will do the same checks on Debian to see if there was any regression on that front, because on Debian everything was working properly. I'll let you know ASAP.

**Comment by davidpolverari** [comment]
LGTM on both Debian and macOS fronts now, with their default vim installs. Thanks!

**Comment by PhilRunninger** [comment]
Fix by #963.

**Comment by vrkansagara** [comment]
> workaround is to put:
> let g:NERDTreeNodeDelimiter = "\u00a0"
> in vimrc

This issue is still persist. When I reload `entire .vimrc` at runtime, If I restart vim instance then it work as it is.
![Screenshot_2021-02-20_05-57-12](https://user-images.githubusercontent.com/12006483/108575525-86b45b00-7340-11eb-9e95-e4275d03080a.png)

This issue should be re-open

**Comment by JESii** [comment]
FYI, I'm seeing this occasionally as well after updating many files in the repo, but then it goes away after files are reloaded from the vim prompts (and thus, no screenshot). Mine looked a bit different:
`[ <folder-icon> ]^G...`
I do have `+conceal` because I `brew install vim` which gives the 'huge' features option mentioned above

**Comment by sensorario** [comment]
Try adding these lines to yout vimrc file:

```
set nocompatible
syntax enable
```

**Comment by joebb97** [comment]
Just wanted to say this is still an issue for me, with nvim (or vim, don't think it matters), when I turn `:syntax off`, seems limiting to only support having highlighting on.

**Comment by cuppajoeman** [comment]
To recap the solutions found here, turning `syntax off` in most cases shows this `ctrl-g` in the nerdtree view. Therefore if you want `syntax off` you need to also add ` let g:NERDTreeNodeDelimiter = "\u00a0"` to your `.vimrc` configuration
