### ISSUE TITLE
NERDTree steals focus when pressing <C-c> twice

### ISSUE THREAD

**Issue by diego-treitos** [scrooloose/nerdtree#939]
### Environment

* Operating System:  Ubuntu 18.04
* Vim version `:version`: neovim `0.3.1`
* NERDTree version `git rev-parse --short HEAD`:  `72c3656`
* NERDTree settings applied in your vimrc, if any:

```vim 
""""""" NERDTree
" change arrows
let g:NERDTreeDirArrowExpandable = '🖿 ' 
let g:NERDTreeDirArrowCollapsible = '🗁 '
" close vim if last buffer is NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" Start NERDTree on start
autocmd VimEnter * NERDTree
" Jump to the main window.
autocmd VimEnter * wincmd p
" NERDTress File highlighting
function! NERDTreeHighlightFile(extension, fg, bg, guifg, guibg)
 exec 'autocmd filetype nerdtree highlight ' . a:extension .' ctermbg='. a:bg .' ctermfg='. a:fg .' guibg='. a:guibg .' guifg='. a:guifg
 exec 'autocmd filetype nerdtree syn match ' . a:extension .' #^\s\+.*'. a:extension .'$#'
endfunction
call NERDTreeHighlightFile('jade', 'green', 'none', 'green', 'none')
call NERDTreeHighlightFile('ini', 'yellow', 'none', 'yellow', 'none')
call NERDTreeHighlightFile('md', 'blue', 'none', '#3366FF', 'none')
call NERDTreeHighlightFile('yml', 'yellow', 'none', 'yellow', 'none')
call NERDTreeHighlightFile('config', 'yellow', 'none', 'yellow', 'none')
call NERDTreeHighlightFile('conf', 'yellow', 'none', 'yellow', 'none')
call NERDTreeHighlightFile('json', 'yellow', 'none', 'yellow', 'none')
call NERDTreeHighlightFile('html', 'yellow', 'none', 'yellow', 'none')
call NERDTreeHighlightFile('styl', 'cyan', 'none', 'cyan', 'none')
call NERDTreeHighlightFile('css', 'cyan', 'none', 'cyan', 'none')
call NERDTreeHighlightFile('coffee', 'Red', 'none', 'red', 'none')
call NERDTreeHighlightFile('js', 'Red', 'none', '#ffa500', 'none')
call NERDTreeHighlightFile('php', 'Magenta', 'none', '#ff00ff', 'none')
```

### Process

1. Open vim to edit a file. NERDTree will be open as start per configuration, although the problem also happens if I remove the configuration above and I start NERDTree manually from vim.

2. Move around the file (press `j`/`k`)

3.  Press `<C-c>`  one or 2 times.

### Current Result

NERDTree gets the focus. This is very annoying as I usually press a couple of times `<C-c>` to ensure that I am not in _insert mode_ and then save. Due to this issue I get an error when saving because I am in the NERDTree tab, so I have to switch and carefully save without pressing `<C-c>` again to avoid falling in the trap again.

### Expected Result

No matter how many times I press `<C-c>` NERDTree should not get the focus. Just stay there until I switch manually to it.

**Comment by PhilRunninger** [comment]
I can't reproduce this behavior. `<C-c>` isn't causing any cursor movement for me. Perhaps there is something else in your configuration that is causing this to occur. 

May I ask why you don't use `<Esc>` or `<C-[>` to return to Normal mode? It seems like `<C-c>` isn't intended for that purpose.

**Comment by diego-treitos** [comment]
Indeed using `<Esc>` fixes the problem. I guess I got a bad habit that I have to correct :). 

Sorry for the noise
