### ISSUE TITLE
NERDTree menu shows -- More --

### ISSUE THREAD

**Issue by Ding-Fan** [scrooloose/nerdtree#944]
### Environment

* Operating System: ManjaroLinux 18.0.2
* Vim version `:version`: NVIM v0.3.4
* NERDTree version `git rev-parse --short HEAD`: 72c3656
* NERDTree settings applied in your vimrc, if any:
    ```vim
    ```

### Process

1. Open `nvim` , open `:NERDTree` , tap `m` to open the nerdtree menu
2. Tap `j` or `k` several times

### Current Result

The size of menu window changes, and showing `-- More --`

### Expected Result

Menu works as intended
### Screenshot(s)
![image](https://user-images.githubusercontent.com/26438549/52028434-f54fd180-2549-11e9-9d1b-3dd230797e55.png)

**Comment by Ding-Fan** [comment]
I've tried Termite and xfce4-terminal. Trouble exist.

**Comment by sethen** [comment]
+1

**Comment by sethen** [comment]
+1

**Comment by sourabh-agrawal** [comment]
Just for announcement, i could not generate the issue on following configurations:
```
mac+iterm+zsh
```
which means issue is not there in above conf..
