### ISSUE TITLE
Windows: Vim 8.0: prefix before names

### ISSUE THREAD

**Issue by Konstantin8105** [scrooloose/nerdtree#945]
### Environment

* Operating System:  Windows
* Vim version `:version`:  see picture
![vim sys](https://user-images.githubusercontent.com/16690032/52272138-da6ccb00-2956-11e9-9396-f7329c775fc3.png)
* NERDTree version :  master

### Screenshot(s)

NERDTree

![vim bug](https://user-images.githubusercontent.com/16690032/52272219-29b2fb80-2957-11e9-8b70-fe958f43f0cc.png)

**Comment by PhilRunninger** [comment]
The workaround is to use a non-breaking space `\u00a0` as the node delimiter. See `:h NERDTreeNodeDelimiter`.

**Comment by PhilRunninger** [comment]
The non-breaking space will push everything to the right one character position if you have `:syntax off`, but at least you won't see `^G` anymore.

**Comment by Konstantin8105** [comment]
Thank you @PhilRunninger .
I choose downgrade to `git checkout 15d06b676dfcd92ac9a0bc375668d127f9822539`

**Comment by PhilRunninger** [comment]
@Konstantin8105 , if you wouldn't mind, I have a new PR out that could use some testing. You can just do
```
git pull
git checkout smarter_delimiter_default
git pull
```
on the NERDTree repo to give it a go. All my vims have the conceal feature, so I can't give it a complete test.

Thanks!

**Comment by PhilRunninger** [comment]
Fixed by #963.
