### ISSUE TITLE
Highlighting does not cover text when a file is selected.

### ISSUE THREAD

**Issue by sharkinsspatial** [scrooloose/nerdtree#953]
### Environment

* Operating System: MacOS 10.14.1
* Vim version: NVIM v0.3.4
* NERDTree version: f4d2b30
* NERDTree settings applied in your vimrc, if any:
```
"Nerdtree configurations
let NERDTreeDirArrows=1
let NERDTreeMinimalUI=1
let NERDTreeIgnore=['\.pyc$', 'CVS', '\~$']
let NERDTreeQuitOnOpen = 0
" Open NERDTree in the directory of the current file (or /home if no file is open)
nmap <leader>d :call NERDTreeToggleInCurDir()<cr>
function! NERDTreeToggleInCurDir()
  " If NERDTree is open in the current buffer
  if (exists("t:NERDTreeBufName") && bufwinnr(t:NERDTreeBufName) != -1)
    exe ":NERDTreeClose"
  else
    exe ":NERDTreeFind"
  endif
endfunction
```

### Process
1.  Open Nerdtree and scroll to a file.

### Current Result
File highlighting only displays after the text of the file name.

### Expected Result
Highlighting is consistent between directories and files

### Screenshot(s)
Directory highlighting working as expected
<img width="351" alt="screen shot 2019-02-18 at 5 18 10 pm" src="https://user-images.githubusercontent.com/3671262/52980555-ace93e00-33a8-11e9-81e5-b094d2c285f8.png">

Broken file highlighting
<img width="300" alt="screen shot 2019-02-18 at 5 18 31 pm" src="https://user-images.githubusercontent.com/3671262/52980530-86c39e00-33a8-11e9-94e0-b1d24137d85f.png">

### Possible Fix
This is a new installation on a new machine and I suspect this may be a font related issue (Monaco patched for Powerline).

**Comment by PhilRunninger** [comment]
That highlighting is done by turning on the `cursorline` setting. I am unable to reproduce this error in either Vim or Neovim. It should be highlighting the entire line, so even your directories are incorrect. What happens when you toggle the setting a couple of times: `:set cursorline!`?

BTW, `NERDTreeDirArrows` is an obsolete variable. It won't hurt anything in your `.vimrc`, but it serves no purpose anymore.

**Comment by sharkinsspatial** [comment]
@PhilRunninger Thank you for pointing me in the right direction.  A quick search for `cursorline` issues revealed that this is a recent Neovim regression https://github.com/neovim/neovim/issues/9019. 
 Explicitly setting `highlight NERDTreeFile ctermfg=251` restores entire line highlighting.
