### ISSUE TITLE
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..77[18]..76[3].

### ISSUE THREAD

**Issue by xzungshao** [scrooloose/nerdtree#962]
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..77[18]..76[3]..<SNR>37_activateFileNode[1]..105[1]..121[3]
..176[6]..177[17]..14:
line    1:
E325: ATTENTION

### Environment

* Operating System:  centos7 
* terminal : xshell
* Vim version `:version`:  
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 25 2019 19:14:32)
Included patches: 1
Huge version without GUI.  Features included (+) or not (-):
+acl               +cryptv            -footer            +mksession         +path_extra        +syntax            +viminfo
+arabic            +cscope            +fork()            +modify_fname      -perl              +tag_binary        +vreplace
+autocmd           +cursorbind        +gettext           +mouse             +persistent_undo   +tag_old_static    +wildignore
-autoservername    +cursorshape       -hangul_input      -mouseshape        +postscript        -tag_any_white     +wildmenu
-balloon_eval      +dialog_con        +iconv             +mouse_dec         +printer           -tcl               +windows
+balloon_eval_term +diff              +insert_expand     -mouse_gpm         +profile           +termguicolors     +writebackup
-browse            +digraphs          +job               -mouse_jsbterm     -python            +terminal          -X11
++builtin_terms    -dnd               +jumplist          +mouse_netterm     -python3           +terminfo          -xfontset
+byte_offset       -ebcdic            +keymap            +mouse_sgr         +quickfix          +termresponse      -xim
+channel           +emacs_tags        +lambda            -mouse_sysmouse    +reltime           +textobjects       -xpm
+cindent           +eval              +langmap           +mouse_urxvt       +rightleft         +timers            -xsmp
-clientserver      +ex_extra          +libcall           +mouse_xterm       -ruby              +title             -xterm_clipboard
-clipboard         +extra_search      +linebreak         +multi_byte        +scrollbind        -toolbar           -xterm_save
+cmdline_compl     +farsi             +lispindent        +multi_lang        +signs             +user_commands
+cmdline_hist      +file_in_path      +listcmds          -mzscheme          +smartindent       +vertsplit
+cmdline_info      +find_in_path      +localmap          +netbeans_intg     +startuptime       +virtualedit
+comments          +float             -lua               +num64             +statusline        +visual
+conceal           +folding           +menu              +packages          -sun_workshop      +visualextra
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -std=gnu99   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -ldl

* NERDTree version `git rev-parse --short HEAD`:   72c3656
* NERDTree settings applied in your vimrc, if any:

 """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Nerdtree  plugin Setup
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" auto open nerdtree when open vim ; Remove annotation can take effect.
"autocmd VimEnter * NERDTree
"  auto move the cursor into the main window (file window , not nerdtree window)
autocmd VimEnter * wincmd p
" set keyboards to open or close nerdtree
nnoremap <silent> <F5> :NERDTree<CR>
" set nerdtree window width
let NERDTreeWinSize=25
" change current work directory to same as  NERDTree root directory.
let NERDTreeChDirMode=2
" Set directory where is store bookmarks 
let NERDTreeBookmarksFile=expand('$HOME')."/.vim/NERDTreeBookmarks"

### Process
1. I open the file foo through the nerdtree window in a terminal session。
2. I opened the same file foo through the nerdtree window in another terminal session. At this time, the above error occurred.

**Comment by PhilRunninger** [comment]
@xzungshao , you left off the most important part of the error message. You can issue the command `:help E325` to learn all about what's going on. Basically vim is complaining that you're opening the same file twice, and it needs to know what you want to do about the swap files.

**Comment by PhilRunninger** [comment]
Closing, due to inactivity.
