### ISSUE TITLE
Do not open other files in nerdtree window

### ISSUE THREAD

**Issue by roobre** [scrooloose/nerdtree#971]
Hey all,

I'm having a small but annoying issue I do not know how to solve. Probably because I'm new to vim and honestly I have zero idea of how the vim scripting works. I like nerdtree and I'd like to have it always open (unless I change tabs), so for me the main problem is when I accidentally change a buffer while the nerdtree window is focused. This causes another file to show up on this small window, and there is no way to go back to nerdtree unless I open it again. This is a bit cumbersome.

The [wiki](https://github.com/scrooloose/nerdtree/wiki) mentions a way of locking nerdtree into its window, but it is buggy: If you leave only nerdtree's window open and try to open a file from it, it will open another nerdtree instance instead, effectively locking you until you close vim.

Is there any non-bugged way of acomplishing this?

### Environment
Mostly vanilla VIM with nerdtree

* Operating System: Arch Linux
* Vim version `:version`: 8.1 (2018 May 18, compiled Mar  6 2019 21:38:32)
* NERDTree version `git rev-parse --short HEAD`: `7513f25`
* NERDTree settings applied in your vimrc, if any:
```vim
autocmd vimenter * NERDTree
```

### Process
Add the suggested solution from the wiki https://github.com/scrooloose/nerdtree/wiki

1. Open nerdtree and another file
2. Close the file
3 Try to open another file with nerdtree

### Current Result
Another instance of nerdtree opens.

### Expected Result
The selected file opens.

**Comment by sourabh-agrawal** [comment]
Hi @roobre, I am not sure why this is happening in your case, never faced this issue before, but you can try with my settings.

Try the following settings with both cases of wiki fix that you have mentioned [https://github.com/scrooloose/nerdtree/wiki](url)

* with using fix
* without using fix
and see which one works for you

### **My settings:**
```
autocmd vimenter * NERDTree | wincmd p
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | exe 'cd'.argv()[0] | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
```
I also do use key-binding for hide/show the NERDTree explorer (ctrl+h), which is
```
map <C-h> :NERDTreeToggle<CR>
```
and following key strokes for switching the panes:
* **ctrl**+**w**+**w** to move from left to right in multiple panes
* **ctrl**+**w**+**h** to move to the left pane
* **ctrl**+**w**+**l** to move to the right pane

**Comment by roobre** [comment]
Thanks for your response! However I currently do not have the setup I described on this computer. I'll come back when I'm able to test your solution.

**Comment by PhilRunninger** [comment]
You can change the autocmd to the following snippet. I'll update the wiki too.
```
autocmd BufEnter * if bufname('#') =~# "^NERD_tree_" && winnr('$') > 1 | b# | endif
```
This change adds another check for the number of windows. If there's only one, this will allow you to replace NERDTree with another buffer, but keep it open if there is at least one other window.

Strange things happen when NERDTree is the only window. The next time it's opened, it will appear as a very wide window. Simply press `A` (unless you've set `NERDTreeMapToggleZoom` to something else) twice to resize it to normal width.

**Comment by PhilRunninger** [comment]
I'm closing this issue. Reopen if the above autocmd doesn't work as advertised.

**Comment by danielgatis** [comment]
@PhilRunninger 

We can do a little change to focus on the last open buffer. 

```
au BufEnter * if bufname('#') =~ 'NERD_tree' && bufname('%') !~ 'NERD_tree' && winnr('$') > 1 | b# | exe "normal! \<c-w>\<c-w>" | :blast | endif
```
