### ISSUE TITLE
when using nerdtree, Error message occured (but it works well)

### ISSUE THREAD

**Issue by Mon9oose** [scrooloose/nerdtree#973]
### Environment
* Operating System: CentOS release 6.10 (Final)
* Vim version `:version`: VIM - Vi IMproved 7.2.411
* NERDTree version `git rev-parse --short HEAD`: 7513f25
* NERDTree settings applied in your vimrc, if any:
```vimrc
set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=/home1/irteam/user/ygpark/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/syntastic'
Plugin 'shime/vim-livedown'
Plugin 'scrooloose/nerdtree'

call vundle#end()
filetype plugin indent on

set number
set hlsearch
set autoindent
set incsearch
set scrolloff=2
set wildmode=longest,list
set ts=4
set sts=4
set sw=1
set autowrite
set autoread
set cindent
set bs=eol,start,indent
set history=256
set laststatus=2
set paste
set shiftwidth=4
set showmatch
set smartcase
set smarttab
set smartindent
set softtabstop=4
set tabstop=4
set incsearch
set statusline=\ %<%l:%v\ [%P]%=%a\ %h%m%r\ %F\

map <C-n> :NERDTreeToggle<CR>

syntax on
set textwidth=80
set encoding=utf-8
```

### Process & Current Result

1. open vim
2. using ctrl + n (for nerdtree)
3. following error occures

![스크린샷 2019-04-08 오후 2 27 38](https://user-images.githubusercontent.com/48558786/55700509-8049be00-5a0a-11e9-9a36-ed25317bf3bd.png)

4. when i want to make some files
   - ctrl + n
   - [3] error occured
   - m (open NERDTree Menu)
   - a (add a childnode)
   - write file name and enter
   - fowwing error occures

![스크린샷 2019-04-08 오후 2 38 20](https://user-images.githubusercontent.com/48558786/55700867-f7338680-5a0b-11e9-9143-f565c8908ad8.png)

5. when i want to open some files
   - ctrl + n
   - [3] error occured
   - enter the file
   - following error occures

![스크린샷 2019-04-08 오후 2 36 01](https://user-images.githubusercontent.com/48558786/55700817-b89dcc00-5a0b-11e9-9398-89832e780350.png)

### Expected Result
* i just want to disappear this error message
* luckily, nertree work very well (except error messages)

**Comment by PhilRunninger** [comment]
@Mon9oose, the `strdisplaywidth()` was added to vim 7.3, and the `and()` function was added to vim 7.4. Is there a way you can upgrade to a newer version of Vim? I will look for a backward compatible alternative, but a Vim upgrade could be quicker.

**Comment by Mon9oose** [comment]
@PhilRunninger, thx your opinion.
this server using many other server engineers. (Dev server)
I will share this issue, and propose an upgrade vim :-)

**Comment by PhilRunninger** [comment]
I'm reopening this to make sure I give it the attention it needs.

**Comment by PhilRunninger** [comment]
I wasn't able to figure out an alternative for `strdisplaywidth()`, so I upped the minimum required version of vim to 7.3.
