### ISSUE TITLE
How to position the cursor on a file instead of NERDTree after automatically opening NERDTree

### ISSUE THREAD

**Issue by caijwei** [scrooloose/nerdtree#975]
I use autocmd vimenter * NERDTree to have NERDTree open automatically
But the cursor is positioned on NERDTree, I want it to be positioned on the file to be edited.

**Comment by PhilRunninger** [comment]
Use `autocmd VimEnter * NERDTree | wincmd p` This will move the cursor back to the previous window after creating the NERDTree buffer.
