### ISSUE TITLE
vim nerdtree *.xml--->*.ml???

### ISSUE THREAD

**Issue by ProZoom** [scrooloose/nerdtree#976]
![image](https://user-images.githubusercontent.com/18642118/55964588-9031fe00-5ca7-11e9-976b-8f950a5eeeec.png)

how i solved this problem??

**Comment by PhilRunninger** [comment]
You haven't given any instructions for reprising the issue. Please update so someone can help you.

**Comment by PhilRunninger** [comment]
No response. Closing.
