### ISSUE TITLE
Makes neovim unresponsive sometimes if open 

### ISSUE THREAD

**Issue by jmolero** [scrooloose/nerdtree#977]
I've been experiencing some freezes while editing with NERDTree open. At first I wan't sure what was causing it, but when it happens, and if I press 'Ctrl + C' the cursor jumps from the buffer to NERDTree. 

Because it seems to happen randomly, I recorded a profile while having NERDTree open and there are two functions that I think are related and take a lot of time to finish: 

```
...
FUNCTION  132()
Called 77803 times
Total time:  89.973046
 Self time:  82.466573

count  total (s)   self (s)
77803              0.093272     let output = ""
77803              0.073563     if a:drawText ==# 1
                            
75037              0.189942         let treeParts = repeat('  ', a:depth - 1)
                            
75037              0.095053         if !self.path.isDirectory
33957              0.057335             let treeParts = treeParts . '  '
33957              0.017351         endif
                            
75037  15.747967   0.393643         let line = treeParts . self.displayString()
                            
75037              0.170280         let output = output . line . "\n"
75037              0.038472     endif
                            
                                " if the node is an open dir, draw its children
77803              0.110611     if self.path.isDirectory ==# 1 && self.isOpen ==# 1
                            
 8297  11.797732   0.042068         let childNodesToDraw = self.getVisibleChildren()
                            
 8297  11.825736   0.048327         if self.isCascadable() && a:depth > 0
                            
                                        let output = output . childNodesToDraw[0]._renderToString(a:depth, 0)
                            
                                    elseif len(childNodesToDraw) > 0
83334              0.079186             for i in childNodesToDraw
75037              0.301768                 let output = output . i._renderToString(a:depth + 1, 1)
75037              0.052369             endfor
 8297              0.004502         endif
 8297              0.003430     endif
                            
77803              0.071584     return output
...
FUNCTION  163()
Called 52516 times
Total time: 243.747307
 Self time: 132.798087

count  total (s)   self (s)
52516  43.435002   0.353528     call self.path.refreshFlags(self.getNerdtree())
187182              0.308178     for i in self.children
134666  70.724309   0.476447         call i.refreshFlags()
134666              0.112921     endfor
...
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
52516 243.747307 132.798087  163()
77803  89.973046  82.466573  132()
...
```

### Environment

* Operating System:  Mac OS X
* Vim version `:version`: NVIM v0.3.4
* NERDTree version `git rev-parse --short HEAD`: 7513f25 
* NERDTree settings applied in your vimrc, if any:
```
let NERDTreeMinimalUI = 1
let g:nerdtree_tabs_open_on_console_startup = 1
let NERDTreeAutoDeleteBuffer = 1
```

### Process

1. It happens randomly while editing files with NERDTree open

### Current Result

It makes neovim unresponsive for a while

### Expected Result

I like to have NERDTree always open but it interferes while editing buffers.

**Comment by adberard** [comment]
I just found out that I had the same error, did you found a fix ?

**Comment by jmolero** [comment]
I haven't, unfortunately. I'd like to look for one but I don't know much vim script yet.

**Comment by PhilRunninger** [comment]
1. How many directories have you opened in your NERDTree, even if currently collapsed, and are there lots of files in your directories. Very large trees can experience poor response.
1. Do you have other plugins that interact with NERDTree, such as [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin) or [vim-devicons](https://github.com/ryanoasis/vim-devicons)?
1. The first function in your profile output is `s:TreeFileNode._renderToString()`, and I suspect it may be being called indirectly from the second function in your profile output - `s:TreeDirNode.refreshFlags()`.
1. Issue the following command in Vim:
    ```
    :echo g:NERDTreePathNotifier.GetListenersMap()
    ```
    If it shows a dictionary, these are lists of callback functions that are invoked in certain situations. Mine, shown below, are defined in the [nerdtree-buffer-ops](https://github.com/PhilRunninger/nerdtree-buffer-ops) plugin:
    ```
    {'init': ['NERDTreeHighlightOpenBuffers'], 'refreshFlags': ['NERDTreeHighlightOpenBuffers'], 'refresh': ['NERDTreeHighlightOpenBuffers']}
    ````
    We're specifically interested in the ones for the `'refreshFlags'` key. It's possible that these callback functions are the source of your slow response.

**Comment by PhilRunninger** [comment]
@jmolero , I don't want to close this one just yet, but I need your feedback to investigate further. Thanks.

**Comment by romariolopezc** [comment]
In my case, it was slow because of this plugin: https://github.com/Xuyuanp/nerdtree-git-plugin

**Comment by jmolero** [comment]
I was also using nerdtree-git-plugin, but I think I tried disabling it and it still happened. Same for vim-devicons. I also had many directories collapsed like in  node_modules, so I tried adding it to the nerdtree ignore list. I can't remember if I tried all these fixes at once.

I don't use nerdtree currently.

**Comment by Cyberlane** [comment]
I have this problem, and am actively using NerdTree so happy to provide some info if that helps?

Answering your questions in order @PhilRunninger 

1. Since I move around mostly with fzf, I generally open only enough directories to reach my destination which could be 5 or 6 levels deep. There are a number of other files/directories that appear in NerdTree, but I do not touch them.

2. only `tiagofumo/vim-nerdtree-syntax-highlight`

3. N/A

4. 
```
{'init': ['NERDTreeGitStatusRefreshListener', 'NERDTreeWebDevIconsRefreshListener'], 'refreshFlags': ['NERDTreeGitStatusRefreshListener', 'NERDTreeWebDevIconsRefreshListener'], 'refresh': ['NERDTreeGitStatusRefreshListener', 'NERDTreeWebDevIconsRefreshListener']}
```

**Comment by PhilRunninger** [comment]
@Cyberlane Some thoughts on your answers...

It doesn't really matter if you touch files/directories in NERDTree; handling the other NERDTree plugins' events requires **all** of the nodes to be visited. 

You have not one, but three NERDTree plugins: [vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight), [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin), and [vim-devicons](https://github.com/ryanoasis/vim-devicons). One of those was identified above to be a culprit, and another one is known to be very slow.

I think this is clearly a case of a lot of processing being done on a large number of NERDTree nodes. Sometimes we just need to balance our need for speed versus the nice-to-have extra bits. There is definitely some slowness inherent in NERDTree, but to fix it would require it to be completely torn apart and rebuilt from the ground up. That's something I don't want to tackle at the moment.

**Comment by Cyberlane** [comment]
@PhilRunninger you're completely right, sorry.

I did want to add some information for other people who might look at this issue in the future though. I was able to keep my current setup and get all the performance problems removed simply by switching from iTerm to Alacritty which can handle all the additional processing a LOT better.
