### ISSUE TITLE
Copy filepath menu item

### ISSUE THREAD

**Issue by Seybo** [scrooloose/nerdtree#982]
Is there a way to add `Copy path` to `Menu` items?

**Comment by PhilRunninger** [comment]
Can you elaborate more? What exactly would that option do? Doesn't `(c)opy the current node` do what you want?

**Comment by Seybo** [comment]
hmmm... i don't think so. Or i'm missing something. What i want is to be able to easily share the selected (in the tree) file path. As a text. To copy it to clipboard

**Comment by PhilRunninger** [comment]
@Seybo, if you want to checkout branch 982, you can take a look at the new menu item. I tested it on Mac and Linux. I'll verify it works OK on Windows before merging it into master.

**Comment by Seybo** [comment]
Great! Thanks!
