### ISSUE TITLE
Reveal file relative to root when doing NERDTreeFind on a file.

### ISSUE THREAD

**Issue by AvinashKrSharma** [scrooloose/nerdtree#984]
Require option to reveal file relative to root when doing NERDTreeFind on a file.

### Environment
Plugin manager is vim-plug. And I use NERDTree disabled by default.

* Operating System: Mac OSX Mojave 10.14.3
* Neovim: v 0.3.1.: 
* NERDTree version `git rev-parse --short HEAD`: e126b87
* NERDTree settings applied in your vimrc, if any:
```vim
 Plug 'scrooloose/nerdtree' | Plug 'Xuyuanp/nerdtree-git-plugin' | Plug 'tiagofumo/vim-nerdtree-syntax-highlight'

 " ----for Nerdtree
  let g:nerdtree_tabs_open_on_gui_startup=0
  let g:NERDTreeQuitOnOpen=1
  let g:NERDTreeMinimalUI=1
  let g:NERDTreeMouseMode=2
  let g:NERDTreeShowHidden=1
  let g:NERDTreeKeepTreeInNewTab=1
  let g:NERDTreeIgnore=['.git$[[dir]]', '\.js.map$[[file]]']

  " ----for vim-nerdtree-syntax-highlight
  let g:NERDTreeFileExtensionHighlightFullName = 1
  let g:NERDTreeExactMatchHighlightFullName = 1
  let g:NERDTreePatternMatchHighlightFullName = 1
```

### Process

1. Say I open vim from this directory `~/my-project`.
2.  Then I open a file say, `dirA/dirAA/fileA.abc` not using NERDTree.
3. Now do `:NERDTreeFind`

### Current Result

The NERDTree buffer that opens up, doesn't show the file relative to the root, i.e. my-project. Instead it shows the file relative to the directory `dirAA`. 

### Expected Result
I expect it to be is have the NERDTree show files from the root and highlight the file I searched for inside it.

### Screenshot(s)
Expected:
<img width="654" alt="Screenshot 2019-04-20 at 1 32 27 PM" src="https://user-images.githubusercontent.com/6334228/56454597-db67a300-6370-11e9-8428-869287e02579.png">

Actual:
<img width="675" alt="Screenshot 2019-04-20 at 1 32 46 PM" src="https://user-images.githubusercontent.com/6334228/56454601-e6223800-6370-11e9-8ff3-b212bdab7e80.png">

**Comment by PhilRunninger** [comment]
@AvinashKrSharma 

This should be working as you expect. Can you double check your `:pwd` before you run `:NERDTreeFind`? The only way to get your reported behavior is if the open file is not contained within the current working directory.

**Comment by PhilRunninger** [comment]
No response. Closing.
