### ISSUE TITLE
ALE syntax check not working when opening files through NERDTREE

### ISSUE THREAD

**Issue by renan-cunha** [scrooloose/nerdtree#987]
### Environment

* Operating System: Ubuntu 18.04.2 LTS
* Vim version: Neovim 0.3.4
* NERDTree version : 5.0.0

### Process

1. Install ALE syntax check https://github.com/w0rp/ale
2. Open a file with NERDTree

### Current Result

The syntax check don't run

![image](https://user-images.githubusercontent.com/32102378/56674375-504c1d00-6690-11e9-9379-71766988d5ad.png)

### Expected Result

![image](https://user-images.githubusercontent.com/32102378/56674398-5a6e1b80-6690-11e9-8a19-4b657b9a1b9a.png)

**Comment by PhilRunninger** [comment]
I can't duplicate this issue; ALE is working find on my machine with both `vim 8.1` and `nvim 0.3.4`. Can you provide any more information to help diagnose this?

**Comment by renan-cunha** [comment]
I found that the problem appears only when I put the below line on init.vim

``` 
let g:ale_linters_explicit = 1
```

My ALE config is 

```
let g:ale_linters_explicit = 1
let b:ale_linters = {'python': ['mypy', 'flake8']}  
```

**Comment by PhilRunninger** [comment]
I still can't reproduce your issue. The linters are working no matter how I open them, and with both settings of `g:ale_linters_explicit`.

Have you reported this to the ALE devs?

**Comment by PhilRunninger** [comment]
No response. Closing.
