### ISSUE TITLE
setting debug option to msg will casue NERDTree to output an error message when opening files

### ISSUE THREAD

**Issue by jdhao** [scrooloose/nerdtree#988]
### Environment

* Operating System:  Windows 10 and CentOS 7.4
*  Neovim version `:version`:  0.4.0
* NERDTree version `git rev-parse --short HEAD`:  7513f25
* NERDTree settings applied in your vimrc, if any: None
### Process

1.  Use the following `init.vim`:

```
if has('win32')
    set runtimepath+=~/AppData/Local/nvim/plugged/nerdtree
else
    set runtimepath+=~/.local/share/nvim/plugged/nerdtree
endif

set debug=throw
```
Open neovim using the above configuration

```
nvim -u init.vim
```

2. Open NERDTree with `:NERDTree` command and open a file in the sidebar.

### Current Result

An error occurs, the message is like:

> Error detected while processing function nerdtree#ui_glue#finvokeKeyMap[1]
> E94: No matching buffer for ^D: \code_exprt\char_in_ font.py$

### Expected Result

No error occurs.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/16662357/56726677-cf6d4e00-6781-11e9-8f9d-9ee31f7db4a0.png)

### Possible Fix

I found that resetting the debug option removes the error. But I am not sure if there are any bugs inside NERTree?

**Comment by PhilRunninger** [comment]
No this is not a bug in NERDTree. The statement causing your message is
```vim
let winnr = bufwinnr('^' . self._path.str() . '$')
```
`bufwinnr()` returns -1 
> if buffer {expr} doesn't exist or there is no such window.

When you `set debug=throw`, it will 
> also throw an exception and set |v:errmsg|.

`bufwinnr()` is doing exactly what it's supposed to do, and NERDTree is handling it appropriately. See `:h 'debug'` and `:h bufwinnr()` for more details.
