### ISSUE TITLE
Delete multiple files

### ISSUE THREAD

**Issue by GabrielDuarteM** [scrooloose/nerdtree#990]
With netrw you can do enter visual mode, select lines and press "D" to delete multiple files. 
I expected Nerdtree to have something similar, but I couldn't find anything searching. Is there a way of doing this?

**Comment by PhilRunninger** [comment]
@GabrielDuarteM , checkout my newest plugin, based on a gist I wrote. It will allow you to do what you requested, with the `dd` keystroke though. It also can open the selected files, in split or in tabs, if so desired.

https://github.com/PhilRunninger/nerdtree-visual-selection

**Comment by GabrielDuarteM** [comment]
Awesome, just installed it, and that's exactly what I was looking for!

Still, not sure why this isn't baked into nerdtree... IMO it's such a common use case (at least when coming from vscode and similars).

**Comment by PhilRunninger** [comment]
I'm going to keep it separate for now. I have some ideas for implementing it differently inside NERDTree.
