### ISSUE TITLE
vim broke trying to install nerdtree, now it ignores my vimrc

### ISSUE THREAD

**Issue by gartha1** [scrooloose/nerdtree#996]
I am running osx

I am using macvim  /usr/local/bin/vim   but the issue occurs with /usr/bin/vim too

I tried to install nerdtree.

I followed (or tried to follow), the instructions  
https://github.com/scrooloose/nerdtree/blob/master/README.markdown

that mentioned these commands

(This line from the nerdtree readme)
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree

Then the next line in the nerdtree readme required apt-vim

And to install apt-vim I used a curl line mentioned https://github.com/egalpin/apt-vim  I used curl -sL https://raw.githubusercontent.com/egalpin/apt-vim/master/install.sh | sh

When  I did the apt-vim line it asked me if I wanted to install various things.. First I said no.. But then I did it again and said yes to each thing.

continuing with the instructions  in the nerdtree readme

apt-vim install -y https://github.com/scrooloose/nerdtree.git

:helptags ~/.vim/bundle/nerdtree/doc/

I reloaded vim and saw that my vimrc is no longer being read. I have one line there saying set shortmess=I (which allows vim to start with a blank screen rather than bram's screed), and when I run vim,  bram's screed appears. So it is now ignoring my vimrc.

**Comment by gartha1** [comment]
I fxied it, I did the same line but with delete, (delete is a bit stronger than remove so a bti better)
apt-vim delete  -y https://github.com/scrooloose/nerdtree.git
then ran vim and it gave an error mentioning /users/apple/.vimrc
that had two lines in it about execute ppathogen#inifect() and call pathogen#helptags()  i.e. stuff from apt-vim

well, my .vimrc is ~/.vim/vimrc  i.e. /users/apple/.vim/vimrc so  I moved the file the error mentioned( /users/apple/.vimrc) ,  .vimrc to old.vimrc
leaving just my vimrc file.
then it ran fine.

**Comment by PhilRunninger** [comment]
Maybe it's not clear in the README, but **pathogen.vim** and **apt-vim** are two separate ways to install NERDTree. You shouldn't do both instructions. There are other was to install plugins, such as [Vundle](https://github.com/VundleVim/Vundle.vim) and [vim-plug](https://github.com/junegunn/vim-plug). I suggest you read the related documentation for the plugin manager you choose to use.
